### ISSUE TITLE
Point of contact

### ISSUE THREAD

**Issue by jimmydorry** [darklordabc/Legends-of-Dota-Redux#1]
I would like to have a quick chat with you. What's your steamcommunity link? 

I can be found here (http://steamcommunity.com/id/jimmydorry/), but too many people have tried adding me, so I need to invite you via the link you leave here or a comment you make on my profile.

**Comment by darklordabc** [comment]
What do you want? To talk about this Git? This is just a sandbox git for me to play around with new ideas and abilities without being hampered all the redtape. I'm not going to publish this.

**Comment by jimmydorry** [comment]
This is to hopefully prevent irreparable action happening to LoD, and your involvement in it. While I think your dedication and time investment into LoD is worthy of praise, you have also been the sole cause of frustration to Ash. The situation can still be fixed, I believe, but will require a small amount of communication.

**Comment by darklordabc** [comment]
Well I'm here if you want to chat. https://steamcommunity.com/profiles/76561198054179075/

**Comment by jimmydorry** [comment]
Cheers. I have to go to work, so I'll write up my thoughts and send them to you later today.
