### ISSUE TITLE
[Suggestion] UI categories header

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1001]
Adding a Separator Header between sources/categories in the Skill Selection screen for clarity and time saving sake.
For example: Default/Default Neutrals/Books & Flesh Heaps/Dusk/IMBA...

**Comment by darklordabc** [comment]
Like a new dropdown box? I dont understand really what you are requesting here.

**Comment by AugurM** [comment]
No, something like some space and/or a return to the beginning of the line.
I'm aiming at some comfort in navigating the abilities.
