### ISSUE TITLE
Two invis abilities available with noinvis mode 

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1006]
1. Patch 7.06 Windranger Level 20 Talents are now: Windrun grants invisibility // +120 Powershot Damage
Windrun - should be banned in this mode
2. some ability creating illusion and making your hero invisible
![invis](https://cloud.githubusercontent.com/assets/24685202/26072215/70c5ca74-39b3-11e7-87dc-9547a0c45921.png)

**Comment by darklordabc** [comment]
Thanks, fixed.
