### ISSUE TITLE
[Troll Build] Rearm Redux + Flesh Heap CDR + Nimbus Cloud + Lightning Bolt + Multicast

### ISSUE THREAD

**Issue by iprobie** [darklordabc/Legends-of-Dota-Redux#1009]
basically just a bunch of cooldown reduction + nimbus cloud + multicast. even worse coupled with heroes with high cdr talents such as Sniper or Windranger.

**Comment by LoDfan** [comment]
Agree this is troll build and may be countered only nonstop rage casting + all other cd reduction skills on sniper/wr. I've already written about Rearm + cd reduction skills https://github.com/darklordabc/Legends-of-Dota-Redux/issues/988 but TideSofDarK closed it without a comment
