### ISSUE TITLE
Spawning standart heroes / heroes not spawning   [7.06] [bug]

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1011]
original:
Часто, после начала игры, несколько игроков либо получают стандартных героев, либо не возрождаются.

translate google:
Often, after the start of the game, several players either get standard heroes, or do not revive.

![20170516222226_1](https://cloud.githubusercontent.com/assets/28739948/26124860/b2c3eb06-3a88-11e7-96e0-3aad5592b7fa.jpg)
![20170516222219_1](https://cloud.githubusercontent.com/assets/28739948/26124872/bb52dc28-3a88-11e7-921c-02c40eef6321.jpg)
![20170516220617_1](https://cloud.githubusercontent.com/assets/28739948/26124879/c6dde8e4-3a88-11e7-9128-3d473d411925.jpg)
![20170515220723_1](https://cloud.githubusercontent.com/assets/28739948/26124882/cf0aaade-3a88-11e7-8c0f-4f41fa3d8c87.jpg)
![20170516231333_1](https://cloud.githubusercontent.com/assets/28739948/26126204/6a0694cc-3a8d-11e7-9c42-9ad5dde49599.jpg)

**Comment by LoDfan** [comment]
It's very similar to https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1007

**Comment by darklordabc** [comment]
I can't reproduce this bug, everytime I've played I've never seen it happen.

**Comment by LoDfan** [comment]
I saw this bug on EU servers. May be that's the reason?

**Comment by darklordabc** [comment]
Yes okay I have experienced this bug now, we'll try to fix it asap.

**Comment by darklordabc** [comment]
Pretty sure this is fixed
