### ISSUE TITLE
Lightning Storm + Pulse Nova + AGHANIM'S SCEPTER [7.06] [bug]

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1013]
original:
при включении "Pulse Nova" с "AGHANIM'S SCEPTER" способность "Lightning Storm" начинает очень часто срабатывать

translate google:
When you turn on "Pulse Nova" with "AGHANIM'S SCEPTER", the ability "Lightning Storm" starts to work very often

![20170517010814_1](https://cloud.githubusercontent.com/assets/28739948/26130443/677064c6-3a9d-11e7-8c4a-3412ff7511fb.jpg)
![20170517011014_1](https://cloud.githubusercontent.com/assets/28739948/26130479/9e1d079a-3a9d-11e7-80bb-807bc4f380a7.jpg)

![20170517005858_1](https://cloud.githubusercontent.com/assets/28739948/26130366/0e5e18c4-3a9d-11e7-8394-54b1ff280c16.jpg)

**Comment by DankBudd** [comment]
there was a similar problem with mirana scepter, this might need to be recoded

**Comment by darklordabc** [comment]
I've made Lighting Storm and Pulse Nova a troll combo, I'll leave this issue open until we can fix the problem properly.

**Comment by Yahnich** [comment]
problem is created because it checks the 4th ability index, which will never or rarely be Pulse Nova, thus it'll be missing the lightning storm strike interval special value; fix is recoding the ability, forcing pulse nova into the 4th ability slot or adding the specialvalue to every single ability

**Comment by WolfRat** [comment]
Actually, the interval key is part of the lightning storm ability:

"interval_scepter"			"1.75"

So my guess is that the lightning storm used by LoD is somehow missing this key value.
