### ISSUE TITLE
Compendium towers shoot invisible projectiles

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1016]
In 10-tower lanes, save for the first and the eight towers in base, the others are visually modified by the compendium and shoot non-visible projectiles.

**Comment by darklordabc** [comment]
What map is this in? I mainly play all_allowed and I havent noticed it.

**Comment by AugurM** [comment]
The dota one, in local.

**Comment by RissaWasTaken** [comment]
Can confirm, Dota map in non-local, compendium towers' projectiles are invisible.
