### ISSUE TITLE
Give Players Final 15 Seconds to Pick Hero

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1018]
Ever since playing LoD there is always that one player takes too long picking skills, misjudges how much time is left and doesn't pick a hero, and then complains about it. This change should finally solve that very ancient problem. 

If the time is up to finish picking skills and there is a least one player who hasn't selected a hero, the game should force all players to go to the hero pick screen, disallow skill picking and have popup text "PICK A HERO!", this will give the slow players a final 15 seconds to pick a hero.

**Comment by LoDfan** [comment]
This change will just make all players wait 15 sec more. It's better to add sound notifications about remaining time.

**Comment by darklordabc** [comment]
Added
