### ISSUE TITLE
Side gunner custom ability works in phase shift

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1022]
As everybody knows there are heroes are able to be in phase shift permanently. And side gunner makes such heroes unstoppable pushers and killers (pulse nova make them only killers).
So add plz Side Gunner+Phase Shift=troll combo.
It's better to add phase shift a single mode op ability (as rearm) because there a lot other combos with phase shift (but you need 2 players) that can't be beaten. My favorite one is Arcane Symbios + permanent phase shift host = 100% win if game is 15+ min.

**Comment by darklordabc** [comment]
I agree, its now a single player ability.
