### ISSUE TITLE
Too long switch voting cd

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1023]
For example single carry wants to switch teams and it's declined.
Another support hero wants to switch, but he can't because of very long voting cd. 

Expected: other heroes are able to start switch voting

**Comment by darklordabc** [comment]
Hmm, I'm going to go against this because I havent really seen it be a problem and if I just lowered the cooldown it will mean players will spam votes more and I feel thats been fixed with the cooldown as it is.
