### ISSUE TITLE
[Allied Chat] 

### ISSUE THREAD

**Issue by iprobie** [darklordabc/Legends-of-Dota-Redux#1024]
Can we please have allied chat during drafting phase?

**Comment by DankBudd** [comment]
this is already a thing. but for whatever reason it is /team instead of /allies #686

**Comment by darklordabc** [comment]
Should it be allies?

**Comment by darklordabc** [comment]
Either way, I've changed the default chat channel to team now instead of all chat

**Comment by DankBudd** [comment]
dota's normal chat uses /allies. so yeah, i think it should be allies

**Comment by darklordabc** [comment]
What does it use for all chat? /all?

**Comment by DankBudd** [comment]
yes, i believe so.

**Comment by darklordabc** [comment]
Allied chat is now default, however its still "team".
