### ISSUE TITLE
Remove changes about additional hero pick time

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#1026]
Please remove changes about additional hero pick time because sometimes game starts when 1 min and 30 sec are left. I hate such buggy changes.

**Comment by darklordabc** [comment]
I think the issue was that when all heros were choosen it would start the game no matter what, I think this has been fixed.

**Comment by LODonly** [comment]
I played today and this bug was reproduced several times

**Comment by darklordabc** [comment]
The fix was only uploaded like 4 hours ago, so I dont know if you have tested it with the fix.

**Comment by LODonly** [comment]
ah ok
