### ISSUE TITLE
Giff us Thrill of the Hunt camera shenanigans back

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1027]
SWAT: Reborn has this somewhere in their code for a chat command that changes camera distance for individual players.

    PlayerChatCommands.CAMERA_MIN_DISTANCE = 1200 -- -view 0 distance
    PlayerChatCommands.CAMERA_MAX_DISTANCE = 2400 -- -view 100 distance

    -- Moves camera
    function PlayerChatCommands:view(playerInfo, args)
        local distance = self:getNumerFromArgument(playerInfo, args[1])
        if distance then
            -- Distance must be between 0 and 100
            distance = math.max(0, math.min(100, distance))
            distance = math.floor(PlayerChatCommands.CAMERA_MIN_DISTANCE + (PlayerChatCommands.CAMERA_MAX_DISTANCE - PlayerChatCommands.CAMERA_MIN_DISTANCE) * (distance / 100.0))

            --mode:SetCameraDistanceOverride( distance ) -- Sets it for everyone it seems
            CustomGameEventManager:Send_ServerToPlayer(playerInfo.player, "util_set_camera_distance", {distance = distance} )
        end
    end

and from their panorama util file

    function SetCameraDistance( args ) {
        $.Msg("Setting camera distance to: " + args.distance)
        GameUI.SetCameraDistance( Number(args.distance) )
    }

**Comment by darklordabc** [comment]
@SwordBacon, ya interested?

**Comment by SwordBacon** [comment]
Yes, this is how it was intended to work in the first place (only affecting the casting player's camera). It does take some panorama to get working, so I'll have to look more into it.

**Comment by SwordBacon** [comment]
We did it fam
