### ISSUE TITLE
Glimmer Cape can be bought when No Invis Items are on

### ISSUE THREAD

**Issue by iprobie** [darklordabc/Legends-of-Dota-Redux#1028]
was in a game where someone bought Glimmer Cape and I thought, oh no invis isn't on, but I couldn't buy Silver's Edge

**Comment by DankBudd** [comment]
if glimmer can be bought then does that mean shadow amulet can be bought?

**Comment by iprobie** [comment]
no, you can't buy shadow amulet.
and I forgot to add, in order to get the glimmer cape, you have to purchase the cloak first or the whole thing right away.
