### ISSUE TITLE
How to Change the Host Settings?

### ISSUE THREAD

**Issue by ZcythierO** [darklordabc/Legends-of-Dota-Redux#1031]
I've been played this game first solo only, to test some skills and learn how to play it. Now that I learn to play it, I invited my friends to play it. But Since we've played it I can't change the Host settings and it was a Voting options. We enabled OP skill option but OP skills are automatically banned too. Please fix if there's a problem and How to change the Host Settings. WE don't know how, so please tell it us.
-
Sorry for grammar haha 😂😂😂

**Comment by darklordabc** [comment]
Play Dota map

**Comment by ZcythierO** [comment]
Ty boss Darklord
