### ISSUE TITLE
Suggesting skill and hero picks/bans to allies

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1034]
in lod you used to be able to right click skills and there would be a drop down with among other things, a button to suggest that skill to your allies. it would write something like this in chat
`  player_name suggests picking <ability icon> Fury Swipes `
and fury swipes would be clickable, letting you pick the skill

**Comment by darklordabc** [comment]
This is a good idea. But arent you a programmer DankBudd? Couldnt you add this?

**Comment by DankBudd** [comment]
i have little experience with panorama

**Comment by darklordabc** [comment]
Theres only one way to change that :wink:

**Comment by TideSofDarK** [comment]
#1037 here it is
