### ISSUE TITLE
Bulwark Strike and Unwavering Stance are unaffected by CDR

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1035]
Those two Molten Lord abilities, which are awesome by the way, display reduced Cooldown Reduction but still stay unavailable the full initial cooldowns (respectively 5 and 20/18/16/14).

**Comment by Deathtal** [comment]
Glad you like them! Other abilities also have this problem, Infernal Blade is one of them. I currently don't know how to fix this problem, but I can recommend using Arcane Art if you want to reduce the cooldowns.

**Comment by DankBudd** [comment]
@Deathtal redux has this in their util file: `CDOTABaseAbility:GetTrueCooldown()`
as the functions name suggests, it gets the cooldown after reductions.

**Comment by Wouterz90** [comment]
That function was garbage, but it should be fine now!

**Comment by darklordabc** [comment]
Should be fixed now, if not, we will reopen case.
