### ISSUE TITLE
Reconnection Bug, No Team

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1041]
original:
вот что я часто вижу после переподключения к игре

translate google:
That's what I often see after reconnecting to the game

![20170530233318_1](https://cloud.githubusercontent.com/assets/28739948/26606021/f2535f52-4598-11e7-8d35-63a8ddd77aa5.jpg)

**Comment by darklordabc** [comment]
Hmm I think this is a very hard bug to fix, I think @TideSofDarK has tried before, we will try to look into it again.

**Comment by darklordabc** [comment]
Duplicate here: https://github.com/darklordabc/Legends-of-Dota-Redux/issues/985
