### ISSUE TITLE
Bounty Runes do nothing if a player has disconnected

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1045]
When playing all_allowed, the bounty runes will eventually give no gold or exp and have no popup graphics when you collect them, unsure why this occurs, and what triggers them to break.

**Comment by DankBudd** [comment]
i think it happens when you shift queue picking up a bounty rune

**Comment by darklordabc** [comment]
I dont think thats it Dank.

**Comment by ReactorXIV** [comment]
I think I found why it happens and when it gets fixed. If someone disconnects from the game the bounties don't work. If he reconnects they work again. There might be more to it but players connecting and disconnecting definitely affects it.

**Comment by darklordabc** [comment]
Hmm thats very interesting @ReactorXIV, somebody or me has to confirm if thats the problem, I'll try to get around to it.
