### ISSUE TITLE
Test of Faith (Teleport) OP Custom Ability Suggestion

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#1048]
I forgot skill name, which teleports creeps back. An OP version which allows to tp even hero-creeps aka bear, golem, familiars. and maybe lower cd, that'd really help

**Comment by XAgent1990** [comment]
Bear already has return, but for those others I wouldn't see much use of that.
You mean Test of Faith (teleport kind)

**Comment by Exchy** [comment]
I mean using ToF which would give ability according to perk. So I could add abilities those listed units
