### ISSUE TITLE
False Promise + Nothl Protection

### ISSUE THREAD

**Issue by ReactorXIV** [darklordabc/Legends-of-Dota-Redux#1062]
When False Promise buff ends and you should take lethal damage from the delayed damaged that is "stored" with False Promise while having Nothl Protection you stay alive with 2 health (i think) and Nothl Protection doesn't activate or go to cooldown. It might have to do something with how Nothl Protection interacts with hp removal?

**Comment by darklordabc** [comment]
Nothl Protection and False Promise is now troll combo because buggy interaction

**Comment by darklordabc** [comment]
Not the best soultio
