### ISSUE TITLE
Try to help Chinese translation

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1063]
Translated stuffs before 1600 line. Keep updating.
[addon_schinese.txt](https://github.com/darklordabc/Legends-of-Dota-Redux/files/1066747/addon_schinese.txt)

**Comment by darklordabc** [comment]
@testiclesbomber could you possible upload this file yourself, I'm worried I wont do it right. I'll give you permission to modify files.  https://github.com/darklordabc/Legends-of-Dota-Redux/invitations

**Comment by 1ran-wang** [comment]
Thx, Got it.

**Comment by xuxiakan** [comment]
I got following compilation errors. There are some extra/missing characters in related files.
> node app.js
Unexpected character "4" at line 1592 (offset 149994)
Unexpected character "4" at line 1592 (offset 149994)
Unexpected character "买" at line 3629 (offset 299949)
Unexpected character "D" at line 4315 (offset 347218)
Unexpected character "D" at line 8098 (offset 808511)
Unexpected character "D" at line 8337 (offset 834328)
Unexpected character "永" at line 8823 (offset 887749)
Unexpected character "永" at line 8826 (offset 887885)
Unexpected character "永" at line 8829 (offset 888034)
Unexpected character "永" at line 8832 (offset 888170)
Unexpected character "永" at line 8835 (offset 888307)
Unexpected character "永" at line 8841 (offset 888687)
Unexpected character "б" at line 377 (offset 23817)
Unexpected character "l" at line 450 (offset 29301)
Unexpected character "<" at line 486 (offset 33406)
Unexpected character "h" at line 761 (offset 65871)
Done loading languages!
Loading custom units...
Loading abilities...
Unexpected character "D" at line 5566 (offset 190200)
Unexpected character "D" at line 5624 (offset 192201)
Loading custom abilities...
Unexpected character "u" at line 1 (offset 0)
Loading heroes...
Done saving custom heroes!
Making links!
Finished saving english!
Finished saving english!
Finished saving schinese!
Finished saving schinese!
Finished saving russian!
Finished saving russian!
Finished saving korean!
Finished saving korean!
Finished saving koreana!
Finished saving koreana!
Done saving custom units file!

**Comment by darklordabc** [comment]
does it work ingame? Sometimes I get unexepected character errors too, but it doesnt seem to break anything.

**Comment by xuxiakan** [comment]
It still compile and I can find two folders to be added properly. However, the add-on won't show up in Workshop Tools and the mod can't be launched.

**Comment by darklordabc** [comment]
Compiling is bugged currently, valve broke the symbolic links that the compiler makes.
