### ISSUE TITLE
CDR from masteries works incorrectly with some passives

### ISSUE THREAD

**Issue by ReactorXIV** [darklordabc/Legends-of-Dota-Redux#1065]
Some passives from custom abilities don't get reduced cd from masteries even though they should and their tooltip displays that they do. Passives that I have tested and were bugged are Nothl Protection, Last Resort and an other one that just heals u when u drop low health (cant remember name, next to nothl). Passives that worked correctly were Reincarnation, Greater Bash, Jinada but these are not custom abilities.

**Comment by darklordabc** [comment]
@TideSofDarK could you check this out?

**Comment by 01der** [comment]
some passives now get reduced for multiple octarines if you skill elemental mastery. I had a game today with nothil protection and unwavering stance, both with 4 sec CD.

**Comment by OtsoTurpeinen** [comment]
Fixed for next patch

**Comment by OtsoTurpeinen** [comment]
I mean the octarine issue.
