### ISSUE TITLE
[Suggestion] Ability set : Disease

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1068]
I know it might not be the best place to put them.
But here they are for reference, if someone is interested in implementing those.

**Disease-based set of abilities**.
Low Damage-over-Time abilities, spanning large distances and slowly amping up, contagious and only dispellable through direct healing to full health or fountain/shrine dipping (excluding lifesteal and passive regeneration). For the damage, it should start very small, being HP-removal, and increase as the unit health deteriorate, an inverted Current % Health if you will.
There could also be some variant of the abilities without damage just debuffs, such as Minus Received Healing, Magic Resist Decrease, turn-rate slow, increased manacosts, healthcost for attacks, reducing attack range, increasing cooldown, reduced ... Possibilities abound.
The abilities should cost health in addition to mana, mostly for flavor.

1. "*Healthy Carrier*" single target medium CD "buff", applicable on enemy and allies alike (think Ion Shell). Either very long lived or permanent "buff" making it immune to the abilities in this set (or at least some) from the caster (as there could be other *strains* in play). At regular interval, with very little to no visible effect, the carrier release an AoE infecting the surrounding enemy units, turning them in non-immune carriers.

2. "*Plague vision*" Passive ability that ping diseased-laden units all over the map, through the fog-of-war (or just on the minimap) without revealing or giving you vision of them. Its only purpose is to monitor your work. (This doesn't necessarily need to be its own ability, this could be inherent to disease debuffs)

2bis. "*Plaguebringer*" Passive ability increasing the rate of ticking of nearby carriers as well as the potency (increased damage and/or effects). Nearby carriers increase the movement speed, granting phased movement from a certain point on (or higher level of the ability).

3. "*Cesspool*" Each activation change the "payload" of your disease abilities.
By default, and permanently if you did not pick this Cesspool ability, the disease deal damage (increasingly as the infected health gets worse). Cesspool switches between the various debuffs to replace the default damaging component.

4. "*Fever*" Large AoE Reflection-like ability, with uncontrollable quasi-invulnerable illusions of heroes being spawned next to them and starting to attack them. This also reduce the line of sight and blind the minimap to solely focus on their hero, the immediate surrounding and the illusion of themselves. Ideally, the illusion should only be visible capable of being interacted with by its original. We are messing with perceptions here. Illusion should not inflict permanent damages, only debuffs.

5. "*Pandemic*" **Ultimate**ability. Infection rate flares up globally, doubling the radius of transmission and allowing them to stack for the duration, transforming concentration of infected units into highly damaging/debuffing areas.

**Comment by darklordabc** [comment]
Interesting ideas, I wonder if @Wouterz90 or @DrTeaSpoon are interested in implementing one or some of them?
