### ISSUE TITLE
Can't select any ability

### ISSUE THREAD

**Issue by Ralayax** [darklordabc/Legends-of-Dota-Redux#1070]
Hey guys,
First thank you for this amazing mod.

Since the last couple upgrades I can't select any ability in the drafting screen.
It last worked on the 08/06/2017.

Also I play in solo OP mode against bots if this helps (local version)

Cheers,
Ralayax

**Comment by AugurM** [comment]
In fact it works, only the icons aren't displayed in your selection.

**Comment by darklordabc** [comment]
I think this has been fixed? If so, please close this issue.

**Comment by Ralayax** [comment]
Yeah icons are now displaying
