### ISSUE TITLE
[Suggestion] Flesh heap health regen and mana regen

### ISSUE THREAD

**Issue by Ralayax** [darklordabc/Legends-of-Dota-Redux#1072]
Hello,

it might be nice to build those flesh heaps.
I would have done a pull request but I have no idea how dota modding works.

Regards,
Ralayax

**Comment by TheRisen41** [comment]
Yes please i would like that too

**Comment by darklordabc** [comment]
Sure if @Wouterz90 wants to make them, I'm fine with them being in.

**Comment by Wouterz90** [comment]
#1073 Needs testing
