### ISSUE TITLE
Troll combos

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1075]

**Comment by 1ran-wang** [comment]
Thunder Musket will trigger on illusions. = OP rating    

Chakra magic and rearm with cooldown reduction = infinity abilities. 
Fixed by add chakra magic into cooldown family.

**Comment by darklordabc** [comment]
@testiclesbomber are you still going to make the PR about thunder musket?

**Comment by darklordabc** [comment]
Chakra Magic and Rearm are already troll combos

**Comment by 01der** [comment]
i agree that thunder musket should not work on illusions.
