### ISSUE TITLE
Hero Pick Tab Shows No Heroes

### ISSUE THREAD

**Issue by AnimaThunder** [darklordabc/Legends-of-Dota-Redux#1076]
Also, the build selector perma-loads. The Skills tab still works, and you can still random a hero or select attributes. Noticed first while using local server version in All_Allowed mode.

**Comment by xuxiakan** [comment]
Same in normal version

**Comment by darklordabc** [comment]
Ops, should be fixed now.

**Comment by darklordabc** [comment]
Thanks for quickly reporting
