### ISSUE TITLE
[troll] Napalm and Custom Abilities

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1081]
I haven't tested all of the abilities but many of the custom abilities that have dmg-tickrates of under 0.5 should not work with napalm or be considered troll like rot+napalm.

**Comment by darklordabc** [comment]
If you have them, I can make them troll combos, or better yet, you can do a pull request and I'll merge it.

**Comment by 01der** [comment]
ok i will do that, i guess i was hoping you could program it so that napalm doesn't work with any skills that have dmg-tickrates of less than 0.5

**Comment by Wouterz90** [comment]
I think it should trigger those, but just once per 0.5 second.

**Comment by darklordabc** [comment]
You would need a custom napalm skill maybe? I don't imagine that would be hard but is there any other way Todo it?

**Comment by 01der** [comment]
I like the changed napalm idea. The advantage to just blacklisting napalm, is that it would even work with new skills then.
