### ISSUE TITLE
[Bug] Subterranean Invincible Jungle Monsters

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1085]
Despite the catchy title, it appears something(s) get spawned at jungle camps (usually not right at the start but over time). I've seen clipping jungle creeps but most of the time, they can't be seen.
They can attack you sometimes, but mostly they are invulnerable.

You can see them through the auto-attacks of Trickshot Passive, some range and ideally Chi Strike or Coup de Grace for visible effects.
While they are not a big issue, who knows how many get spawned over the course of a game, and it might bog down the game at some point.

**Comment by DankBudd** [comment]
this also happens with towers sometimes but the towers usually disappear after a few seconds. after they are destroyed creeps and even heroes who are using attack move will continue to attack the tower that is no longer there.

**Comment by darklordabc** [comment]
Were u guys using multiply creep mutators?
