### ISSUE TITLE
[bug] new simple abilities issues

### ISSUE THREAD

**Issue by xuxiakan** [darklordabc/Legends-of-Dota-Redux#1089]
Blade Mail OP, Tenacity, Tenacity OP can't be load.

Anti-bash and Anti-bash OP have no effect on caster itself.

**Comment by darklordabc** [comment]
Thanks, fixed blademail OP and tenacity, anti-bash is a bit more complicated, for now just dont cast it on yourself, there is no benefit todo that, you already have the protection you dont need to cast on self to benefit.

**Comment by xuxiakan** [comment]
Looks like they can be loaded but have no effect.

**Comment by darklordabc** [comment]
I'm pretty sure this is fixed, let me know if its not.
