### ISSUE TITLE
Infernal Blade + Witchcraft

### ISSUE THREAD

**Issue by Wolsken** [darklordabc/Legends-of-Dota-Redux#1090]
Issue:
**Witchcraft** removes 4 second cooldown of **Infernal Blade** turning it into a passive that melts any hero without spell immunity down quickly (as all attacks trigger it, it stacks with itself, it has max-hp based damage, and it is refunded for all of its mana). Other Auto-casts of a similar nature such as **Liquid Fire** completely ignore **Witchcraft** at the same time. 

Possible Solution:
Allow all auto-casts with cooldowns to be reduced as other spells are (to 1 second) and remove the ability for **Infernal Blade** to stack with itself (instead refresh the duration of the debuff). 
OR
Completely remove the interaction between **Witchcraft** and **Infernal Blade**.

This is just an example of inconsistency within DotA abilities that when combined in an environment such as LoD, could benefit from a little bit of tweaking to make builds fun and straightforward.

Edit: WC is a single player ability so this issue is low-prio but could help with the balance of abilities later when more things are added.

**Comment by OtsoTurpeinen** [comment]
Isn't witchcraft single player ability anyway?

**Comment by Wolsken** [comment]
Yeah which makes this a low-priority issue but I still think it could free the game up a bit creatively if things worked consistently.

**Comment by 1ran-wang** [comment]
I think we should have a redux version of Witchcraft. which can reduce
cooldown to 5 sec(instead of 1).

2017年7月7日 上午5:02，"Wolsken" <notifications@github.com>写道：

**Comment by darklordabc** [comment]
@Wouterz90 you did infernal blade, is there some special reason it is reduced by cooldown reduction abilities, could you change it so that it is unaffected like the other auto-cast abilites

**Comment by Wouterz90** [comment]
I don't think the interaction with other auto cast abilities is any different, but aren't they all shorter than 2 seconds? Infernal Blade stacks with itself in the original game, we have already recreated it because it was causing too many issues. I think it not stacking with itself is the best solution, though I dislike it.

**Comment by darklordabc** [comment]
Closing this because witchcraft is single player ability. However if anybody wants to code a fix for this as a PR, I'll merge it.
