### ISSUE TITLE
Some particle effects are broken

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#1092]
Just playing some support build. and I've noticed that particles for Caduceus staff, heroes never die, extraplanar pact and Godfall are not appearing for the most part, except for the particles which are taken from the main game. So, can I presume that a fair few abilities with particles from external custom games will be broken too? D: they work, if they hit and stuff, they just don't show up and stuff.

**Comment by TideSofDarK** [comment]
Uploaded Caduceus and heroes never die particles. Other ones seems to be present. They are in precache blocks as well. Create issue again with screen shots if same stuff happens
