### ISSUE TITLE
Warlock perk change

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1093]
could you improve warlocks perk because it seems a little bit weak mayby if you change it to that he receives wards ability and wards ability op if single player ability is enabled or you can set up timer to receiving wards for example every xxx minutes

**Comment by edotenseilove** [comment]
also wards ability is instantly refresherd by tempest double clone

**Comment by 1ran-wang** [comment]
There are so many issues with perks XD. Like Monkey king's perk is unusable. and Wind runner's perk doesn't work at all. Alchemist's perk too weak... Hope Darklord have enough time to fix them haha...

**Comment by darklordabc** [comment]
Improved Warlock's Perk.... he gets more wards now.
