### ISSUE TITLE
Tempest Double and redux version dont despawn

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1096]
and because they dont despawn, they can spawn their own double.....
you see where this is going.
very broken if abused

**Comment by darklordabc** [comment]
They dont despawn? With omniguard or just by themselves? 

Ive made omniguard a troll combo with tempest doubles and I've made it so tempest doubles no longer have the tempest double ability so they cant cast it again even if they can survive until the cooldowns off.

**Comment by 01der** [comment]
no additional skills needed, tempest double is simply bugged and instead of despawning it gets reduced to 1 health (which is no problem if you cast it in fountain).

**Comment by darklordabc** [comment]
I'm assuming this is fixed now @01der, let me know if its now and I'll reopen.
