### ISSUE TITLE
High dropout rate during banning-screen

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1097]
I have experienced most people (including myself) dropping out at the start of banning.
It is obviously a timeout issue because my screen is frozen for sometimes 10 sec.
I assume its the loading of the ability icons that might cause the freeze. It could also be the connection to the lod-stats-server to get the builds, that causes the timeout.
In any case i suggest trying to start the banning screen with the hero selection.
And maybe put a random wait time before the stat-server-connection so that not all 10 people connect at the same time.
If the icons could be precached during option voting/setup, that might also help the issue.
Because of frozen screen the banning time gets also really short, so maybe adding 10-20 sec wouldn't hurt.
I think the new spawning system has improved the dropout problem a bit, but it is still the most frustrating one in lod.
Thank you for all your hard work.

**Comment by darklordabc** [comment]
Thanks, good suggestions, will look into this.

**Comment by 01der** [comment]
i also have noticed that if i reconnect while banning is still going on, i get to spawn, after that i am stuck with the 1 sec spawn timer...So that extra banning time would really come in handy. if you could make it a guarantied 1 min of banning time that would at least solve the not spawning for me, because i could reconnect during banning and then get a hero.
