### ISSUE TITLE
[Suggestion] Alchemist Perk

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1098]
Alchemist has some of the worst stats in the game and his perk in lod is currently also not very helpful.
I almost never see him picked in lod.
I suggest this perk:
For every lvl Alchs BAT is reduced by 0.02 (maybe with a cap at lvl 25 or 30)
that would mean that at lvl 15 he would have the BAT of 1.4 that AM and Juggernaut have
and at lvl 25 a BAT of 1.2 which is the same as Chemical rage at lvl 2.
I think that would make him a viable choice for some builds.

**Comment by darklordabc** [comment]
Shouldn't his perk be income related?

**Comment by darklordabc** [comment]
Or some kind of innate chemical rage?

**Comment by DankBudd** [comment]
his current perk is weak, but it should definitely stay income related.
just increase the gold his perk gives him, or maybe change it to a free skill point in greevils greed whether he has it or not

**Comment by 01der** [comment]
i was thinking of some kind of innate chemical rage, the way i described above.
income related is very tricky, because the usefulness of the perk varies a lot on the lobby settings (ofc all_allowed being the most used).
But if you start at lvl 16 with 10000 gold, or if you have a gold tickrate of 20 then the 2 gold or free greevils greed doesnt do much.
I know that lobby settings can always make perks useless (wtf mode makes CDR useless).
But in my experienced goldtickrate and starting gold get changed a lot in custom lobbies.
just my take on the situation. :)

**Comment by darklordabc** [comment]
I've made it just a free level in greevils greed, which I think is fairly useful.
