### ISSUE TITLE
Tempest double OP

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1099]
Can you make tempest double op without preventing clones recieving this ability.

**Comment by darklordabc** [comment]
Ah I could but what is the purpose of that? Is anyone going to use it just for that difference?

**Comment by edotenseilove** [comment]
there were very good combos with tempest double which were based on repeating this ability with realm for example creating a huge army of creeps from definitly not dota spawn abilities and many more and i really believe that  many players would appreciate it

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/bc245e96279bc453d875480a7e036e4e922f9e5e
Added OP version of the ability
