### ISSUE TITLE
Arcana Symbiosis + Ally with Infest = Infinte Mana Troll Combo

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1100]
I'm getting reports of a troll combo with arcane symbiosis
Hero A is using arcane symbsios on Hero B and then Hero B is infesting Hero C, and when Hero A uses spells - like ball lighting - Hero B does not lose any mana because he is infested, meaning that they can use infinite ball lighting and teleport anywhere on the map.
One fix, which may be a bit complicated is that when the symbiote host infects another hero, the symbiote transfers to the infested hero, it does not stay on the hero thats inside the other hero.

**Comment by 01der** [comment]
i tried this combination by accident when there was an infester on my team and i had symbioses, it really is broken. Fortunately you need at least 2 people to work together to get it to work, so i don't see it abused much. TBH i think the basic infest+rot+restauration combo is also op with the right infest target at least.
So maybe a change to infest could solve 2 problems at once.
If infest behaved more like symbioses we wouldn't have this problem.

**Comment by darklordabc** [comment]
@OtsoTurpeinen is the fix done yet?

**Comment by darklordabc** [comment]
This should be fixed in a latest commit
