### ISSUE TITLE
add option to disable ai bot controller for towers

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1101]
as the title

**Comment by darklordabc** [comment]
But the bots will behave very badly with multiple towers, they wont attack the extra ones, and they wont be able to finish the game.

**Comment by edotenseilove** [comment]
maybe add option to choose weaker ai bot controler which wont teleport bots back to base

**Comment by 1ran-wang** [comment]
I think best solution is play with people, bots are for testing and we really need you guys be active in lod. XD.

**Comment by darklordabc** [comment]
Closing this as I don't think its going to happen. Bots need improvements I agree, but this is not the way todo it.
