### ISSUE TITLE
"Ghost Players" prevent their team from earning exp

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1112]
it has happened to me twice now, cause unknown. 

first time it affected entire radiant team but all of dire could still get exp. 
second time 3/5 of radiant could not earn exp.

**Comment by darklordabc** [comment]
Never encounted this, will need more info.

**Comment by DankBudd** [comment]
this has not happened to me again and ive heard no one else complain about it since.
 i guess this is a pretty rare thing? or perhaps it was accidentally fixed

**Comment by DankBudd** [comment]
encountered it again.. i think it has something to do with players reconnecting and not getting a hero. (that happens if they dc during ban phase and dont come back until in-game)

**Comment by OtsoTurpeinen** [comment]
I've encountered this bug once. Not sure how to recreate it but how it works is that when game sets your level to 4, it skips giving you experience enough to be on that level so you need to earn until you have that much. After that it works as normal.

**Comment by 01der** [comment]
i have heard couple of players complain about this in game, couldnt verify it though. My guess was also that the "ghostplayers" are responsible.

**Comment by DankBudd** [comment]
confimed to be caused by the ghost players, when there is a ghost player present their team will earn no exp.
 when the ghost player leaves their team can earn exp again
