### ISSUE TITLE
When any legion commander duels all legion commanders will get spell immunity

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1113]
until the duel ends.
not sure if it only happens when an LC duels

**Comment by 1ran-wang** [comment]
Can't reproduce this bug. I only see LC get spell immunity in 0.1 sec. Any further detail?

**Comment by darklordabc** [comment]
I'll wait on somebody to confirm this bug before trying to fix it.

**Comment by OtsoTurpeinen** [comment]
The bug exists. Even reading the code reveals that much. "OnAbilityStart(keys)" triggers on all ability cast's, not just on casts from parent of the modifier. the perk never checks who the caster is.
suggested fix new line at 43
`if hero ~= keys.caster then return end`

**Comment by darklordabc** [comment]
Fixed here, thanks for the tip Otso
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/e1587c374bf8a792689c5d38fa248f27cbcf32c6
