### ISSUE TITLE
skill "Thirst for life"

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1114]
Google translate: 
Tell me what is the point of pumping this skill

missing health for one bonus:15%(max ~6 bonus )
regenetation per bonus: 
1 lvl - 0.5%(max regeneration 3%)
2 lvl - 0.1%(max regeneration 0.6%)
3 lvl - 0.15%(max regeneration 0.9%)
4 lvl - 0.2%(max regeneration 1.2%)

![20170722002329_1](https://user-images.githubusercontent.com/28739948/28483810-c20236e0-6e77-11e7-81c2-2d58145a3b02.jpg)

**Comment by russo-2025** [comment]
In addition, the values from 0.1 to 0.3 are very small

**Comment by 1ran-wang** [comment]
I'm trying to buffing those weak skills but there are so many work to do, so just wait for now. XD...

**Comment by 1ran-wang** [comment]
Thanks for the feedback!

**Comment by 1ran-wang** [comment]
Oh the thing is lv1 data is broken. Should be 0.05%

**Comment by russo-2025** [comment]
Google translate: 
0.2% are very small, check for yourself

**Comment by 1ran-wang** [comment]
I change it to 1%->3%.  (when you are 0% hp (Which is maximum regen))

**Comment by 1ran-wang** [comment]
Fixed in pr.
