### ISSUE TITLE
Consumable Echo Sabre, Vlads and S&Y

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1117]
if your gunna make some passive items consumable you might as well add them all.

theres also ~~aether lens~~(added), divine rapier and aghanims scepter, but i think those three should be excluded

**Comment by darklordabc** [comment]
Hmm, the difference between these consumeables and the other ones, is that the previous ones are all late game items, i.e. items that you wouldnt replace in your inventory eventually, if we start making non-lategame items consumeable, I don't know where we would draw the line. Bracers be consumeable too?

**Comment by 1ran-wang** [comment]
I think the thing is echo sabre has unique ability echo hit. And also
linkin sphere Could you make it upgradable. (after upgrade it will became
consumable)

2017年7月26日 上午7:17，"darklordabc" <notifications@github.com>写道：

**Comment by DankBudd** [comment]
the line should be drawn where items are fully upgraded. dont make components consumable.
