### ISSUE TITLE
grapeshot ability and missing model of phantom dreadnaught

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1118]
this ability is is really interesting but i dont know why is mana cost increasing on upper levels but no benefit for this ability so that for this ability is better skill it only for one time and i think this ability need some upgrade also particle effect is wierd

**Comment by edotenseilove** [comment]
also i dont see phantom dreadnaught ship model now

**Comment by 1ran-wang** [comment]
#1119 Made it stronger at level 4, but weaker at level 1.

**Comment by edotenseilove** [comment]
thank you
