### ISSUE TITLE
dragon blood op bug

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1120]
if i pick this ability i dont get tallent 2x dragon blood but if i choose dragon blood normal + op version and  skill only op version tallent work

**Comment by darklordabc** [comment]
Unfortuntely the talent replacement system only works with 1 ability, it does not check for anymore than 1, including the variant abilities. Its something we have to improve.

**Comment by darklordabc** [comment]
I'm closing this and redirecting here, as there will be lots of these kind of bugs
https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1095
