### ISSUE TITLE
New version of Anti-Bash

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1121]
Current [Anti-bash] can only affect on player that picking bashes. However, you can't view other players builds in our new hero-builder. So picking this ability became a kind of gambling.(Overkill or totally useless)

1. Make anti-bash became a item. and nerf it.

Bash-shield: 
     Passive: You will at most get bashed once per 1.5 sec. 
     Active: reflect all bashes in 3 sec.

But make too many new item in Lod maybe not a good solution as we always having new player.

2.Make a new version of anti-bash:

Anti-stun: For any stun affect on you, you have 10% 20% 30% 40% chance to reflect it back to caster(or remove it instantly).

**Comment by darklordabc** [comment]
I'd prefer to make it anti-stun instead of the item.

**Comment by DankBudd** [comment]
closing issue because anti-stun has been made
