### ISSUE TITLE
Reopen pls Troll combo Overload + Morph [balance] #1040

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1123]
it's possible to pick overload with custom morph

**Comment by LoDfan** [comment]
Also shtorms perk works with it as well

**Comment by LoDfan** [comment]
It's better to change shtorm's perk because there are several troll combos with it

**Comment by darklordabc** [comment]
Good points. I've made the Morphs troll combos with overload and I've replaced Storm Spirit's perk to Mana Aura, instead of Overload, if you think of a better perk to give him, let me know here, otherwise please close this issue.

**Comment by 1ran-wang** [comment]
Im thinking about give him a no damage version of overload.

2017年7月26日 上午7:14，"darklordabc" <notifications@github.com>写道：

**Comment by LoDfan** [comment]
Some more ideas:
Restore mana for 10-15% of damage dealt (mana vampirism)
Every x seconds casts Static Remnant same level as it's learned (same as mirana's ahs or clockwerk's perk)
Damages every attacker by lighting dealing 0.1 of Shtorm's int

**Comment by darklordabc** [comment]
Restore Mana is what Leshrac has, and the random static remnants are a bit random and uncontrollable, also I'd rather not give any type of overload or else it will still be abuseable with toggles

**Comment by LoDfan** [comment]
I didn't know Leshrac has such perk. I believed it's still spell vamp aura

**Comment by 1ran-wang** [comment]
What about 
1. Only receive half damage to all Thunder abilities. 
2. When casting Thunder ability, grant 2 sec spell immunity.
3. 20% cooldown reduction on all thunder ability.
4. Free level 1  Razor's [Unstable Current]

**Comment by darklordabc** [comment]
I like the unstable current idea seems to fit the hero more, I'll change the mana aura to unstable current.

**Comment by LoDfan** [comment]
`When casting Thunder ability, grant 2 sec spell immunity.`
too op

`Free level 1 Razor's [Unstable Current]`
Is it better for razor?

**Comment by darklordabc** [comment]
@LoDfan I had the exact same thought. Unstable current is better for Razor. He has another perk, but its related to static link and probably unpopular.

**Comment by darklordabc** [comment]
Plus Razor is fairly unpopular, it seems like he should have a better perk like having unstable current. 
http://ec2-52-59-238-84.eu-central-1.compute.amazonaws.com/wordpress/#heroes

**Comment by darklordabc** [comment]
What if he gets 3 intelligence for every point put in lighting abilities?

**Comment by LoDfan** [comment]
`but its related to static link and probably unpopular`
He has low stats, slow, and week perk. If perk was smth like "Spell immunity" while using static link or cd reduction for ult or longer ult duration

**Comment by LoDfan** [comment]
Since it's possible to get talent for picked ability (if correct hero is chosen) there is no reason to pick low stats and slow heroes.

**Comment by darklordabc** [comment]
For Razor, I'll give him unstable current lvl 1 AND his current static link perk.

**Comment by LoDfan** [comment]
What about shock talent: all enemies attacking Storm Spirit will be shocked and their movement is slowed by 100% for 0.2 sec (or stunned for 0.01 sec - just for canceling channeling abilities)

**Comment by darklordabc** [comment]
Good talent suggestions, but I dont think anyone is available to make them right now, so I'm closing this issue, if somebody wants to volunteer to code the perk, we'll add it.
