### ISSUE TITLE
Rewrite team logic to allow for more than 2 teams and TDM style maps

### ISSUE THREAD

**Issue by ShortVix** [darklordabc/Legends-of-Dota-Redux#1124]
There's a lot of code that looks like it needs to be rewritten to for LOD-Redux to support TDM style maps like overthrow i.e. 2v2v2v2v2v2 style game play.

As a first step I'd like to gather everywhere that has team logic defined i.e:

https://github.com/darklordabc/Legends-of-Dota-Redux/search?utf8=%E2%9C%93&q=DOTA_TEAM_GOODGUYS&type=

https://github.com/darklordabc/Legends-of-Dota-Redux/search?utf8=%E2%9C%93&q=DOTA_TEAM_BADGUYS&type=

Is there any other terms other than DOTA_TEAM_GOODGUYS and DOTA_TEAM_BADGUYS?

**Comment by OtsoTurpeinen** [comment]
https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API#DOTATeam_t
