### ISSUE TITLE
[May be a Bug] Custom Passive abilities CD reduction problem

### ISSUE THREAD

**Issue by xuxiakan** [darklordabc/Legends-of-Dota-Redux#1132]
I'm not sure if it is a bug or you did intentionally. 

A lot of custom passive abilities, for example tower abilities, won't work with CD reduction.

I found out those abilities use ability:GetCooldown(ability_level) instead of ability:GetTrueCooldown(ability_level).
I know some abilities could be imbalanced after CD reduced. But I still prefer to let CD reduction works with them.

**Comment by 1ran-wang** [comment]
Yeah I agree CD reduction should work on all abilities. I can do the data balance parts.

**Comment by AugurM** [comment]
As far as I know, this one is intentional, as it would be rather easy to have perma-stun/bash/blind otherwise.

**Comment by LoDfan** [comment]
It's currently not hard to have perma-bash build. You just need to pick talent +10% of bash and have 0.2 sec attack time. Also custom passive 60% of additional attack at 10 stack will help you.
But LoD is not 1-1 game and it's easy to counter perma-bash build.

**Comment by LoDfan** [comment]
There could be a problem with auto shallow grave (if cd = 3 sec)

**Comment by AugurM** [comment]
We are talking AoE Immunity-ignoring permanent Stun/Bash here.
Towers are fun like that.

**Comment by darklordabc** [comment]
My thoughts are on this that a) It would be good in theory for custom passives to have reduction like normal original passives, but b) Cooldown reduction is already pretty cancerous strategy, adding shorter passives will probably create a whole new avenue of cancerous builds, so I kind of think its not a great idea to make passives reduce, even if it is consistent.
