### ISSUE TITLE
[Bug] Roshan won't take damage when NeutralCreepPower option on

### ISSUE THREAD

**Issue by xuxiakan** [darklordabc/Legends-of-Dota-Redux#1134]
Neutral Creep Power option upgrades Roshan constantly. But after 50 mins in game, Roshan won't take any incoming damage.

The problem comes from modifier_neutral_power, in file abilities/modifiers/modifier_neutral_power.lua.
MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE becomes -100% after 50 mins in game time.

I suggest to have a lower bound for incoming damage, which makes Roshan can be killed in late game.

**Comment by darklordabc** [comment]
Good find, I've made it so that Roshan now has a maximum damage reduction of 70%.
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/766dc09e74741a44ee942232e41c5013cea5ede8
