### ISSUE TITLE
Is it possible to make another version for testing before master branch is deployed on prod?

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1135]
I see there are a lot of bugs with new added abilities and it happens because of bad testing.
Is it possible to test new changes before they are added to update without installing Workshop Tools?

**Comment by darklordabc** [comment]
Its easy todo, but whos going to test it? Its a manpower issue, not a technical one.

**Comment by LoDfan** [comment]
I and my friend are going to test it. Mostly on weekends.

**Comment by LoDfan** [comment]
Anyway 2 QA guys is better than nothing :)

**Comment by russo-2025** [comment]
I can also allocate time for testing new versions.
P.S. translate google
