### ISSUE TITLE
Anti-Bash broken?

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1136]
i just tried it out for the first time and it never reflected any bashes. the enemy had greater bash and an abbysal blade, didnt reflect either of those ever.

there was also towers with bash that didnt get reflected

**Comment by darklordabc** [comment]
The enemy didn't get stunned?

**Comment by darklordabc** [comment]
Just to be clear, it doesn't prevent you being stunned

**Comment by DankBudd** [comment]
the enemy never got stunned and the ability never went on cooldown

**Comment by darklordabc** [comment]
I just tested this on Roshan and everytime he stunned me, he got stunned too, hmm, maybe something else is going on, I'll probably need to test against players.

**Comment by darklordabc** [comment]
Uploading a new version soon, let me know if its still broken.

**Comment by DankBudd** [comment]
anti-stun seems to be working fine
