### ISSUE TITLE
BOTS ATTACKING NON EXISTING CREEPS

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1143]
![20170731193329_1](https://user-images.githubusercontent.com/19620604/28789938-8b29a1fa-7627-11e7-9fbf-f5bd5c1bae4f.jpg)
![20170731193328_1](https://user-images.githubusercontent.com/19620604/28789964-9a11eaec-7627-11e7-82d9-9519c147ba7f.jpg)

**Comment by edotenseilove** [comment]
SEE THE CRIT

**Comment by DankBudd** [comment]
already an issue #1085

**Comment by darklordabc** [comment]
Were u guys using multiply creep mutators?

**Comment by darklordabc** [comment]
I tried to reproduce this issue, but I couldnt do it.
