### ISSUE TITLE
 [troll] Mastery of Magic and tempest double

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1145]
basically you can double your mastery charges (mb only a problem with nimbus).
also tempest double still doesnt always disappear, so you can keep one forever in base (it disappears if you summon a new one).

**Comment by LoDfan** [comment]
I've already reported a bug with TD in discord. If you have an OC in your bag TD won't die after its summon time is over.

**Comment by darklordabc** [comment]
@Wouterz90, yeah there is a strange bug with the octarine core on tempest double. When he should die, the octarine core heals him a little bit just before he dies, meaning he lives on permantely, can you check how the octarine core (consumable) gives health? Can you make it not work for things like tempest double deaths. 

This bug seems to apply to haunt illusions too.

**Comment by darklordabc** [comment]
@01der I'm not really sure what your talking about. Are you talking about tempest double can you master of magic to cast spells like nimbus? I made a nerf to master of magic so that it requires 3 charges to cast an ultimate without cooldown, that should help a little.

**Comment by darklordabc** [comment]
I've temporarily made it so that tempest double no longer gets octarine core, this is a temporary fix until we can fix octarine core bug. 
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/37222a45a6e0541eeb8a82dcc79bd48969ad3b33

**Comment by 1ran-wang** [comment]
not only tempest double. all illusions with OC will became invisible and
staying alive.

2017年8月2日 下午7:09，"darklordabc" <notifications@github.com>写道：

**Comment by LoDfan** [comment]
> not only tempest double. all illusions with OC will became invisible and staying alive. 

Yes I also saw this. It's not too strong, but causing lags

**Comment by Wouterz90** [comment]
Is this only the consumed version or both? Not sure if I can detect that kind of damage, but I'll do some tests

**Comment by DankBudd** [comment]
@Wouterz90 couldn't you just check for when **modifier_illusion** expires (might be **modifier_kill**)?
and util_remove the unit if they have an octarine in inventory or consumed

**Comment by LoDfan** [comment]
If octarine was consumed illusions just disappear normally. Bug is only reproduced when octarine is in inventory slot
