### ISSUE TITLE
Please reduce sleep cloud effect duration a bit. 28 sec of sleep is too much

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1148]
Please nerf sleep cloud a bit. 28 sec of sleep is too much. Also there is no animation, so you can't avoid it. It's even enough to move enemy hero to fountain using VS's swap

**Comment by LoDfan** [comment]
Or just add a possibility to wake up by hit of allies

**Comment by DankBudd** [comment]
these are both good suggestions. and there seems to be a lot of custom abilities missing particle effects, im not sure why this is.

**Comment by darklordabc** [comment]
Fixed sleep coud to max 10 seconds, also made some other changes to compenstate. When I tested it, I saw the cloud particle, can anyone else try it? 
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/74942acc464e1bc84c02e23211835adee9f32283

**Comment by 1ran-wang** [comment]
If we reduce the duration we should also reduce the time requirement for
sleep. otherwise this skill will became little bit too weak.

2017年8月2日 下午6:36，"darklordabc" <notifications@github.com>写道：

**Comment by LoDfan** [comment]
Thank you. Time to sleep I think is better to reduce to 2 sec. 
Before nerf I tried a cancer build with any hero having 20+ cd reduction talent + skill 15% cd reduction and OC. My cd was nearly 20 sec (depends on what cd red talent) and duration 26 sec. All enemy team slept on fountain till base destruction. Easy win, but I don't wont to see this build in enemy's hands. After 5 min of sleeping all enemy team left.

**Comment by darklordabc** [comment]
I dont know about 2 seconds, doesnt really give players the chance to escape the cloud.

**Comment by 1ran-wang** [comment]
it means you have to build blink dagger or force stuff to escape. One item
counter one ability is balance for most abilities I guess. And also 10 sec
sleep without damag is not a big deal. We what we really need is prevent
permanent sleep, So I think more reliable + longer CD is a better choice.


2017年8月3日 下午7:40，"darklordabc" <notifications@github.com>写道：

**Comment by LoDfan** [comment]
Need to calculate so WR with 30% cd tal + 25% OC + 15% custom ability won't make cd =< sleep duration

**Comment by darklordabc** [comment]
I'm going to leave it at 3 for now, because there are other changes to make it better, if its still under powered we can revist the ability later.
