### ISSUE TITLE
[Bots] Remove Attack Range increasing abilities from the pool for melee heroes

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1151]
Everything is in the title.
Maybe also remove Reactive Armor for aesthetic reasons.

**Comment by darklordabc** [comment]
Not sure about this.

**Comment by darklordabc** [comment]
Seems like it would be nerfing bots, and I'm always reluctant to do that since they are already stupid.

**Comment by AnimaThunder** [comment]
Agreed, the only thing most melee bots have going for them is randomly generated op builds. Bloodseeker with double essence shift or wk with coup de grace and take aim, for example. If you need help dealing with them ask about it in builds section of discord

**Comment by AugurM** [comment]
Bots need all the help they can get, I just find them aesthetically displeasing. In the case of bots, I think they should be kept in their theme.
Sniper getting more range (both attack and spell). Omniknight getting more survivability...
