### ISSUE TITLE
[Suggestion] Random "Survival of the" option

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1152]
Just like Random Flesh Heap.

**Comment by darklordabc** [comment]
![image](https://user-images.githubusercontent.com/16277198/28948073-b681763a-78f6-11e7-8d29-53aea7fd184e.png)
Added here
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/91de13f58050d90dded911ee1de43915704f3984
