### ISSUE TITLE
IDEA OF ADDING ANCIENT POWERS LIKE IN DOTA IMBA

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1153]
CAN SOMEONE ADD THIS FEATURE I THINK IT WOULD BE INTERESTING

**Comment by darklordabc** [comment]
There are some ancient powers, like the giga ability and the reveive ability, do you mean adding ancient abilities to the ancients themselves? Because I dont like that part of IMBA it just prolongs the game for ages.

**Comment by AnimaThunder** [comment]
Maybe make it another mode modifier if this gets more support

**Comment by edotenseilove** [comment]
YES i MEAN adding ancient abilities to the ancients themselves ABILITIES LIKE BORROW TIME AND RAVAGE WITCH REQUIRES PERCENTAGE HEALTH MISING AND THEN IT WILL TRIGGER IF THERE ARE HEROES AND UNITS WITHIN RANGE AND IF ANCIENT IS ATTACKED. AFTER TRIGGERING IT WILL GO ON COOLDOWN
