### ISSUE TITLE
[troll] decrepify + life break

### ISSUE THREAD

**Issue by ShortVix** [darklordabc/Legends-of-Dota-Redux#1155]
This combo with spell amp will insta kill anything,

**Comment by OtsoTurpeinen** [comment]
Magic resistance is you friend. Linken sphere, bkb, etc. you figure it out.

**Comment by DankBudd** [comment]
yeah i dont think this should be a troll combo, there are lots of ways to deal with it

**Comment by darklordabc** [comment]
I usually just buy a blademail, doesnt that counter this combo pretty easily?

**Comment by russo-2025** [comment]
DankBudd, Darklordabc

Blade Mail - duration of 4.5 seconds
Linken's Sphere - blocks only 1 spell

I played against a similar build (Life Break + Dispersion) with 70% resistance to magic and had Linken's Sphere, Blade Mail, Lotus Orb.
All this did not help.

P.S. translate google

**Comment by OtsoTurpeinen** [comment]
I would bet that there is more than just those in that build. Dispersion, Flesh Heap, Bristleback. Some sort of damage reduction. Few other damage amp spells like Blood Rage,Ancient Seal or Natural Order.
decrepify + life break are not enough to consider troll combo.
In the end you can still do lot with sheepstick, orchid or silver(edge)
