### ISSUE TITLE
Please make -dc voting 100% instead of 50%+1

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1157]
Currently double neutral creep voting is made by rule  50%+1. So it's very easy to vote for this unbalanced mode. Usually players picking farm builds do this and at 10 min they have 6 slots.

**Comment by 1ran-wang** [comment]
Nah, I think 100% means never. 50%+1 is good now, For games I've
played.It's fair enough.because 50%+1 means at least one person in your
team voted yes.

2017年8月7日 上午7:08，"Good Morning" <notifications@github.com>写道：

**Comment by AnimaThunder** [comment]
Why not make it a 70% vote, since the only reason people use it is to dominate people who don't know what's about to happen?

**Comment by darklordabc** [comment]
I'll make it so it requies 70% votes, btw before it only required 50% vote, not 51%

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/a4cec760bbffd1463dbd58a6ea510c817c8cf83d
