### ISSUE TITLE
Chat votes will trigger even if vote is in the middle of text typed

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1158]
sorry for poorly worded title, wasnt quite sure how to say it.
this is mostly a quality of life thing

**How it is**
if your msg is something like `"you can use -eb to enable hero builder"`
it will start the hero builder vote.

**How it should be:** 
the vote should only start if the command is at the start of the msg, even a space should stop it
- doesnt work `"use -eb"`

- doesnt work `" -eb"`

- works `"-eb"`

**Comment by darklordabc** [comment]
I don't know if I'm going to bother with this change, i'll leave this issue open if anybody else feels like working on it, but I dont imagine this is a real issue that comes up often.

**Comment by darklordabc** [comment]
If anyone cares, the problem is with this code 
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/3e65af6c7d206dfea1f6d9a992e147f3a8bf5c16/src/game/scripts/vscripts/commands.lua#L89

**Comment by DankBudd** [comment]
to be clear, its not just with hero builder, its all the votes.
just need to change all the ` string.find()` to `string.sub()`. ill probably do it myself later

using local variables here just to show whats what

    local msg = "-votecommand"
    local msgLength = 12

    if string.sub(msg, 1, msgLength) == "-votecommand" then

        --insert code magic here

    end
