### ISSUE TITLE
SotF: Bash

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1160]
survival of the fittest bash gets over 100% bash chance after 17 min of being alive.

there was an attempt at balance here, with the bash cd. but i dont think thats enough, the bash chance needs a nerf.
but try not to nerf it into the ground

**Comment by OtsoTurpeinen** [comment]
All of the "Sotf"s can be disabled by break. And Hex/Disarm work fine against the bash. I could put the whole thing into sigmoid function but that would be really hard to explain in ability tooltip.

PS: If you have some clever idea for Sotf Bash, I would like to hear it. I would really like the ability still scale after 100 stacks. But adding stun duration seems op.

**Comment by 1ran-wang** [comment]
I did some balance on SOTF already.
