### ISSUE TITLE
infernal blade doesnt cost mana and prevents UAMs from working

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1161]
while toggled on inf blade will stop any unique attack modifiers from working, such as lifesteal (is lifesteal the only UAM left? lmao)

edit: all the datadriven abilities that use the "Orb" block probably stop UAMs as well.

**Comment by darklordabc** [comment]
Any suggestion on how to fix this?

**Comment by DankBudd** [comment]
it just has to be recoded without using the datadriven "Orb" block.
