### ISSUE TITLE
Stop Survival Bash from procing on buildings

### ISSUE THREAD

**Issue by Wolsken** [darklordabc/Legends-of-Dota-Redux#1165]
He had 124% bash chance...He attacked the tower...He bashed the tower...      S U R V I V A L  O F  T H E  B A S H L O R D

**Comment by 1ran-wang** [comment]
But it only has 0.75 duration with 1.5 sec cooldown. Roshan's bash can bash towers as well.

**Comment by darklordabc** [comment]
This is a problem we will fix
