### ISSUE TITLE
[Suggestion] oposite tenacity 

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1167]
is it possible to make an ability which increase duration of spells that we cast by pecentage for example if we cast Shadow Word on our ally he will be healed more because it will have longer duration and if we cast it on enemy he will suffer more damage because of longer duration

**Comment by DankBudd** [comment]
would probably be overpowered with buffs/debuffs that have long durations already.

imagine RP with 30% increased duration, nearly 5 seconds of bkb piercing aoe stun.

**Comment by 1ran-wang** [comment]
Actually, think about Absolutely zero and Doom.

**Comment by LoDfan** [comment]
I think it may be used only for positive buffs, not for debuffs.

**Comment by OtsoTurpeinen** [comment]
Borrowed time and Notlh protection.

**Comment by LoDfan** [comment]
If it will be increased only by 30% it's not a big issue.

**Comment by 1ran-wang** [comment]
here is an idea:
For original duration lower than 10 sec :increase all buff duration by
10%/20%/30%/40%

For original duration longer than 10 sec :increase duration by 1/2/3/4 sec.

2017年8月10日 下午12:30，"OtsoTurpeinen" <notifications@github.com>写道：

**Comment by 01der** [comment]
Definitely a skill that would have much use, i like the balancing idea, 40% might still be a bit much but it could be nerfed if issues arise. Maybe a scepter upgrade would give it +10%/1sec on each lvl and the base-durations would be:
10%/15%/20%/25%

**Comment by DankBudd** [comment]
@darklordabc I'll implement this if you think it can be balanced.
