### ISSUE TITLE
Octarine Core + Illusion = endless duration illusion with no model

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1173]
this was mentioned in a different issue, but it deserves its own issue #1145

this can easily be reproduced with manta + octarine core and its suspect to be causing lag.

when the illusion('s) die they will still be where they died but with no model, and will attack any passing enemy creeps or heroes.
i am unsure if they must be killed by modifier_illusion or if simply taking damage and dieing will cause this

**Comment by darklordabc** [comment]
Made a hotfix for this for now, swaps the consumed octarine with the original for illusions and tempest doubles
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/545322808a7540fa2a186afaf634fb62fa8d40da
