### ISSUE TITLE
Sometimes talent replacement system gives heroes random useless talents

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1174]
sometimes the talents you get are for skills you dont have.
ive seen people get things like "Geomagnetic grip can target allies", "AoE Deafening Blast", etc.

**Comment by LoDfan** [comment]
AoE Deafening Blast seems to appear only for invoker because he doesn't have this ability by default slot, but considered he can use it by manipulating spheres.
Geomagnetic grip also appears only for earth spirit.

**Comment by DankBudd** [comment]
not true, ive gotten "aoe deafening blast" as various heroes such as vengeful spirit or enchantress

edit: enigma with geomagnetic grip talent
![20170812024205_1](https://user-images.githubusercontent.com/18477016/29244997-bd7baf3e-7f98-11e7-9e3b-4f1bf34afd85.jpg)
