### ISSUE TITLE
[troll] Stunlock builds

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1177]
Another pet peeve of mine:
stunlock builds get also picked a lot because they allow you to ignore whatever skills (apart from craken, anti-stun and unwavering stance) the opponent has and just stun them till they are dead.
Mostly its an issue of meele heros (especially AM and Jugg) taking a bash skill and buying a basher.
Similar result can be achieved with chemrage and berserkers rage.

While not neccessarily a stunlock, bash on ranged gets also picked lot (greater bash with arcane art).
I think the bashes should be treated similarly to essenceshift and furyswipes.

Seeing how aftershock got a redux treatment, i think the same might be needed here (at very least in the non op option). Maybe a cd on all bashes would solve the issue.

Casters can also stunlock, they usually just need more mana and lvls so it becomes a lategame issue (cant do anything without bkb). Maybe a limit of 3 stuns per hero would be acceptable?

To underline that this is not only my issue, i have noticed a lot of people dc after they get stunlocked.
It has turned some lobbies into bash-fests with only bash-builds left in the game and the one who stuns first wins the fight.

**Comment by darklordabc** [comment]
Maybe instead of dealing with bashes on the attacker side we deal with it from the victim side. Like make a global rule where if a player gets bashed stunned or rooted, for 2 seconds after the stun, they are immune to bashes. What is your opinion of that fix?

**Comment by 1ran-wang** [comment]
I prefer give all bashes 150% cooldown of durations.

2017年8月12日 下午1:49，"darklordabc" <notifications@github.com>写道：

**Comment by darklordabc** [comment]
The problem is that normal Dota 2 passives will still work even if on cooldown, and I'm not going to recreate all the bash abilities, so it's not a feasible solution.

**Comment by 01der** [comment]
I like the immunity to bashes idea, doesn't even need to work for roots, its only stuns, that disable you from any kind of retaliation.

If there is a lot of voices against it, maybe we could have it as an option like anti-rat.

PS.: is there anywhere we can see how the original abilities are coded, so we would only need to edit them, not recreate them?

**Comment by darklordabc** [comment]
We can't see the code for the original abilities, only a few of their variables are exposed, but the code is not available. There is this very helpful user run library that tries to replicate the abilities in LUA https://github.com/Pizzalol/SpellLibrary

**Comment by 1ran-wang** [comment]
Should it prevent any stun effect for 2 sec? I'm not sure about this, because it means you cannot kill any heroes with blink and Eul's Scepter,I think it should only work with passive bashes.

**Comment by darklordabc** [comment]
Yes I was thinking only for bashes.

**Comment by 1ran-wang** [comment]
Is that a nerf on MKB? LEL

**Comment by DankBudd** [comment]
> I prefer give all bashes 150% cooldown of durations.

this could be done in a modifier filter right?

just put some variable on the hero who applied the bash 
`local multiplier = 1.5`
`caster.bashCooldown = GameRules:GetGameTime() + modifier:GetDuration()*multiplier`

and then check if enough time has passed to bash again the next time they bash

    if caster.bashCooldown then
        if GameRules:GetGameTime() <= caster.bashCooldown then
            --allow bash
           return true
        else
            --remove bash
            return false
        end
    end
    return false

**Comment by darklordabc** [comment]
@DankBudd, there is no modifier we can place on a hero that will disable his bash from working, as long as he has the bash passive ability he will continue to bash people, its not easily disableable.

**Comment by DankBudd** [comment]
@darklordabc  
you can just return false in a modifier filter to reject a modifier from being applied right?

i meant whenever a hero has a bash applied to them, put the cooldown variable on the hero who applied the bash.
if the hero who applied the bash bashes another hero check the variable and current game time to see if enough time has passed to bash again. 
im pretty sure this would work. ill test it out later today

Edit: It works, the stun doesnt happen.
but i think they will receive the damage from the bash, and the bash sound is still played

in this code i use StartCooldown and IsCooldownReady, but i think it would be better to do it internally with the variable i mentioned before.

    function GameMode:BashManager( filterTable )
      local parentIndex = filterTable["entindex_parent_const"]
      local casterIndex = filterTable["entindex_caster_const"]
      local abilityIndex = filterTable["entindex_ability_const"]

      if not parentIndex or not casterIndex or not abilityIndex then
        return true
      end

      local parent = EntIndexToHScript( parentIndex )
      local caster = EntIndexToHScript( casterIndex )
      local ability = EntIndexToHScript( abilityIndex )
      local modifierName = filterTable["name_const"]

      local modifier = parent:FindModifierByNameAndCaster(modifierName, caster)
      local duration = filterTable["duration"]

      local exceptions = {
        item_abyssal_blade = true, --is a bash, but has an active
      }

      if modifier:IsStunDebuff() and ability:IsPassive() or exceptions[ability:GetName()] then
        if ability:IsCooldownReady() then
          local multiplier = 1.5
          print("allow bash", "CD: "..tostring(duration * multiplier))
          ability:StartCooldown(duration * multiplier)
          return true
        else
          print("reject bash")
          return false
        end
      else
        print("NOT A BASH", modifier:GetName(), ability:GetName())
      end

      --return true by default
      return true
    end

**Comment by DankBudd** [comment]
working on stopping the sound and dmg as well. am i missing any bashes?

    --used to stop bash sounds from playing
    local sounds = {
    --items
      item_abyssal_blade = "DOTA_Item.SkullBasher",
      item_basher = "DOTA_Item.SkullBasher",
      item_monkey_king_bar = "DOTA_Item.MKB.Minibash",

    --dota
      slardar_bash = "Hero_Slardar.Bash",
      faceless_void_time_lock = "Hero_FacelessVoid.TimeLockImpact",
      spirit_breaker_greater_bash = (parent:IsHero() and "Hero_Spirit_Breaker.GreaterBash") or "Hero_Spirit_Breaker.GreaterBash.Creep",
      troll_warlord_berserkers_rage = "Hero_TrollWarlord.BerserkersRage.Stun",
      troll_warlord_berserkers_rage_active = "Hero_TrollWarlord.BerserkersRage.Stun",
      roshan_bash = "Roshan.Bash",

    --custom
      imba_tower_permabash = "Hero_FacelessVoid.TimeLockImpact",
      imba_tower_spacecow = (parent:IsHero() and "Hero_Spirit_Breaker.GreaterBash") or "Hero_Spirit_Breaker.GreaterBash.Creep",

      spell_lab_survivor_bash = "DOTA_Item.SkullBasher",

      android_pocket_factory_spawn_goblin1 = "Roshan.Bash",
      android_pocket_factory_spawn_goblin2 = "Roshan.Bash",
      android_pocket_factory_spawn_goblin3 = "Roshan.Bash",

      item_monkey_king_bar_consumable = "", --this doesnt have a sound? is it built into modifier_stunned??
    }

**Comment by 1ran-wang** [comment]
SOTF bash… and also I think mkb shouldn't in the list

2017年8月13日 下午11:06，"DankBudd" <notifications@github.com>写道：

**Comment by igor-netFantom** [comment]
Just now windranner do stunlock with nimbus. I dont see all her skills, but he has:
survival .... (cd reduction) 
north protection imba
blink
nimbus
lighting bolt

we cant catch her because of north protection+blink and after ~30 min she casts Nimbus on our heads and its perma-stun us. I have rage so i can cast it and can be immune to magic, but i cant use it because i already stunned. ... and its global skill - i cant take distance and be safe.

**Comment by DankBudd** [comment]
> SOTF bash… and also I think mkb shouldn't in the list

spell_lab_survivor_bash is SOTF bash.

ill probably make all the item bashes ignored, primarily because its difficult to differentiate abyssal blade bash and abyssal blade active because they use the same modifier.

> Just now windranner do stunlock with nimbus.
...

that wouldnt be permastun unless they had a LOT of survival stacks.

**Comment by igor-netFantom** [comment]
> that wouldnt be permastun unless they had a LOT of survival stacks.

but she has a lot of survival stacks because of blink+nort protection. Her teammates push us and she was under her tower near our creeps. I try to catch her, but i was catched by her team mates, or she just blinks out. After ~ 30 minutes without deaths she perma-stun us with nimbus

**Comment by LoDfan** [comment]
Agree with these changes. Also don't forget to make impossible to permabash towers with roshan's bash

**Comment by igor-netFantom** [comment]
One more stunlock build
https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1249
