### ISSUE TITLE
[bug] AA perk

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1178]
AAs perk is one of the most useful perks in the game, but highly bugged.
1st, only a few of the available ice-themed skills actually work with the perk.
2nd, the debuff doesn't refresh correctly: first frost arrow applies frost arrow debuff and AA debuff, second frost arrow refreshes frost arrow debuff but not AA debuff.
3rd, if you walk out of cold feet casted by AA, the AA debuff doesn't get removed -> you cant heal till you die or AA applies the debuff again.

Please fix the perk, it makes AA very useful, but also very broken right now.

**Comment by 1ran-wang** [comment]
Yes I tried Cold feet and force stuff, is easily to forever prevent enemy's healing till they die.

**Comment by DankBudd** [comment]
1. if you can list some ice-themed skills that should work for the perk but don't, we can update them
2. i will attempt to fix this, not sure if i can
3. potential fix  b37c3bb

**Comment by darklordabc** [comment]
The permanent duration should be fixed here https://github.com/darklordabc/Legends-of-Dota-Redux/pull/1192 but the other issues probably still remain

**Comment by 01der** [comment]
@darklordabc can confirm other issue still exists!

**Comment by DankBudd** [comment]
fixed the other issue #1210

**Comment by 01der** [comment]
@DankBudd  thank you so much for fixing it so far.
Curse of Avernus applies the no-healing debuff also to AA.
Also i would be willing to add the ice tag to a couple of other ice spells if that would be wanted.

**Comment by DankBudd** [comment]
> Curse of Avernus applies the no-healing debuff also to AA

interesting.. i guess i should add a check for if the applied 'ice' modifier is a debuff.
edit: should be fixed 9beb5be

edit: you can add the ice tag to spells like this, or just list the ones that aren't currently ice and i will add the tags.
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/npc/abilities/dota/invoker_ghost_walk_lod.txt#L40

**Comment by LoDfan** [comment]
2. The skills not working with AA perk: ice breathe (custom), ice vortex, ice armor debuff works only for the first debuff duration (same as with frost arrows), frost attack (neutral) etc.
But if Ice armor debuff will be permanent on attacker it will make some return builds(centaur) on AA very powerful.
It's hard to make this perk balanced. It may be too OP or too week. But there are a lot of other totally useless perks.

**Comment by DankBudd** [comment]
@LoDfan can you double check that ice debuffs don't reapply AA perk when refreshed?
i thought i fixed that about a week ago.

and you're saying sometimes AA perk debuff is still permanent?

**Comment by LoDfan** [comment]
Thank you for fixes, I didn't play AA often so I missed the update with perk fix.
There are still some ice abilities not working with AA:
Ice vortex, Arctic Burn, Frost Attack (from neutral) - but I'm not sure it's good idea to make last 2 skills to apply AA debuff.
Positive ice buffs prevent self healing (frost armor), and didn't check cold embrase  (may be same)

![shot_0001](https://user-images.githubusercontent.com/24685202/29784361-5dd87a08-8c2c-11e7-9b4e-f768aec108b2.jpg)

**Comment by DankBudd** [comment]
tried cold embrace and frost armor/ice armor, was unable to replicate the perk debuff being applied to allies.

arctic burn and frost attack should work with the perk next update

working on fixing ice vortex. currently, if you cast a second ice vortex on them they will get the debuff
