### ISSUE TITLE
[bug] various bugs

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1179]
- [x] Return Astral Spirit can be spammed with essence aura to get free mana.

- [x] Echo spell, will recast any spell which is cast during the spell delay time. (maybe we could get a scepter upgrade with 2 charges echo-spell instead).

- [x] Survival of the fittest (mana/hp regen version) lifts the movement speed cap completely. (1500 is my record) **[[Needs confirmation]]**
- [x] Mischief can remove any model if you cast it near a tree with a hero other than MK. **[[Disabled until it can be fixed]]**

- [ ] Instant-picking IO will allow you to play IO without any model or Health-bar -> not target-able.
IOs can be killed before finishing picking by using global teleports (unstable rift and natures prophet's).

**Comment by darklordabc** [comment]
"Survival of the fittest (mana/hp regen version) lifts the movement speed cap completely. (1500 is my record)" 
Can you double check this, it didn't override the movement cap for me, are u sure you didn't have thirst that was removing the cap? 
![image](https://user-images.githubusercontent.com/16277198/29240588-90636c7c-7fab-11e7-81ac-257ca8cbba1f.png)

**Comment by 01der** [comment]
its the original survival of the fittest:
![20170806020910_1](https://user-images.githubusercontent.com/29154151/29241734-80dc93ea-7f7f-11e7-8315-0960afd44431.jpg)

**Comment by OtsoTurpeinen** [comment]
Original survival of the fittest is not used anymore.
Edit: I forget the name of that ability buts the one on third slot that causes the move speed thing.

**Comment by 01der** [comment]
I am sorry didn't even notice that it was gone. I am so seldom on github i tried to remember all the bugs i encountered. Guess that is not an issue then anymore 👍 .

**Comment by 1ran-wang** [comment]
It's plain runner that let you remove the cap.

**Comment by 1ran-wang** [comment]
'Return Astral Spirit can be spammed with essence aura to get free mana.' Fixed in 1 month ago, by setting them as a troll combo.

**Comment by 01der** [comment]
I just tried the Astral spirit with essence_aura_redux and that gives unlimited mana.
plains runner does not remove the cap, it used to be the origianl survival of the fittest.

**Comment by darklordabc** [comment]
I've changed so return doesn't process essence aura it will be in next version.

**Comment by LoDfan** [comment]
> I've changed so return doesn't process essence aura it will be in next version.

What about timber's Return Chakram?
