### ISSUE TITLE
Team Balance

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1180]
One of the biggest issues right now in lod in my opinion is that teams are rarely balanced.
Sometimes you have lots of old regulars on radiant against mostly fresh meat on dire, or the other way around.
In both cases it becomes inevitable that the game will be one-sided (experience in LOD means almost certain victory).
My suggestion:
Use the stat-collection that we have:
https://getdotastats.com/#s2__mod_lb?id=3
(maybe take win-rate of the last 2 months)
And distribute the old regulars amongst dire and radiant.

Of course that doesn't guarantee a balanced game, but in my experience when the old regulars are stacked it actually guarantees a steamroll.

As a first step we could allow switching teams even when there is only a 1 player difference.

**Comment by DankBudd** [comment]
> And distribute the old regulars amongst dire and radiant.

i like the idea but it wouldnt be great for people who play in partys, they would probably get put in different teams.
im not sure if we actually have a way to check if players are in a party

 .

> allow switching teams even when there is only a 1 player difference.

yeah i agree with this. just dont let people swap with disconnected heroes if there is no player difference

**Comment by darklordabc** [comment]
This is a fantastic idea, and I'd love to develop it but to be blunt, I don't think we have the resources to do it. I know a lot of programmers that would be happy to implement this but they require payment, and right now my funds are being directed towards a second project, and unfortunately Redux has no income stream, there is no Patreon and no donations. If somebody is willing to donate money towards this objective, I could make it happen, I imagine 40$ would be enough to pay the programmers. But without funding, I don't think this particular feature request will happen as it requires skills outside of my set.

**Comment by 01der** [comment]
I hope i might be able to either code it someday myself, or at least support it with cash, but for now all i can contribute are (good) ideas. 
I think the KISS way to implement this would be to hardcode it. 
If it is possible to get this information from the getdotastats.com database: "amount of wins in lod for the last 3 months" and use that for deciding which team each player goes:
player A has had 50 wins, B 30, C 20, and the other 7 are new players
then A and 4 new players would go on radiant and B and C and 3 new players would go on dire.

Seeing how LOD gets updated many times per month i think hard coding the listing and updating it maybe once per month wouldn't be a problem.
In any case it would be much better than what we have now. (often A B and C are on the same team).

**Comment by 1ran-wang** [comment]
Yes this is a good idea, I think it would be a good idea to build a donation system in LOD. 

Put some enhancement and price that we don't have enough funds on the introduction page of LOD . And people can donate cash with specific enhancement they want. 

    Ranking system: 40 $
    Update perk system 40 $

sth like that.


And for the team balance system, I think the balance way could be better than just seperate party players

Example: 

Assume we have follow players in one game. dash means they are in party.


Before balance:

        189                        90
    50-40 50 40 5 4      10 30 20-10-10

After balance:

         109                       120
    50-40 5 4 10       50 40 20-10-10

But if we have ：

     103                  5
    50-50 1 1 1     1 1 1 1 1

then, party players have to play in different team. 

Not everyone gonna accept that,  for me (I want to play with my friend) > (I want to play a fair game)
If we notice that we have to play in different team, we probably will use new accounts to cheat this system.

I totally agree with @01der but I think this is also a problem.
