### ISSUE TITLE
[Balance] Weaver/Gyrocopter Perk

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1181]
These 2 heroes get banned or picked almost every game, because their perks are too good.

- [ ] Weavers perk seems to scale with lvls, scepter and CDR which gives you a <16 sec self-triggering timelapse which is way too strong. Now i want weaver to stay a viable pick (hist stats are awful and his talents not great), so maybe just capping the perk-ult at 40sec cd would be a good idea. Alternatively give weaver a free germinate attack ability (not just a point).

- [x] Gyrocopter perk stacks with sidegunner skill and allows for insane 5 attacks per sec or more with arcane art. Additionally he has great stats and talents so he makes the perfect rightclick base for many builds. Best solution in my opinion would be to just give gyrocopter a free sidegunner ability.

**Comment by darklordabc** [comment]
I've removed the scepter upgrade for gyro, and made his perk juts 1 free level in side gunner.

**Comment by 1ran-wang** [comment]
Weavers perk doesn't work with cdr, because it's cd is related to a buff.

**Comment by 01der** [comment]
> Weavers perk doesn't work with cdr, because it's cd is related to a buff.

even at 16 sec cd, the self triggering ult is considered too OP by many (who either ban it or complain if you pick him).

Also don't give Weaver geminate attack, it will be picked with totem or walrus-punch then.

**Comment by igor-netFantom** [comment]
> I've removed the scepter upgrade for gyro, and made his perk juts 1 free level in side gunner.

I think its now too weak just as 1 lvl. Maybe allow gyro to spend his points to lvlup this ability like PhantomLancer can lvlup his Phantom Rush?

**Comment by DankBudd** [comment]
so apparently weaver perk uses its own cd separate from the Time Lapse skill.
so if you pick weaver and take time lapse, you have an auto time lapse, and a manual time lapse with separate cooldowns.

havent looked into this yet, but someone reported this to me.

edit: checks out, the perk is coded to have a separate cooldown. 
i think it would be fine if it shared cooldown with regular timelapse. should be enough of a nerf to make it balanced.
