### ISSUE TITLE
[suggestion] reverse Marksman = Brawler

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1184]
Like Marksman (+str/int), but you only get the benefit if there IS a hero within 400 range.
And because that means you wont have the benefit for farming, maybe give it a cleave scepter upgrade or something.

**Comment by DankBudd** [comment]
there is already ferocity agi, int ,str, all(ult) versions which pretty much does this already. 
difference being that ferocity gives stats for each nearby creep/hero

**Comment by 01der** [comment]
I haven't checked ferocity since the buff, but last i tried it, it was rather difficult do get a reliable increase of 80 stats. Also there is many reasons why you wouldn't want many units next to you (cleave and spells that profit from many units)

**Comment by 1ran-wang** [comment]
May I change the  ferocity so that It will only work on heroes but increase the stats gain?

**Comment by 01der** [comment]
seeing how marksman at lvl 3 give 80 stats, i think it would have to be around 20 stats per hero at lvl 3 to be as effective. If you do change it to that you definitely need to make them ults.

**Comment by DankBudd** [comment]
i personally think that ferocity is fine how it is.
one of my favorite builds is to use Undying with ferocity and summon skills.

**Comment by 01der** [comment]
I definitely don't want people to miss their ferocity, but i still think a reverse marksman would be very useful.
