### ISSUE TITLE
Mischief makes players lose model when used near trees

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1185]
Its meant to make you become a tree model, and it does with monkey king, but for all other heros it bugs out and creates a model-less tree. It has been disabled until it can be fixed. 
![image](https://user-images.githubusercontent.com/16277198/29240365-1f222ce6-7fa7-11e7-96d1-4bf50c4dd20a.png)

**Comment by 1ran-wang** [comment]
I think It's related to the model bugs.

**Comment by DankBudd** [comment]
could make a custom mischief maybe? 

edit: did a little testing and apparently this is the model he uses for trees. could it be a precaching issue?
`models/heroes/monkey_king/transform_invisiblebox.vmdl`
