### ISSUE TITLE
Need to update formating in consumeable item texts

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1186]
Valve has updated their formatting of texts with the snazzy headings, but all of the texts of consumable items are still in the outdated format. They need to be updated so they look like this:
![image](https://user-images.githubusercontent.com/16277198/29242861-c972081c-7fd7-11e7-9421-b82d1bd53b9a.png)
If anybody is interesting in helping convert the other texts that would be great, also its a task that any non-programmer could do. This is an example of what needs to be updated:
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/40cf27f2bb68f172fa31a78629b3b48eca472229

**Comment by 1ran-wang** [comment]
#1187 Fixed.
