### ISSUE TITLE
[suggestion] vote to UNIVERSAL SHOP mutator

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1188]
Maybe it will be better to add Voting to UNIVERSAL ~~GLOBAL~~ SHOP mutator at start on all_allowed map? I so like this option, but it disabled on all_allowed and can't be voted.

**Comment by 01der** [comment]
you would definitely have my vote, there is even a tip on the loading screen claiming it would be on, but it isn't.

**Comment by 1ran-wang** [comment]
I think Black market gonna declare bankruptcy。

**Comment by 01der** [comment]
wait, did he mean global shop? like shop anywhere in the map? i only meant universal shop as in secret and  normal shop combined also in sideshop.

**Comment by igor-netFantom** [comment]
I meant universal shop as in secret and normal shop combined also in sideshop. Its option already exists as mutator, but it disabled by default at all_aloowed map and I suggest to allow it by default OF add voting on start.

**Comment by 1ran-wang** [comment]
Yeah but it will also remove one of the most important part of Dota, which
allow you hunt people/courier at secret shop,or guess which items they
gonna purchase. also, It will definitely nerf mid lane Cuz there is no mid
shop.

2017年8月13日 下午12:57，"igor-netFantom" <notifications@github.com>写道：

**Comment by igor-netFantom** [comment]
>Yeah but it will also remove one of the most important part of Dota 

because of that i suggest to add VOTING so people can choose what they want

**Comment by 1ran-wang** [comment]
Well think about current voting system, most of people just vote Yes
without any hesitation.

2017年8月13日 下午1:29，"igor-netFantom" <notifications@github.com>写道：

**Comment by igor-netFantom** [comment]
I see close to 50/50 votings and different variants every game. Also i meant starting voting before choosing heroes, NOT in-game voting.

**Comment by igor-netFantom** [comment]
Also if you afraid that everybody vote YES without reading, then you can change question from:
Enable UNIVERSAL SHOP? NO/YES
to
Disable UNIVERSAL SHOP? NO/YES
:-)

**Comment by 1ran-wang** [comment]
Yeah why we dont change it into：

Do not disable the non-universal shop?

No/Yes

XD


Also if you afraid that everybody vote YES without reading, then you can
change question from:
Enable UNIVERSAL SHOP? NO/YES
to
Disable UNIVERSAL SHOP? NO/YES
:-)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1188#issuecomment-322056891>,
or mute the thread

**Comment by igor-netFantom** [comment]
Also if you swap team from winning to loosing side, you:
- can't use courier because of 'swap bug'
- you can't leave base to shop because enemy destroy your base
- so you can't spend a lot of money to buy expensive items

UNIVERSAL SHOP solve this problem.
Please add voting for UNIVERSAL SHOP on voting panel for all_allowed map before banning phase.

**Comment by darklordabc** [comment]
You can now vote to enable universal shops with -us or -universalshops or from the vote menu. Requires 50% to succeed
