### ISSUE TITLE
[Suggestion] Another no invis system.

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1190]
Instead of ban all invisible item and abilities, could we make heroes permanently has dust modifier?

So that we could still use invisible abilities, like web or Clinkz's invis for movement speed.

**Comment by darklordabc** [comment]
I'm worried that this might confuse players. E.g. players pick cloak and dagger but then realize after picking that it's useless.

**Comment by 1ran-wang** [comment]
What if we change the description from "no invis" into "Global true sight"?

Hm... But it different with the real [True sight] So... IDK

**Comment by darklordabc** [comment]
The name isn't the problem.

The problem is that most players won't know about the true sight buff and will pick simply pick invisibility abilities because they are available, and then will be angry when the game starts and realise they are 90% useless.

**Comment by 1ran-wang** [comment]
maybe place a notice in hero builder when you picking a invisible ability
and No invisible is ON,Just like the light bulb of balance Build UI.

2017年8月13日 上午4:44，"darklordabc" <notifications@github.com>写道：

**Comment by darklordabc** [comment]
People won't pay attention, they will simply see permanent invisibility, and a big percentage of people are just going to pick it because they see it.

**Comment by LoDfan** [comment]
The main problem of noinvis is analog of silver edge. Silver helps a bit, but it's not so useful for long range rightclickers builds and it may be blocked by some passives and linken.
May be it's better to make very common item with silver edge noinvis buff for 1st attack (truestrike, damage bonus, phase movement, increased movement speed). Make this item available only for noinvis mode to avoid buying several items for break.

**Comment by darklordabc** [comment]
I hear you guy, but I dont think I'm going to do this feature.
