### ISSUE TITLE
Make Spell Echo have some penalty for recasting ultimates

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1197]
Maybe extra cooldown or extra manacost, or something else.

**Comment by igor-netFantom** [comment]
I think that it can be like "second cast will consume extra manacost equal to re-casted skill cooldown".
So if Ultimate (or even ordinary skill) has cooldown like 120 sec, then it consume extra 120 mp, and if Ulimate has 30 sec cooldown, then it consume extra 30 mp. Seems fair enough.

**Comment by DankBudd** [comment]
the extra manacost being based on the abilities cooldown would be irrelevant mid to late game.
it wouldnt solve anything.

**Comment by igor-netFantom** [comment]
It also can be extra cooldown based on ability cooldown. 
For example "double casted ability has extra 20% cooldown"
If ablility has 100 sec cooldown, then after echo it will be 120 sec.
If ability has 10 sec cooldown, then after echo it will be 11 sec.

I just suggest to do penalty scalable based on SKILL POWER (similar to SKILL COOLDOWN).

Ultimates much powerful then regular abilities, also they have more cooldown, so you get bigger penalty for double-casting them.

**Comment by OtsoTurpeinen** [comment]
Thats not bad idea but I would say make it +50%
