### ISSUE TITLE
Make Nimbus with CDR or Multicast like abilities a Troll Combo

### ISSUE THREAD

**Issue by ReactorXIV** [darklordabc/Legends-of-Dota-Redux#1200]
Nimbus scales very well with CDR because it benefits twice from it. Nimbus itself has a shorter cooldown and the Lighting Strikes from Nimbus have shorter intervals. Sometimes it gets to the point that you get permastuned either via really high CDR or abilities that allow u to cast nimbus multiple times like Multicast Redux and Master of Magic (this one is especially abusable. I suggest to make such abilities a troll combo with Nimbus (abilities that manipulate cooldowns but don't give cdr directly are fine I think).

**Comment by igor-netFantom** [comment]
Totally agree. It should be troll combo. 
I already mentioned it here: https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1177

**Comment by 01der** [comment]
I agree too, i mentioned it too when i talked about the tempest double bug,
tempest double, master of magic, nimbus is definitely troll in my opinion.

**Comment by LoDfan** [comment]
Totally agree too. Also CDR for survival of the fittest gives too much CDR in my opinion.
