### ISSUE TITLE
Abaddon ultimate passive trigger + CDR 

### ISSUE THREAD

**Issue by ReactorXIV** [darklordabc/Legends-of-Dota-Redux#1202]
Some sources of CDR don't affect Abaddon's ultimate when trigger by itself (I think it works like it should if you activate it yourself but didn't test).

**Comment by 01der** [comment]
I have tested this with the survival CDR, if you trigger it, it works as expected, when it gets triggered by itself it has normal CD.

**Comment by DankBudd** [comment]
I haven't tested this myself, but Baumi recently made a video where he used SotF: CDR and abaddon ult and he didn't seem to have this issue. However he could have just been doing it manually..

**Comment by darklordabc** [comment]
Borrowed time was being activated passively by using an outdated function, its been updated so that it accounts for cooldown reductions. 
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/355e5b605cbd559e6204c7d6ea90f3b2391d7756
