### ISSUE TITLE
Consumed assault cuirass lost after death

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1204]
Ass the title. Confirmed. Consumed assault cuirass modifier will remove after death.

**Comment by darklordabc** [comment]
Uploading hotfix, close this if its works.

**Comment by DankBudd** [comment]
seems to be fixed

**Comment by 01der** [comment]
Seems to be broken again.

**Comment by DankBudd** [comment]
#1218

**Comment by darklordabc** [comment]
Fixed
