### ISSUE TITLE
Enhance for Last Will

### ISSUE THREAD

**Issue by OblivionVortex** [darklordabc/Legends-of-Dota-Redux#1206]
Thinking of Last Will share the skill amplify so we can play the build as a reviveable Skeleton King who can do  
 pure damage to the one kill him；） Plz~

**Comment by darklordabc** [comment]
Not sure what this is, can you expand a bit please? Otherwise plz close this issue

**Comment by OblivionVortex** [comment]
Well... You guys actually did that, Last Will has already enjoy the spell amplify skills, while being killed under high stacks of spell amlify,the one who did the last hit won't get rid of what he did. Thx alot, you guys all alsome.
