### ISSUE TITLE
Nothl Protection + CDR

### ISSUE THREAD

**Issue by ReactorXIV** [darklordabc/Legends-of-Dota-Redux#1209]
Some sources of CDR don't work correctly with Nothl Protection (tooltip and actual cd don't match). This issue is similar with #1202 and probably have the same cause. I had reported a similar issue in the past #1065 and it was resolved successfully (or so I thought). Anyway, in both cases (noth and abba ulti) I had Windrunner or Sniper (with the CDR perk), Octarine Core and Survival of the Fittest CDR. The problem probably lies with  Survival of the Fittest CDR and I suggest to make it function like the other CDR abilities that are allready in the game (not Flesh Heap CDR though because it's buged and doesn't work with octarine).

**Comment by lewishack** [comment]
I tested with Nothl Protection and Flesh Heap CDR and at 500% CDR I was 100% invulnerable. Just to rule out a problem with the CDR mechanics in general.

**Comment by DankBudd** [comment]
This is not a bug, it is intended by Volvo. CDR stacks multiplicatively like most things in dota. Meaning  it's not actually possible to get 100% cd reduction through multiple sources

CDR formula
`(Cooldown × (1 - reduction) × (1 - next source of reduction)) - source of flat reduction + source of flat increase = reduced cooldown`

Similar to the way evasion works

> Because of the way it is calculated, the maximum evasion possible through chance stacking is 95%. 100% evasion is only attainable when it is specifically provided by an ability such as Magnetic Field or Windrun.

**Comment by DankBudd** [comment]
May have misread the issue.. potential fix: #1215

**Comment by ReactorXIV** [comment]
You can't have 500% cdr with Flesh Heap CDR because each stack stacks multiplicatively with each other stack (that's how it is coded right now) and was probably close to 99.34% cdr.
Also I don't know how and if valve has implemented cooldown stacking but I know that there are (or at least were in previous versions of lod) abilities that have hardcoded the cdr to stack additively with some other sources and ignore others.

**Comment by DankBudd** [comment]
We literally have `MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING`
But the only CDR ability that is currently using it is survival of the fittest.
Every other one is using `MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE`

**Comment by darklordabc** [comment]
Please report back if this problem still exists after I upload the new version which incorporates Dankbudds changes to Soft Cooldown reduction
