### ISSUE TITLE
Make wisps invulnerable until they finish picking skills

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1214]
#1179 Currently you can kill the io's in fountain before they pick skills, or if they disconnect you can farm them with globals like zues ult throughout the game.

**Comment by darklordabc** [comment]
How common is this issue?

**Comment by DankBudd** [comment]
with globals that dont require vision like haunt or zeus ult it almost always happens.

less commonly because they are troll combos, global tp's + dispersion + shallow grave type skills

**Comment by DankBudd** [comment]
so the wisps are actually able to move around, cast spells and even attack during skill picking.
meaning you could walk yourself into the enemy tower and feed.
