### ISSUE TITLE
SotF: Cooldown a spell amp OP

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1219]
Could you do SotF Cooldown a spell amp OP without range penality?

**Comment by Fapboard** [comment]
No.

It can't ever be enabled without a range penalty in place, since those 2 skills offers unlimited power without ever risking yourself to die.

Doesn't apply as brutally on the others but the concept remains the same.

Imo the skills should just be removed from map.

**Comment by edotenseilove** [comment]
I am not talking about enabling it without a range penalty i am talking about creating a new OP OP version of these abilities without it

**Comment by igor-netFantom** [comment]
should be for single player mode only

**Comment by edotenseilove** [comment]
YES

**Comment by darklordabc** [comment]
Added single player versions of both abilities here:
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/cf71e52c752929671e90f9a2cba3bc959e3232af
