### ISSUE TITLE
[suggestion] allow to Vote team switch when enemy has one player less

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1220]
allow to Vote team switch when enemy has one player less (not two players as now) because offten enemy team start to leave then they weaker, so if they weaker 4 vs 4, then they more weaker as 3 vs 4 and dont have a chance until one more leave and someone from winning team switch side. 

Also please make team switch Voting cooldown smaler (and individual as it possible) because sometimes after team switching some enemies still leaves and more players should to switch but cant because of Vote cooldown.

**Comment by darklordabc** [comment]
I'll meet you halfway. I understand the first issue, but I also can see it being abused, so I'm not going to change that, but as for your second request I can help there. The current vote cooldown is 300 seconds (5 mins), I'll half it to 150 seconds (2.5 mins).

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/c0ba4c1208bc3a559c847be065822614668d4495
