### ISSUE TITLE
 BUG military training not gaining attack speed

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1222]
as the title

**Comment by darklordabc** [comment]
Hmm, I tested this and I got bonus attack speed as I leveled it up, can u check again pls.

**Comment by edotenseilove** [comment]
oh now i got it maybe it was just a bug but acording to the description about gold per level up it says that it can be upgraded 8 times but that ability can be upgraded only 7 times maybe you should change description or add that one level

**Comment by darklordabc** [comment]
I've fixed that bug, there was 8 values for the gold bonus, but it was only a 7 level ability

**Comment by edotenseilove** [comment]
thank you

**Comment by darklordabc** [comment]
No worries
