### ISSUE TITLE
SotF: Cleave is not in the selection menu

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1223]

**Comment by darklordabc** [comment]
What do you mean? Do you mean it doesnt exist?

**Comment by edotenseilove** [comment]
yes interesting is that in github files there is that ability and i can even add it trough addability command but it is not doing anything only gain charges but without any effect and icon

**Comment by darklordabc** [comment]
Cleaved is bugged so thats why it wasn't added

**Comment by edotenseilove** [comment]
oh i see thank you for explanation for me
