### ISSUE TITLE
chronotower cooldown bug

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1226]
![20170829131338_1](https://user-images.githubusercontent.com/19620604/29818339-2e9fbcf2-8cbc-11e7-9101-21bb4bf16cfa.jpg)
 cooldown should be 5 but it is 10 (the original cooldown)

**Comment by Fapboard** [comment]
Most of these tower abilities are unaffected by cooldown modifications with the exception of Arcane Arts.
 - Which ticks off a second on each prock efffectively.

Offtopic: I'd like to see some of the tower abilities deemed regardful to be enabled outside Singleplayer ability pool.

**Comment by darklordabc** [comment]
Custom passives don't get cooldown reduction. That's probably not great, but considering that all of them behave that way, it would require a lot of work if we were to change them all to getting reduced cooldowns, also it would introduce probably balance issues.
