### ISSUE TITLE
[Suggestion] Ability that is mana version of item heart of tarrasque

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1227]
Restores percentage of max mana per second. 

If damage is taken from an enemy hero or Roshan, this ability is disabled for number seconds for melee heroes, or number seconds for ranged heroes.

**Comment by darklordabc** [comment]
This ability sounds like it would be the best mana regen ability by far. I generally dont like to add abilities that will relegate others to useless, this would make a lot of the mana abilities useless. Prehaps it could have a bigger downside to balance it out?

**Comment by edotenseilove** [comment]
maybe add condition if damage is taken from **all** units and gave it higher cooldown and also percentage make a little bit lower
 of course there could be an op version without those downsides

**Comment by darklordabc** [comment]
What if we made a meditate ability, that will increase a % of mana but require you to channel to do it? @Wouterz90 would you like to do that?
