### ISSUE TITLE
[bug] Sometimes you cant consume items after team switch

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1229]
Sometimes you cant consume items after team switch. 
1) I buy Scadi
2) enemy leave
3) I switch to enemy team
4) I buy Heart
5) Now i can consume Scadi but cant consume Heart
![20170903160732_1](https://user-images.githubusercontent.com/26833529/30003585-7c2cc108-90c8-11e7-99ec-95dd57b02ec1.jpg)

**Comment by Wouterz90** [comment]
This should be fixed, let me know if it happens again
