### ISSUE TITLE
[bug] after last update someone cant get EXP  if players disconnected and shared xp is on

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1235]
after last update someone cant get EXP  if players disconnected and shared xp is on

**Comment by darklordabc** [comment]
Nobody can get exp?

**Comment by igor-netFantom** [comment]
Radiant was about 3 players + 2 leaver
Dire was about 2 players +3 leavers

Radiant was ~12 lvl
All Dire was 4 lvl and dont get exp for creeps at all

**Comment by darklordabc** [comment]
Is this problem reproduceable? I test it with bots and it still worked.

**Comment by igor-netFantom** [comment]
It was only once on all_allowed map after ban phase, loading and massive players disconnects on "build" phase. I think maybe all Dire was disconnected. I can't reproduce this too because this kind of disconnect is unusual. I write if i see it again.

Maybe it affects only players that was disconnected on start or maybe not, I don't know.

**Comment by DankBudd** [comment]
where there "ghost players" on either team? players who were never assigned a hero, and have a black hero  portrait.

**Comment by igor-netFantom** [comment]
>where there "ghost players" on either team? players who were never assigned a hero, and have a black hero portrait. 

At start was 2 at least. But i don't remember how long they was in that state. They could reconnect after... 
Two enemy players that was connected/reconnected say that they cant get any EXP and we was ~12 lvl, they was just 4 lvl and can't lvlup at all, so we all left and go new game.
Next time I will try to not forget to take screenshot.

**Comment by igor-netFantom** [comment]
Still can't reproduce and confirm issue. Looks like it's rare one.
