### ISSUE TITLE
[suggestion] Disable shared exp mutator for more balanced games

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1239]
Disable shared exp mutator for more balanced games. With shared exp ON games often goes one side. 
If one lane was feeded early, then all lanes have big difference in levels and you can't do nothing
5ppl x 6 lvl VS 5 ppl x 12 lvl

When only one player feeded without shared EXP then he can destoy one lane, but with shared exp ON all three lanes will be destroyed together.

**Comment by darklordabc** [comment]
Yeah we can give it a try, but I like how shared XP helps non-carry builds get EXP and prevents some heros from snowballing too hard.

**Comment by LoDfan** [comment]
I liked this change because it fixed long time picking strategy, when enemy makes counterpick and his hero is same lvl as other teammates
