### ISSUE TITLE
Perks balance [VERY BIG LIST OF CHANGES]

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1242]
Here is a list of my ideas about perk changing. Some heroes may have some of them because of very bad stats and talents. I used http://ec2-52-59-238-84.eu-central-1.compute.amazonaws.com/wordpress/#heroes  to understand what heroes are under powered and need a better perk. If you have better ideas please write them in comments below. So here is a list:

**batrider**
Firefly gives maximum ms
Firefly damage is increased x2 times
Firefly has 20% less cd and 100% free manacost
Flaming Lasso cd is decreased by 50%
has unobstructed vision when flying

**earth spirit**
Magnetize has 50% less cd
Every earth ability gives 10 hp and 5 mana regeneration per sec / 10 armor per ability

**sand king**
Burrowstrike has 50% less cd
Epicenter has 50% less cd

**warlock**
Has a unique ability : transform to golem which gives same abilities of golem without spell immunity and same attack range
Has golem armor aura increasing armor by 10/20/30 depending on lvl of ult (and may be has global radius)
Fatal Bonds cd is reduced by 50%
Shadow Word has no manacost

**shadow shaman**
reduce cd of his perk to 20 sec cd
Mass Serpent Ward cd is reduced by 50%
Ether Shock cd is reduced by 50%

**earthshaker**
increase % of healing from 2 to 10 % (make current perk stronger)
Echo Slam cd is reduced by 50%
Fissure cd is reduced by 50%

**brewmaster**
bottle is refilled every 15 sec
thunder clap has no manacost
thunder clap cd is reduced by 50%

**tidehunter**
ravage cd is reduced by 50%
gush applies break for same duration as a debuff (same for ags type of this spell)
Free additional kraken shell passive of lvl 1
Ankor smash has no manacost

**death prophet**
Has additional ability witchcraft of lvl 1
Exorcism has 50% less cd

**elder titan**
Earth splitter cd is reduced by 50%
Has additional ability natural order of lvl 1

**bane**
if bane is attacked by enemy hero last will be effected by nightmare lvl 4, has 20 sec of cd
Fiends Grip cd is reduced by 50%
Brain Cap manacost is reduced by 50%

**slardar**
slithereen crush has no mana cost
Every enemy attacking Slardar are effected by corrosive haze of lvl 1. Has 5 sec cd

**beastmaster**
has global radius of inner beast OR all aura radius is increased by 50%
Primal Roar cd is reduced by 50% (same for ags version)

**chen**
hand of god has no manacost
penitence also applies break

**visage**
grave chill also applies break
gravekeeprer's cloak refresh time is reduced by 2 seconds on every lvl

**magnataur**
Reverse Polarity cd is reduced by 50%
Empower has no manacost

**shadow_demon**
cd reduction of demonic abilities is increased from 20 to 30%

**puck**
illusory orb and dream coil cd is reduced by 50%

**disruptor**
thunder strike cd is reduced by 50%
static storm cd is reduced by 50%

**clockwerk**
rocket flare cd is reduced by 50%
hookshot has no manacost

**witch doctor**
cask cd is reduced by 50%
deathward cd is reduced by 50%

**kunkka**
torrent has no manacost
ghostship cd is reduced by 50%

**crystal maiden**
crystal nova cd is reduced by 50%
freezing field cd is reduced by 50%
has extra ability arcane aura of lvl 1 / or frost attack of lvl 1 (neural)

**omniknight**
light spell manacost and cd is reduced by 50% (old is reducing only manacost by 40%)
Guardian Angel cd is reduced by 50%

**meepo**
can poof to buildings
has extra ability geostrike of lvl 4 (I think casual lvl 1 is not so much)

**doom bringer**
cd reduction of demonic abbilities is increased from 20 to 30%

**dark seer**
vacuum cd is reduced by 50%
wall of replica cd is reduced by 50%

**spectre**
haunt cd is reduced by 75%
has an extra ability dispersion of lvl 1

**oracle**
just add a description what are support items

**jakiro**
50% of mana is returned to jakiro after casting fire and ice abilities sequentially
mana regeneration is increased by 1 for every point put to ice and fire abilities
has unobstructed vision when his mana is > 90%

**broodmother**
insatiable hunger cd is reduced by 50%

**nyx assassin**
spiked carapace cd is reduced by 50%

**Razor**
static link cd is reduced by 50%
unstable current is an extra ability of lvl 1

**Timbersaw**
increase current perk from 1 % to 2 % because it seems to be very week

**lycan**
Howl cd is reduced by 50%

**enigma**
midnight pulse cd is reduced by 50%

**templar assasin**
traps also appy break

**Lich**
receives gold for sacrificed units
chain frost cd is reduced by 50%

**winter wyvern**
has also unobstructed vision when is flying

**Riki**
blink strike has no manacost and cd reduced by 50%
extra passive ability - backstab lvl 1

**tinker**
perk's chance should be increased to 25% at least

**undying**
Flash golem cd is reduced by 50%

**bounty hunter**
track has no cd

**viper**
every skillpoint put to poison skills increase ms by 2 (or increase agi by 3)

**medusa**
mystic snake/stone gaze cd is reduced by 50%

**wraze king**
has no cd of buyback

**dragon knight**
dragon form cd is reduced by 50%

**enchantress**
nature attendance cd is reduced by 50%

**obsidian destroyer**
sanity's eclipse cd is reduced by 50%

**slark**
pounce has no manacost and leave existing perk because slark has not enough agi

**bristleback**
change perk from 15% to 25%

**axe**
battle hunger has no manacost

**ember spirit**
sleight of fist cd is reduced by 50%

**zeus**
increase perk manacost reduction from 20 to 40%

**arc warden**
magnetic field cd is reduced by 50%

**tiny**
toss damage to buildings is increased by 100%

**chaos knight**
phantasm cd is reduced by 50%

**ursa**
roshanify has 2 times longer duration
earthshok has no manacost

**Comment by LoDfan** [comment]
**Terrorblade**
Reflection cd is reduced by 50%
Metamorphosis duration is increased by 100%

**Storm Spirit**
Static Remnant cd and manacost are reduced by 50%
Ball Lighting manacost is reduced by 50%

**Comment by Fapboard** [comment]
This is a great list!

And i'd be happy to see atleast half of it implemented into the mod.

**Comment by 01der** [comment]
i agree that perks need an update, especially the weakest heros, and preferably caster favoring perks.
Some of these perks are great, but most would be too broken in my opinion.
When i feel up to it, i will make a list of my own suggestions.

**Comment by LoDfan** [comment]
I would like to see other suggestion. I'm not able to generate all good ideas for hero perks. If you have a good one even for some hero please write in comments

**Comment by averman** [comment]
I'd rather prefer that hero perks not attached to a particular skill, or just give them that skill freely at the start of the game. This makes choosing hero and choosing abilities kind of independent but the perks will enhance if you pick a certain category of skill (but not a particular skill)
