### ISSUE TITLE
[Bug] Infest support with Burrow redux

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1245]
Interaction of infeast and burrow, make the redux version of burrow gain invisibility

**Comment by LoDfan** [comment]
I saw this bug once, but I didn't manage to reproduce it because I forgot what skills that hero exactly had.

**Comment by igor-netFantom** [comment]
Zetysa, used this bug with this skills:
![20170929211611_1](https://user-images.githubusercontent.com/26833529/31029779-a84a8660-a55b-11e7-91db-e21e03a8bf28.jpg)

infest+borrow redux on invisible wolfs.
Dust and sentry wards won't help.

Just make infest with borrow redux and borrow as troll combo.

**Comment by darklordabc** [comment]
Infest and Burrows are now troll combos, please close this issue
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/63f66da25725065a06ccdf6bf4a7170f45f06f38
