### ISSUE TITLE
Crashing at abilities loading page.

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1247]
Can we change the default page into the abilities instead of recommended build. Because the loading of recommended builds is the main reason of crashing on wooden PC.

**Comment by DankBudd** [comment]
well by that logic it would be best to make it start on the hero tab, as the hero tab has the least things to load. (assuming custom skills are enabled)

**Comment by 01der** [comment]
I actually suggested this already in July. Still think it might help a lot.
#1097
