### ISSUE TITLE
[Suggestion] nerf Eldric Anti-Magic (it goes throw magic immunity)

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1249]
nerf Eldric Anti-Magic (it goes throw magic immunity)
Please disable eldric anti-magic then you under magic imunity.
Enemy uses permastun + eldric anti-magic.
(eldric anti-magic + borrow strike + Tempest Double + pocket factory + some stun)

You can't fight by auto-attack because he perma-stun you.
You can't use skills because tree stun you.
You can't use BKB because it won't help you.

Also after patch forced you to use 3 or less passives with 3 or more actives its even more powerfull.
I just have 3 skills that i can't use and BKB won't help at all.

**Comment by DankBudd** [comment]
👍  i support this change. make it not pierce magic immunity

**Comment by darklordabc** [comment]
I'm not sure how to make this change, @DankBudd could you change eldrich so it doesnt stun if the unit is spell immune?

**Comment by darklordabc** [comment]
I think the relevant code is here: https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/vscripts/abilities/overflow/eldri_anti_magic/modifier.lua

**Comment by DankBudd** [comment]
#1262

**Comment by darklordabc** [comment]
Should be fixed
