### ISSUE TITLE
Octarine Core breaks Bloodstone suicide

### ISSUE THREAD

**Issue by Solonarv** [darklordabc/Legends-of-Dota-Redux#1250]
If you have an Octarine Core and activate Bloodstone, you don't die; instead, you lose 75% if your current HP. Presumably, this is because the Octarine lifesteal triggers on the Bloodstone self-damage, thus healing you back up from 0 HP and "saving" you.

This bug is especially annoying since it's possible to consume Octarine Core, making it impossible to remove the spell lifesteal in order to restore suicide functionality.

I have not yet managed to test whether this bug also occurs in the regular game; I'll edit this PR once I do some further testing.

**Comment by LoDfan** [comment]
Also it seems centaur receives less dmg and can't kill himself (but I'm not sure)

**Comment by DankBudd** [comment]
you mean with double edge? thats already not supposed to be able to kill the caster.

**Comment by LoDfan** [comment]
No I meant Centaur and suicide using Bloodstone. Because of perk centaur doesn't die.

**Comment by DankBudd** [comment]
yeah it seems like centaur perk would do it too. ill add a check for bloodstone in octarine core and the perks code.

**Comment by DankBudd** [comment]
actually centaur perk doesnt seem to do this. but i made a fix for octarine core + bloodstone deny a25e1d4
