### ISSUE TITLE
[bug] save/load bans

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1251]
Не работает сохранение и загрузка банов в карте 'dota' .
Does not work saving and loading of bans in the map 'dota'.

P.S. translate google

![1](https://user-images.githubusercontent.com/28739948/31057539-253c4f68-a6ed-11e7-9626-77f4b7041cc5.jpg)
![2](https://user-images.githubusercontent.com/28739948/31057542-2aa765fa-a6ed-11e7-8332-a2ffe67d1f3f.jpg)
![3](https://user-images.githubusercontent.com/28739948/31057544-2e004e10-a6ed-11e7-8879-36ca80c02a5e.jpg)

**Comment by darklordabc** [comment]
![image](https://user-images.githubusercontent.com/16277198/31100114-f8f2eed0-a813-11e7-8127-1851765a7a6f.png)
It worked for me when I just tested it.

**Comment by russo-2025** [comment]
=( 
https://youtu.be/10oXDYegubo

**Comment by russo-2025** [comment]
@darklordabc how can i fix this bug?
