### ISSUE TITLE
Skill description

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1252]
неправильное описание умения 
incorrect description of the skill
P.S. translate google 

![20171001213524_1](https://user-images.githubusercontent.com/28739948/31057869-6bd44f0c-a6f2-11e7-9241-675d81fe6ce0.jpg)
![20171001213529_1](https://user-images.githubusercontent.com/28739948/31057870-6bf709f2-a6f2-11e7-963e-7f92f468437f.jpg)

**Comment by darklordabc** [comment]
Thanks. Fixed https://github.com/darklordabc/Legends-of-Dota-Redux/commit/aaaf6533fdac890e1b2a1d5d3102b7c7e7a43e14
