### ISSUE TITLE
Cheats createhero

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1253]
не работает
does not work

-createhero /name/ enemy

**Comment by DankBudd** [comment]
are you using the correct hero names?
e.g. skeleton_king
beastmaster
wind_ranger

**Comment by russo-2025** [comment]
я похож на идиота ? в имени свен сложно ошибится... 
Свен создается но не враг.

Do I look like an idiot? in the name of Sven it's hard to make a mistake ...
Sven is created but not the enemy.
P.S. translate google

**Comment by LoDfan** [comment]
Also created heroes aren't infuelnced by commands like -levelbots X or -givebots item Y
It makes more difficult to test and find abilities bugs in solo game.

**Comment by DankBudd** [comment]
createhero isnt a cheat made for redux, its a built in cheat. the only reason it wouldnt create enemies is if the enemy team cap is already reached. i dont remember what the cap is, but it is presumably 5.

**Comment by russo-2025** [comment]
no comments....
https://youtu.be/IpSgAiohIk0

**Comment by DankBudd** [comment]
@darklordabc did you somehow manage to break volvos cheats? xd
