### ISSUE TITLE
Silver & Linken's Sphere

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1254]
'Silver' блокируется предметом 'Linken's Sphere', что делает его бесполезным.
'Silver' is blocked by the item 'Linken's Sphere', which makes it useless.

P.S. translate google

**Comment by DankBudd** [comment]
why should it not be blocked by linkens? all other unit target items are blocked by linkens (with the exception of medallion / solar crest)

**Comment by russo-2025** [comment]
Silver блокируемый и отраженный Spell Shield(Anti-Mage) выглядит очень смешно.....
Я не могу это проверить из за не работающих читов

Silver blocked and reflected Spell Shield (Anti-Mage) looks very funny .....
I can not verify this because of the non-working cheats.

P.S. translate google

**Comment by LoDfan** [comment]
I wrote some time ago my opinion about silver.
Silver was made as an item to turn off passives for non invis mode. But attack from silver always turns off passives and new silver item not. Also hero with long range attack was able to turn off pasives from long range, but now it's impossible. Also if you want to turn off spell reflect/AM's passive with ags you'll fail.
So my idea was to give silver same mechanics of usual silver edge but without invis: Attacking to end the invisibility will deal 175 bonus dmg to the target, and for 5 seconds, disable their passive abilities, and reduce their damage output by 50% ; gives you phase movement for 14 seconds, or until you attack or cast a spell (while in phase mode, you move 20% faster).
Is it so difficult?

**Comment by DankBudd** [comment]
i dont agree with letting a unit target item bypass linkens, but changing the way the item works, like lodfans suggestion would be acceptable.

edit: would need to be more expensive if it gave all those bonuses tho.

**Comment by LoDfan** [comment]
It's recipe may be changed to Claymore + Ultimate orb + Recipe
Stats bonuses:
+15 Strength
+15 Agility
+15 Intelligence
+30 Attack damage
