### ISSUE TITLE
Lion Talent 20 lvl

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1255]
не меняется талант 20 уровня
does not change talent level 20

P.S. translate google

![20171001221515_1](https://user-images.githubusercontent.com/28739948/31058084-494a8bc8-a6f6-11e7-80fa-6ed7c9e2847c.jpg)

**Comment by darklordabc** [comment]
Fixed
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/e6f94ebab5ff4e8f5cbabda23af32c8d5588f2c7

**Comment by russo-2025** [comment]
@darklordabc 
![20171003201624_1](https://user-images.githubusercontent.com/28739948/31139641-df53bc18-a87a-11e7-97cf-a732bde490c1.jpg)
