### ISSUE TITLE
[bug] Infernal blade

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1256]
"Infernal blade" перебивает другие "Unique Attack Modifiers" даже если на нем кулдаун.
Так же стоит добавить в описание что это умение "Unique Attack Modifiers".

"Infernal blade" interrupts other "Unique Attack Modifiers" even if it has a cooldown.
It's also worth adding to this description that this is the skill "Unique Attack Modifiers".

P.S. translate google

**Comment by DankBudd** [comment]
already an issue #1161 
infernal blade is not supposed to be a unique attack modifier.
