### ISSUE TITLE
Hero builder [bug]

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1259]
баг при котором я не могу взять навыки.
в всплывающем окне написано:"Вы можете выбирать способности только во время фазы выбора."
почему я не могу поиграть без багов ????
2-3 игры = 1 баг
извините я горю.

a bug where I can not take skills.
in the pop-up window it is written:"You can choose abilities only during the selection phase."
why can not I play without bugs ????
2-3 games = 1 bug
sorry i'm burning.

P.S. translate google
https://youtu.be/k7WGFSecuzk

**Comment by russo-2025** [comment]
кажется, это связано с 'essense aura'/'essense aura redux'  и 'io'.
it seems to be related to the 'essence aura'/'essence aura redux' and 'io'.

P.S. translate google

![20171002132242_1](https://user-images.githubusercontent.com/28739948/31073638-7742abe4-a775-11e7-9073-3c33ee740f52.jpg)

**Comment by darklordabc** [comment]
How do I reproduce this bug?

**Comment by DankBudd** [comment]
this is caused by picking io
