### ISSUE TITLE
Some cheat builds with very high winrate that should be fixed

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1260]
Hero 1: fanaticism, Dispersion/borrow, Bristleback, Kraken Shell/antibash/spellreflect/spellshield/return + some active abilities
Hero 1 support: arcane symbiosis, tether, Overcharge, some other support skills
these combo of 2 heroes have 100% winrate when I played with my friend (100% of dmg reduction)
for solo game  fanaticism, borrow, Bristleback, return gives you 100% dmg reduction from back and sides and only 20% of dmg from front.
Also Chakra cd or rearm redux will help to use fanaticismnon stop (if you have enough mana)
-----
Hero 2: Arcane echo, focusfire, Bash of the Deep + 3 other skills and hero with random talent on 25 lvl and good base attack speed.
It just stunlocks enemy hero because of 35% of bash. Arcane echo needs to pierce linkens :)
-----
Hero 3:
Impetus + arcane orb + Geminate Attack + Lens skill + + arcane symbiosis + some skills giving int or mana
Hero 3 support: kotl + any build with a lot of manareg and vision
Just a lot of pure dmg and can't be countered by blade mail because reflected dmg doesn't hit hero in arcane symbiosis
-----
Hero 4:
fanatism+ passive vision skill (don't remember its name)+ dispersion+ some other skills
Just nearly same as hero 1 , but for active solo play. Based on 80% of dmg reduction. Just need to ask teammate to be far away from my hero.
-----
Hero 5:
centaur+Dispersion+Arcane echo+Life Break+Flesh Heap+some other 2 skills
Very snowball build. Just need to farm ags, heart and Octarine Core and gg
-----

I'm bored to play these builds, because they give nearly 100% win. Not interesting. So I ask dear LoD developers to nerf at least fanaticism, arcane symbiosis and Dispersion+Arcane echo+Life Break combo.
Thanks in advance.
-----

**Comment by darklordabc** [comment]
I'll check this out soon.

**Comment by 1ran-wang** [comment]
Those are really old fashion build. finatism's damage block has been nerfed
into 30%maximum and silver can easily kill the tank host.

**Comment by 1ran-wang** [comment]
But I agree that we should nerf life break.
half the cast range or double the cooldown.
