### ISSUE TITLE
Berserker's Rage + Roshanify = Troll combo

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1263]
Please make Berserker's Rage + Roshanify = Troll combo
Because Roshanity becomes unlimited by duration and may be used in range form (if aegis is picked up). So it'll be 2 bash passives on 1 hero.
![20171006110859_1](https://user-images.githubusercontent.com/24685202/31269007-69877ea2-aa87-11e7-95f0-6789b6ff7063.jpg)
![20171006110939_1](https://user-images.githubusercontent.com/24685202/31269008-6987c20e-aa87-11e7-8750-2f71b63b0069.jpg)

**Comment by DankBudd** [comment]
what is making the roshanify permanent? its supposed to have a duration again once the aegis is gone

@darklordabc should i make a fix for ranged roshanify using bersekers rage? or would a troll combo suffice?

**Comment by LoDfan** [comment]
> its supposed to have a duration again once the aegis is gone

Supposed, but after aegis is gone permanent roshanify effect remains till your death. After death you need to pick up aegis again

**Comment by DankBudd** [comment]
well i know for a fact that if you die with aegis you will lose the buff. 
so are you saying if aegis expires after ~5 min you will keep roshanify buff permanantly?

**Comment by LoDfan** [comment]
>  so are you saying if aegis expires after ~5 min you will keep roshanify buff permanantly?

yes

**Comment by DankBudd** [comment]
i dont think the ranged roshanify is that big of a problem. the permanent buff issue is fixed

and the "2 bash passives on one hero" is still weaker than taking 1 bash thats not berserkers, closing this
