### ISSUE TITLE
ardent strike + essence shift = troll cmbo

### ISSUE THREAD

**Issue by Techmind** [darklordabc/Legends-of-Dota-Redux#1264]
allows for both griefing and having hero with all the agi & str he wants from his team-mates

**Comment by LoDfan** [comment]
Agree it's fu..ing imba

**Comment by russo-2025** [comment]
sry =D
https://youtu.be/_CuZ_xbgHsc

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/2932fded15886fbec5d4516f5d16f7c38b2c5a85

Increased its cooldown to 4 seconds at lvl 4, hopefully will remove the abusive cases without making troll  combos.

**Comment by LoDfan** [comment]
> hopefully will remove the abusive cases without making troll combos.


No it won't because there is a bug (causing usage without cd):

1. start attack with ardent strike on
2. turn it off during attack animation
3. turn it on again after successful attack
4. repeat last 3 steps as long as your teammate is alive
