### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1271]
addon_english.txt
`"lodCategory_superop" "Single Player abilities"`
`"lodOptionDesBanningUseBanList" "Ban Single Player Abilities (SUPER OP)"`
`"unique_mechanic_warlock" "Warlock starts the game with a <font color='#ffd966'>Necronomicon</font>."`

addon_russian.txt
`"lodCategory_superop" "Dota IMBA способности"` (~Dota IMBA abilities)
`"lodOptionDesBanningUseBanList" "Использовать LoD запрет-лист"` (~Use LoD ban-list)
`"unique_mechanic_warlock" "Варлок получает в начале игры 2 <font color='#ffd966'>Observer Wards</font>."`

как написал бы я / as I would write
`"lodCategory_superop" "Single Player способности"`
`"lodOptionDesBanningUseBanList" "Ban Single Player Abilities (SUPER OP)"`
`"unique_mechanic_warlock" "Warlock начинает игру с <font color='#ffd966'>Necronomicon</font>."`

P.S. возможно я еще что-нибудь найду / maybe I'll find something else
P.S.S. translate google

**Comment by darklordabc** [comment]
It would be better if you made a pull request for the russian localization file

**Comment by russo-2025** [comment]
@darklordabc 
I would like to help, but I have no experience with git.
