### ISSUE TITLE
Phantom Dreadnaught. Custom skills.

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1272]
Пожалуйста уберите ненужные пользовательские навыки, многие из них просто ненормальные или несбалансированные. 
Пользовательские навыки редко берутся, потому что всем не хочется вникать в их механику, но если их пикают они очень портят игру.
Ниже пример навыка который за 1 каст просто сносит все хп башни.

Please remove unnecessary custom skills. They are mostly imbalanced or useless. Custom skills are picked seldom because new players don't want to learn their mechanics, but if they are picked (especially imbalanced ones) they ruin game flow. The example on one of such skill is below. It's totally op against buildings and can't be countered.

https://youtu.be/vAnmqRLjDlk
https://youtu.be/iVSgQYKUyjA

**Comment by 1ran-wang** [comment]
I Itried a build base on this ability once. It's neither OP nor building
buster. Try it and you will find It's just a normal push build.

And also custom abilities is the best part of Lod. it's called Lod redux
not Lod official. I agree that we could have a normal dota map. But I
really wanna keep them in Lod.

2017年10月12日 下午3:12，"YURNER0" <notifications@github.com>写道：

**Comment by LoDfan** [comment]
It seems this skill deals more damage to buildings then it's mentioned in description. According to description it should deal 25% of normal damage and this damage is physical, so it should be lowered by armor damage reduction.
Currently 3 level of ability with arcane echo destroys tier 3 tower and deals 75% of range barracks total hp at once. The only skill that can counter that is Guardian Angel, but it has much longer cd. So I suggest to move this ability to single player abilities.
Yesterday we played several games with this skill and such game were about fast push and buildings destroy and nothing common with regular dota or official lod. Each game was < 20 min.

**Comment by DankBudd** [comment]
670a7e2 
it wasnt actually dealing reduced damage to buildings, but next update it should work correctly.
