### ISSUE TITLE
[troll] Tempest and Starfall with Aghs

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1273]
Tempest allows to abuse the fact that the first starfall Aghs keeps triggering indefinitely so it lets you:
nuke heros,
push fast,
farm fast,
very broken and ofc bugged.

**Comment by Fapboard** [comment]
With the current standard of lodR current state:

It is basicly a snowballfest everygame of a single dude deciding the game in 15 min.

That's just one of the many possible combo's you can do in this boring, onesided fashion LodR is atm.
 - Banning, "adressing" or balancing this particular combo wont fix the root of the problem, theres just gonna be another one just like it a couple of days later and then a similuar thread will be created.

I suggest turning on: Shared_EXP_All again.

That will give the games a decent rubberband mechanic, instead of people just rushing towards the finnish and having one-sided games that are decided by 15-20 min of stomping.

**Comment by 01der** [comment]
i agree this won't fix the root of the problem (in this case its a bug) and there will always be some unbanned op combos, that will then get picked. Nonetheless banning the most broken ones is the best we can do for now. It has been stated in a different issue how some kind of pointsmode with self-regulating costs might be the answer, but that needs some skilled programmer with a lot of time.
After playing for about a month with Shared_EXP_All disabled, i also think it doesn't help balance so might as well get enabled again for all_allowed.

**Comment by Fapboard** [comment]
#Regulating the playerbase:

Not really.

Rightclickers gonna rightclick.

A self regulating points mode that will adjust like ebb and flow simply means theres gonna be diffrent seasons of overpicked builds.

And in the end, rightclickers still gonna rightclick.

**Comment by igor-netFantom** [comment]
> I suggest turning on: Shared_EXP_All again.
> That will give the games a decent rubberband mechanic, instead of people just rushing towards the finnish and having one-sided games that are decided by 15-20 min of stomping.

I don't understand how it would help. It just make all his team high lvl. 
With shared EXP off you have one strong enemy with OP skills.
And with shared EXP on you get five! strong enemies.
After that you will be pushed much faster and get 10 min game instead of 15 min.

**Comment by Fapboard** [comment]
The chain is only as strong as it's weakest link.

Now that his allies are gaining levels, but not nescesserily more power: More often than not you get someone who is high leveled taken down a big chunk of exp.

Not to mention that all of the allies of "the losing team falling behind" also gathers exp from all lanes.
As it stands, the snowballer just keeps everyone pinned down as he keeps on snowballing making a recovery impossible unless right efforts are applied.

And basicly the majority of the players simply becomes cannon-fodder or idlers while the snowballer is destroying the game.

It just simply evens things out, and that makes the average lod experience better.

**Comment by darklordabc** [comment]
How do you reproduce this? I had starfall and I used tempest double with scepter, but the double did not get the bugged starfall, he got the fixed one.

**Comment by darklordabc** [comment]
Anyway, I've made it so tempest doubles no longer get starfall and I've turned shared EXP back on.

**Comment by 01der** [comment]
@darklordabc Thanks!
