### ISSUE TITLE
"new" all_allowed spawning mode also for dota-map

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1274]
The wisp spawning is a bit more stable then the previous system and one of the reasons why dota-map is hardly played in lod, if we could get the new spawning also for dota map, it would definitely boost its popularity.
Starting banning screen at hero-tab might further help with the banning-stage-crashes.
A warning for when single player skills have been enabled and or troll-bans disabled would also be desirable.

**Comment by darklordabc** [comment]
Yes I want to do this eventually but it requires @TideSofDarK or @ark120202 to have a look at and they are kind of busy right now. We can do this after the 20th.

**Comment by darklordabc** [comment]
One reason we didnt use the new spawning method in the dota map is because it doesnt work with bots, but we can still enable it for only human games.
