### ISSUE TITLE
Would anyone be interested helping out and testing a new custom game we are working on?

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1276]

**Comment by LoDfan** [comment]
Did you stop fixing bugs in LoD? What this custom game is about?

**Comment by russo-2025** [comment]
каким образом она связана с lod  redux? / how is it related to lod redux?

**Comment by darklordabc** [comment]
Its not related to LoD, its a new custom game for the frostivus competition. I'll still occasionally work on Redux, not abandoning it, but the main focus is on the new game at least until the 20th of November when the competition ends.

**Comment by darklordabc** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=1165493298&searchtext=
