### ISSUE TITLE
Ice aura (custom) doesn't work with heartstopper aura

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#1277]
**Preconditions:**
all allowed map is loaded

**Steps to reproduce:**

1. select necr and ice aura
2. spawn hero
3. come close to creeps

**Actual result:**
creeps hp isn't reducing

**Expected result:**
creeps hp is reducing and they are effected by both auras

**Comment by DankBudd** [comment]
both of these work.
