### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1282]
Можно ли обновить те строки в addon_russian.txt, которые не переведены на русский язык или, если будет проще, взять за основу addon_english.txt и перенести туда то, что уже переведено на русский.

Is it possible to update those lines in addon_russian.txt that are not translated into Russian or, if it is easier, take as a basis addon_english.txt and transfer there what has already been translated into Russian.

___________________________________________________________________________________
`"DOTA_Tooltip_ability_ebf_rubick_arcane_echo_Description" `

addon_english.txt
`"Rubick, being the grandest magus there is, casts the last ability he used a second time. Echoed spells still require mana. Certain spells will not echo for balance reasons. Echoing Ultimates will cause this ability to take the cooldown of the ultimate."`

addon_russian.txt
`"Rubick, being the grandest magus there is, casts the last ability he used a second time. Echoed spells still require mana. Certain spells will not echo for balance reasons."`
____________________________________________________________________________________
`"DOTA_Tooltip_Ability_spectral_form_Description" `

addon_english.txt
`"You wrap the etheral around you becoming difficult to physically strike but weak against magic. While spectral you regenerate health and mana. Also your basic attack deals magic damage instead of physical. You deal %building_reduction%%% less damage to buildings.\n\n Upgradeable by Aghanim's Scepter\n\n<font color=\'#7D7D7D\'>Credits: Otso Turpeinen | github.com/OtsoTurpeinen</font>\n"`

addon_russian.txt
`"You wrap the etheral around you becoming difficult to physically strike but weak against magic. While spectral you regenerate health and mana. Also you basic attack deals magic damage instead of physical.\n\n Upgradeable by Aghanim's Scepter\n\n<font color=\'#7D7D7D\'>Credits: Otso Turpeinen | github.com/OtsoTurpeinen</font>\n"`
____________________________________________________________________________________

P.S. translate google

**Comment by darklordabc** [comment]
Yes, updating is as easy as updating the russian language file. If you like I can give you access to update the file directly and any new lines you add will be present in the next update.
