### ISSUE TITLE
antibash mutator thats not actually a mutator counts abbysal blade active as a bash

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1286]

**Comment by darklordabc** [comment]
Fix would be in here somewhere, not sure where. https://github.com/darklordabc/Legends-of-Dota-Redux/blob/5359039e363e5549ee7a8f3bd07a76bb802be1b3/src/game/scripts/vscripts/abilities/bash_cooldown.lua
