### ISSUE TITLE
Infernal blade op 

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1287]
Can you add a special infernal blade without those downsides. I like having witchcraft + infernal blade it was so cool also now i cant even seen spell amp upgrading of it and also dooms perk doesnt work eighter on it so please add an op version of this skill.

**Comment by DankBudd** [comment]
witchcraft + infernal doesnt really make sense, its an attack not a spell.

however, i will add the damage numbers popup and add it to dooms perk

edit:  93900ea
