### ISSUE TITLE
100level bugs.

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1289]
Some time players just get level 100. Can't reproduce but has follow features.

1. Only few players are 100lv no matter global exp is on or off.

2. Even If you kill the 100 level hero, You still cant get into level 100

**Comment by 1ran-wang** [comment]
Okay bug reproduced. Once a hero reach level 30. Any hero kills him will became lv 100.

**Comment by averman** [comment]
Level 29 also triggers the bug

**Comment by averman** [comment]
Also when I set level cap to 28, any hero killing a level 28 hero will become level 28 as well

**Comment by darklordabc** [comment]
hotfixed: https://github.com/darklordabc/Legends-of-Dota-Redux/commit/a40ab97c0ea4ab7bd92420ce02e8dd1d33f700a3

**Comment by DankBudd** [comment]
this is still happening. entire enemy team jumped from 40ish to lvl 100 after they won a team fight

**Comment by darklordabc** [comment]
Are you on the latest version?

**Comment by DankBudd** [comment]
yes, all the other changes were in the game

**Comment by darklordabc** [comment]
Well for now I uploaded a hotfix that limits levels to level 28 in the non-dota map. It will have to do until we can figure out the exp bug.

**Comment by darklordabc** [comment]
This is what FireToad told me about how he fixed it in Dota Imba. @TideSofDarK was planning on looking at this problem
> you set their bounty at level 1 when they first spawn
> https://github.com/RodneyMcKay/dota_imba/blob/8a33e6af9da886a411e4c32797dccf15d434e5ac/game/dota_addons/dota_imba/scripts/vscripts/hero_selection.lua
> GitHub
> RodneyMcKay/dota_imba
> dota_imba - Repo for the development of Dota IMBA, a mod for Valve's Dota 2.
> 
> line 585
> and then every time they level up
> https://github.com/RodneyMcKay/dota_imba/blob/8a33e6af9da886a411e4c32797dccf15d434e5ac/game/dota_addons/dota_imba/scripts/vscripts/events.lua
> GitHub
> RodneyMcKay/dota_imba
> dota_imba - Repo for the development of Dota IMBA, a mod for Valve's Dota 2.
> 
> line 791
> the whole function at 735 will probably be useful if you're dealing with levels above 25 for the first time
> solves shenanigans such as missing/extra ability points and so forth
> good luck
