### ISSUE TITLE
Ultimate hotkeys don't work

### ISSUE THREAD

**Issue by KaleeshWarlord** [darklordabc/Legends-of-Dota-Redux#1290]
When I play LoD, I have to manually hit the button on the UI in order to activate my Ult because the Hotkeys don't work. Any way I can fix this?

**Comment by darklordabc** [comment]
Can you give me a screenshot of this bug, I couldn't reproduce it.

**Comment by darklordabc** [comment]
I'm assuming this is fixed, I can't reproduce the error.
