### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1291]
Hi i successfully managed to make my own medical tractat which reduces cooldowns of my spells every time i cast it however i cant see actual cooldown in description of spells can someone please help me?

**Comment by darklordabc** [comment]
![image](https://user-images.githubusercontent.com/16277198/33405462-935b8f92-d5bc-11e7-8803-8e36a2a2a49f.png)
Does it have this in the ability data?

**Comment by edotenseilove** [comment]
yes when i use it it works well it reduces cooldowns but it is not visible in descriptions of spells. there is the old value for example when i use my custom modified madical tractat once the ability with 20 sc cooldown will have 18 sc cooldown but when i look on that ability it still shows 20 sc in description

or when i make my medical tractat to increase health regen and i use it it will work my hp will be regenerating faster and faster every time i cast my medical tractat it but when i look on the health bar or on the stats i will see the old unchanged values of regenerating (my hp regen is 20 and i can see 20 i use medical tractat and my hp regen is 25 but i can still see 20)

**Comment by DankBudd** [comment]
what are you using to apply these values. 
if its a datadriven modifier it should be showing up as long as you are actually using modifier properties.
but if its a lua modifier you are probably using IsServer() where you shouldnt be

**Comment by edotenseilove** [comment]
thanks for the advice i will try to change it and i will see

**Comment by edotenseilove** [comment]
well i think i have done something wrong could you please look at it and help me
[cooldown reduction tractat.zip](https://github.com/darklordabc/Legends-of-Dota-Redux/files/1545044/cooldown.reduction.tractat.zip)

**Comment by DankBudd** [comment]
try changing the name of the modifier_spell_cooldown_and_amp_tractate function. 
i dont think you cant have the modifier and that function be named the same
