### ISSUE TITLE
[Suggestion] Passive Insta-kill and Passive Invulnerability

### ISSUE THREAD

**Issue by GREYSQUID** [darklordabc/Legends-of-Dota-Redux#1295]
Obviously would be single player passives but my friends had an idea for a game mode where hero damage instantly kills(like midas or demonic conversion) all units or heroes are completely invulnerable. Former would be for short intense games while latter for cc/push intensive ones.

**Comment by darklordabc** [comment]
So you just run down the lane, one shotting all the towers and ending the game in 30 seconds? I dont get it.

**Comment by Acture** [comment]
I kind of have some idea about what he's talking. For example, you can give each hero a passive or whatever allow them to kill an enemy instantly. So everyone has to get survival things, like blink, bkb, phase shift, rage, etc. There're a couple of mods designed based on this idea. 
Examples:
Pudge War (https://steamcommunity.com/sharedfiles/filedetails/?id=296831818)
Hardcore Ninja (https://steamcommunity.com/sharedfiles/filedetails/?id=36883349)
Slide Ninja Slide (https://steamcommunity.com/sharedfiles/filedetails/?id=543923614)
