### ISSUE TITLE
Bilds Nimbus anti game 

### ISSUE THREAD

**Issue by nopesinetimore** [darklordabc/Legends-of-Dota-Redux#1296]
Nimbus + cd abilits + rearm
cause prema stun and damage, impossibilite move. This bild is interesting problem is prema stun, balancing nimbus redux no cause stun or troll combo nimbus + arcane echos, rearm, master of magic+cd abilits. I do not know the combo exactly.

**Comment by DankBudd** [comment]
the reason this is as strong as it is is because nimbus uses lightning bolts reduced cooldown, its not a fixed cd.

**Comment by darklordabc** [comment]
Slightly nerfed by making arcane echo go on longer cooldown when using nimbus. Nimbus wasnt counted as an ultimate before.
