### ISSUE TITLE
Midnight Pulse + Master of magic troll combo 

### ISSUE THREAD

**Issue by nopesinetimore** [darklordabc/Legends-of-Dota-Redux#1297]
Midnight Pulse + Master of magic + stun cause easy kills, using + chono anti game.

**Comment by 1ran-wang** [comment]
pick Faceless void can counter this build.

2017年11月29日 下午5:22，"nopesinetimore" <notifications@github.com>写道：

**Comment by darklordabc** [comment]
Yeah this is powerful but I dont know if its a troll combo enough.
