### ISSUE TITLE
hero default perk bug not level up ,and other issues

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1298]
hi dev , really appreciate your hardwork, but i would love to let you know that is some annoying bug i hope you can fix,
1. urgent:the default hero perk is only level one and cannot upgrade to level 4, can thisbe fix(for example monkey king had jingu mastery learn defaultly despite he learn or no learn the skill-but the problem is it always level one only cannot be upgrade(late game with only level one skill is unbearble) psl do fix so it can level up normally

2. urgent:the ingame hero builder is bug ,once u change skill half way in game ,all the hero perk tree cannot be learn and click despite doing anything ,pls do fix

3. not so urgently :some of the new hero still no have their own default unique perk,hope to see they can be added as well

Thnx dev, and kindly reply ,wish you a good day and continue to keep up the awesome job

**Comment by 1ran-wang** [comment]
thanks for the feedback!

the reason that we locked perk ability level is for balance.

Monkey King has the max atk distance in melee heroes. So it will be too OP
for him to have a extra skill.

2017年12月2日 上午1:42，"jephat" <notifications@github.com>写道：

**Comment by jephat** [comment]
hi ty for reply , not only this hero, virtually every hero with some default perk( despite not picking the skill they still will learn) is only stay at level one(pls take a look,just to name a few for  example SF necromastery also level one ,luna (lunar default lunar blessing also level one),alchemist grevil greed also level one , all cant level up.

**Comment by 1ran-wang** [comment]
Yeah As the description of perks part. it says all perks are Unupgradeable.

Which means perk = free level 1 Unupgradeable ability.

And we still working on new perk system, so this system might just for
temporary use.

2017年12月2日 上午3:00，"jephat" <notifications@github.com>写道：

**Comment by jephat** [comment]
o ok noted ty  for reply ,looking forward to the new update,keep up the good work

**Comment by 1ran-wang** [comment]
thanks, really appreciate the feedbacks let us know If you got any good
idea.

2017年12月2日 上午7:27，"jephat" <notifications@github.com>写道：
