### ISSUE TITLE
Arcane echos + weaver perk is bugued 

### ISSUE THREAD

**Issue by nopesinetimore** [darklordabc/Legends-of-Dota-Redux#1300]
the arcane echos resets the perk cd.
I really like the work of the team here, I played this mod in the garena, I do not know if the developers is the same, I'm very happy to have found this way here, I just have to thank you.
will you be able to add some troll combos that are really problem;

life break + dispersion or + natural ordem or + arcane echos(there are several combos one hit with this ability but I see that with passive skills this gets well unbalanced);

swashbuckle + infernal blade (she is trouble with everything But with this you're stuned);

bedlam much op (this ability is almost like a cancer,not banned and caught); 

thanks for listening, I speak this in question see for example dispersion + retur(cent) considered troll combo more others not.

**Comment by darklordabc** [comment]
Arcane Echo no longer works with ultimates.
