### ISSUE TITLE
Bug can't play at all.

### ISSUE THREAD

**Issue by wzyas** [darklordabc/Legends-of-Dota-Redux#1304]
After I start a game And we vote. We get in the baning phase the game disconect me (and some friends) when I try to reconect I can't pic skillls or hero. I can't even have an ramdom hero with ramdom skills i just can't play at all.

**Comment by DankBudd** [comment]
already an issue #1198

**Comment by darklordabc** [comment]
This is a known bug, and I'll get @TideSofDarK to have a look at it today/tomorrow.
