### ISSUE TITLE
toggle movement phoenix sun ray missing

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1308]
hi as title mention, phoenix 3rd skill sun ray miss a toggle movement button, thus phoenix cant move 
forward or stopping while casting sun ray ,pls do fix it by adding a toggle movement for it like normal dota,otherwise this hero is unplayable ,

**Comment by darklordabc** [comment]
Added

**Comment by jephat** [comment]
ty dev appreciate it
