### ISSUE TITLE
Need New Perks for Pangolier and Dark Willow

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1309]
The new heros don't yet have perks.

**Comment by jephat** [comment]
hmm how about pangolier have default heartpiecer despite he learn or not learn
as for dark willow + 25%  magical damage when casting default skill ,just a suggestion :)
hmm by the way jsut want to bring out the issue in case dev forgot, the ingame hero builder switcher is buggy if u decide to change half way the skill build in game , the hero perk cannot level up anymore (pls do check it yourself) .Keep up the good work dev,P.S. will there be any new item release just for lod redux?(i so greedy haha).Wish you a good day

**Comment by jephat** [comment]
my mistake so 9.9 changelog have been release will seeing phoenix sun ray toggle movement soon ty dev

**Comment by Fapboard** [comment]
Suggestions on unique perks for models (while also applying the swappable talents as on other models):

One of the following for Pangolier:
 - Gains a level in Swashbuckle regardless of draft
 - Gains a level in Heartpiercer regardless of draft
 - 20-50% cooldown and manacost reduction on mobility abilities.
 - Gains movementspeed bonus of agility regardless of primary stat (Gains double value if Agi is primary)
 - Heals <X>/<Z%> per distance traveled. (Flat or percentage of max hp).

Dark Willow has one of the following:
- Gains +2 to all stats per support skill leveled up ingame.
- 20-50% cooldown and manacost reduction on support skills ( if not already taken by other model).
- Is untargettable for 3 seconds after casting a support skill. (Mimmics the effects of her own ability).
- Gains an aura that shares % of her magic resistance.

**Comment by darklordabc** [comment]
I went with Paonglier gets free level of Heart Piercer and Dark Willow gets 2+ to stats per point in support abilities.
