### ISSUE TITLE
Magicians Revenge does nothing

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1311]
After it's "fix" slapped on it, it does nothing and i'm wondering what it's still doing in the game.

I suggest keeping the cooldown that was placed on it to prevent instant-melt enemy heroes with dots scenarios and simply up the modifier.

The reason being that it can simply be ignored and has no impact during a game.
 - I give this ability a 1/10.

The reason being that < your int > minus < their int > and then 70% of that value is simply non-existant and has no impact on the game.
Beyond dealing about let's say:
150 int - 50 int -> 100 int x 0.7 = 70 dmg returned every 0.5s.

Any carry in the mid-late game has above that in attack speed and bypasses alot of potential dps (unlike Return from centuar, Dispersion from spectre), and guess what: They also buy lifesteal and max hp items such as hearth, satanic, sangeyasha and skadi.
 - Having on average 3k-5k hp and 350 dps -> 600 dps.

And at that point it's a fucking joke, Magicians Revenge doesn't justify being picked.
Ît's a shame it was jus simply "fixed" without checking the outcome of this ability and how it performs afterwards. 

As it is, it simply just doesn't pay out.

So heres what i'm thinking, upping the modifier from 70% to 150%-200%, which I find plausible considering the cooldown preventing any "off-the charts" shenaniganz.
And perhaps even remove the int-diffrence as a factor.

I'm open to suggestions, bust mostly i'd just want this to be implemented in the game.

Worst case scenario, darklord will nerf it again or re-load it to it's previous state.

**Comment by darklordabc** [comment]
Its been buffed. Lowered cooldown to 0,3 and it goes up to max 100% intelligence, best I can do for ya for now.

**Comment by Fapboard** [comment]
Seems like something was already in the works or you were simply just that quick about it.

Preferably i'd go with my own idea and embracing the concept of larger hits less frequently, so that it actually packs a punch which in turn can be countered by other ingame-mechanics cooldown oriented tactics (such as satanic or bkb) instead of just simply beign a flat power boost.

But this will be fun to experiment with none-the-less when the update goes live.

Appreciate the quick response.

**Comment by darklordabc** [comment]
No worries

**Comment by Fapboard** [comment]
I'm reopening this thread again for the sake that Magicians Revenge (Atm called Whiteboard's Revenge) still suffers from the same problem it previously had.

Which is that it has a threshhold of destroying anything that falls beneath that threshhold uncontested and having no affect at all on those above it.

Diffrence is now that the threshhold is higher.

I said this before despite the recent buff it gained and from a developer standpoint i'm not satisfied with the results which are just simply plain unfair from an interactive standpoint and the ability should have a higher cooldown and pack a bigger punch (High damage ocationally) rather than having low cooldown and always damaging anything that pokes you (which results in people with dotrs instantly destroying themselfs) or not doing anything at all.

It's been some time now since this buff and that remains true as expected from theory to practice that some heroes just falls short uncontested and are obliteraded completly while others are just simply unaffected ands its just plain fucking dumb to have it that way instead of having it more interactive and rewarding than just casually weeding out the weaker opponents effortlessly.

And the problem was that got it nerfed because M'Revenge acted as a power threshhold in the first place.

As it is now it has 0.3s CD with 100% of your int minus theirs in damage.

As it should be: 1.5-2.0s cd with 200%-250% of your int, not reduced by any assailant int.

Instead of pretending to be something it isn't, it can do something.
