### ISSUE TITLE
Update Save/Load Bans to use server

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1313]
It used to use scaleform local storage, but that's been removed and no longer works.  We need to convert it to using online storage like we do for the settings.

**Comment by Fapboard** [comment]
No longer occurs ingame on active players since level cap was raised to 100 again.

Does occur on leavers for uninvestigated reasons.

**Comment by darklordabc** [comment]
What still occurs? Did you reply to the wrong issue?

**Comment by Fapboard** [comment]
Yes.

Fuck this laggy homepage.

You can ignore my previous reply.
