### ISSUE TITLE
import from dota fun v 2.05 ai item ,skill and character

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1314]
is that any possibilities?

**Comment by DankBudd** [comment]
link the workshop page of the mod you are talking about.
the answer is likely no, that sounds like a meme mod and probably doesn't have much that would be reasonable to add.

**Comment by jephat** [comment]
https://steamcommunity.com/workshop/filedetails/?id=956357541

**Comment by darklordabc** [comment]
Anything in particular that is unique and cool?

**Comment by jephat** [comment]
not sure but the fun hero look cool, but i think is not possibel at the moment becoz they actually put the skill on the existing hero ,item in that map is pretty cool like angelic aliance and others
