### ISSUE TITLE
Buff Perk: Vengeful Spirit

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1315]
Comment: The passive simply just doesn't have any impact on the game. Losing a branch in exchange for a kill does (not just even) get balanced out by the simple farm you get in return and momentum/advantage by gameflow it gets canceled entirely by a single flesh heap of chosen attribute.

Suggestion: Buff the value from 1 -> 3 or if thats too drastic I believe another perk should replace it.

And tbh, it should be a drastic change. Thats the only way to see the flaws, either double of half.
 - Or like i said, a new perk entirely.

**Comment by Fapboard** [comment]
For a week now this thread has gained 0 intrest/attention.

So i'll drop a suggestion for alternative perk for VS alongside the previous suggestion of buffing the integer from 1 to 3, to get some sparks flying.

- Gains vision over it's killer until VS respawns (with a lingering 10s debuff after respawn).
- Casts haunt on owner of killing blow on respawn.
- Casts one/any spell not on cooldown on target area/owner of killing blow on death.
- Has a hidden respawn not displayed to the enemy team.
- Places a stackable debuff on it's killer, consumes debuff when killed by VS to gain 5% Damage increase on her aura. Debuff also applies a stackable -5 armor to owner of killing blow. Each stack is consumed/placed one kill/death at the time.

Am proud to present these aletnative perks for such on which is downright pathetic, to me it seems more of a filler perk just waiting to be replaced by something decent.

I mean, cmon. 1 stat loss per death.
People dont care and happily takes the kill without that perk having any presence at all.
 - Same with agha's of Arcane Symbiote, that bonus needs to be buffed or replaced.

I would say i'm open to suggestions, but once again i'd just really like to have a response from a developer and have this perk dealt with and see it to be changed ingame.

**Comment by darklordabc** [comment]
I'm reluctant to discuss buffing VS's perk, because out of all the perks, it is probably in the top 10. If we want to buff the perks, we should start buffing the bottom 10, not one of the top 10s.

**Comment by Fapboard** [comment]
Vs perk is on the bottom 10.

There is no reaction whatso-ever during ingame time by killing a VS towards her "loose a branch when you kill me".

In the strict trade/value district, you gain more benefits killing her than you go backwards.

Minus one branch per death is downright pathetic of a perk that accomplishes nothing.
Any given hero with Flesh heap for a mainstat directly deletes VS perk.

Then it shouyld either do something else or get buffed.

If youre reluctant towards buffing it, then that means that you are afraid it's gonna be too powerfull and blow the roof up -> so it remains halfassed, incomplete and ends up doing nothing.

Shake it up a bit.

An example of a top10 perk would be: 
- Lion (75% CDR on kill), 
- Monkey King (Absurd passive for free plus good stats for his model), 
- Underlord (With his recent update, gains +2, a hefty chunk of power right there), 
- Weaver (Has a free auto-mated timelapse with low cd), Pheonix (Similuar stuff to weaver).
- Spirit Braker (applies break on bash, topmeta stuff currently overlooked by its casual playerbase).

Theres more examples of top 10 perks in lod redux that all has a significant impact on the game that changes how people play.

Vs perk does not change how people play.
 - You go "huh", when you notice you lost 4-7 to all stats at end of game.

The lack of reaction alone proves how weak it is.

Some examples of other bottom 10 perks would be:
- Clinkz (Levels an autocast on spawn).
- Viper (Applies a non-stackable -2 armor debuff when casting a psn skill).
- Templar Assassin (Free stealth, Actually good, but barely functions fluently ingame).
- Queen of Pain (Gains/Takes 10% more damage from male/female models, simplunplausable to play around for a small benefit).

Punchline is: VS perk is on the bottom 10, not top 10 of perk abilities.

Frankly If you think VS has a powerfull perk, then you obviously do not play the game at all.

And especially now when the level cap was raised up to 100 again, and I do believe it will stay that way (by default), people have alot of stats to give away ingame before they start giving a fuck.

And at that point, the game is allready probably over after feeding the enemy 75 kills to 150 kills on a single player.

The more you think about it, the dumber it sounds.

I'd look forward to having this perk ability changed ingame.

**Comment by Fapboard** [comment]
I would like to know what it is, that makes VS perk good from your perspective Darklord.

**Comment by CaptainDildac** [comment]
The problem is the suicide girl builds that were viable when the perk was buffed and fury of the immortal was added were too strong, when the perk was 2 attribute loss it was too easy to force trades where permanent stacking debilitation could be done to the entire combat capabilities of a hero while also simultaneously being a favorable play style for the build. Now that the environment that supported it has sorta fallen out it needs to be looked at again, i agree. Perks that cause permanent damage to attributes however, generally are either bare minimum effects or a single point pushes it too far. We've seen VS perk be strong, we've seen it be less than worth, time to use that knowledge to make something less binary.

**Comment by Fapboard** [comment]
Well, it's either buffing it or changing it.

So it will be the other option: To change it to something else.
