### ISSUE TITLE
Old Abilities

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1319]
Is it possible to add old abilities like viper´s tiny´s dazzle´s morpling´s razzor´s and so on using lua spell libraries like [https://github.com/Pizzalol/SpellLibrary] and moddifiing a little bit? I know that many bugs that needs to be fixed accourd so if this will be after a long time or would´nt be even created i understand it.

**Comment by DankBudd** [comment]
yes it is possible to add them, some old abilities have been recreated and added before.

if someone makes a pull request to add such an ability its very likely to be merged, probably best to ask first though.
