### ISSUE TITLE
suggestion anti-tenacity Aura

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1320]
Since there is a new atribut bonus: Status resistance i think we should have something to counter it: i have an idea of makeing an anti-tenacity aura ability: basicly an aura that amplify duration of spells on enemy unit

**Comment by Fapboard** [comment]
More stuns, more win.

**Comment by DankBudd** [comment]
you already suggested this #1167
all the comments are just saying it would be broken
