### ISSUE TITLE
phoenix sun ray have toggle movement but unable to assign hotkeys for it ,pls fix

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1322]
as title mention ,dev add phoenix sun ray  toggle movement but the toggle movement unable to assign hotkeys for it ,pls take a look and fix it ty

**Comment by DankBudd** [comment]
theres not really much that can be done to fix this. you can have hotkeys for 6 abilities at most, thats just the way valve has their ui coded.

its technically possible to add more hotkeys by remaking the ui from scratch but thats more work than its worth
