### ISSUE TITLE
Thirst bug

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1329]
I have been playing thirst builds a lot but when i played it today it works well a little while but after a few minutes i  died and then i recieved dubuff with was reducing my max movement speed to 550 and i also start commiting suicide after i respawn without pressing anything. I first tought that is because  i have been playing my moddified version of redux but i tested it in official version of redux but it happened too.

my build was plains runner book of agility thirst rupture and flaming laso

**Comment by DankBudd** [comment]
did the debuff have a name/description and or an icon?

**Comment by darklordabc** [comment]
Do you have steps on how to reproduce this bug?

**Comment by edotenseilove** [comment]
i was leveling increasing my movement speed using tome of agility and agility hero and one level in thirst op then i start killing  but i died and when i respawned i started commiting a suicide again and again  but after a few respawns it stops and i could play without commiting suicides but the movement_spee... debuf still remains on my hero so i couldent extend my movement anymore

**Comment by edotenseilove** [comment]
it has  been fixed so i am going to close this
