### ISSUE TITLE
Make Assassinate Redux work with the castpoint reduction talent

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1330]
Assassinate has been remade for Redux but it doesnt currently interact with the talent for it. Need to change the code of the ability so it checks if the player has a level into that talent. 
![image](https://user-images.githubusercontent.com/16277198/35070801-a8f638ba-fc32-11e7-9f8a-0018e56aa245.png)

**Comment by Wouterz90** [comment]
https://github.com/ModDota/AbilityLuaSpellLibrary/blob/master/game/scripts/vscripts/heroes/sniper/assassinate.lua

Is an improved version of whats already in here, it should also have the cast point talent. It may have _lua tag behind it which needs to be removed.

**Comment by Fapboard** [comment]
Also make sure it interacts properly like every other spell in the game with things like your characters spell amp and other modifiers.

At the moment, the current custom made Assassinate interacts only with cooldown reduction (both items, non-existant talents and abilities) Multicast and supposively Cast Range (unconfirmed though).

Does not interact with Flesh Heap: Spell amp, ingame character stat spell amp, Spell Crit and perhaps other abilities as well which I may have forgotten.

May also be worthwhile to mention the crit from boosted version (which is supposed to be 100% x2) malfunctions at random, despite other onhit modifiers are absent which may interfere with the crit: like other crits.
