### ISSUE TITLE
Make Slardar's Perk only apply to abilities

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1331]
@DankBudd did you intend the perk 50% more damage to apply only to abilities, because right now it also applies to right clicking, which is too powerful IMO, it would be a good perk if it only applied to abilities that do physical damage like, Crush and Hook. 

Also when perks are updated, there is 3 text fields that need updating in addon English. You missed this one that is on the ingame display on the hero picking section. 
![image](https://user-images.githubusercontent.com/16277198/35072187-ac5ee4ca-fc37-11e7-8a7e-ccae6cfacccf.png)

**Comment by DankBudd** [comment]
yes its intended to include right click damage. the original idea was to double any -armor effects applied by slardar but i couldnt think of a feasible way to do it.

and wat. that picture has the updated tooltip. i left the "cant use basher" part in there because i didnt change anything related to that.

**Comment by DankBudd** [comment]
theres really not that many physical damage abilities. the perk would have pretty limited uses if it only applied to abilities. 

a lot of the abilities in this list are talents and neutral skills
https://dota2.gamepedia.com/Concept:Physical_damage_abilities

**Comment by darklordabc** [comment]
It would work for his Crash, and there is actually quite lot of physical abilities, moreso than some other talents, like fire or ice abilities. I actually think it would be a pretty neat niche, but physical right click damage is too much of a bonus, and doesn't really thematically match slardar. Would you be able to change it for only Physical damage from abilities?

**Comment by DankBudd** [comment]
already done, forgot to close the issue
