### ISSUE TITLE
Map/Mod dying.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1337]
Change default map to All_Allowed on LodR.

**Comment by Fapboard** [comment]
Takes about 45 min - 2 hours to get a full game.
Where atleast half leaves, majority at the start of the game.

I get a single game a day now since this change was made.
Down from being able to play Lodr all day long if I so wanted.

Protip: people/players without any persistance or intrest simply will not play no matter how much you lower the bar for them.
Plus the game gets more frustrating for those who do have an intrest in the game.

This change is bad and stiffels playerflow and activity and should go back to having All_Allowed as default map again.

**Comment by Acture** [comment]
agree.

**Comment by Fapboard** [comment]
Bumping this thread.

While flipping the steak to the other side:

- Has this change recieved any constructive positive feedback?
- Has it achieved desired results?

- Regards, Whiteboard.

**Comment by Fapboard** [comment]
Bumping this thread.

It's hard getting games.

**Comment by Fapboard** [comment]
Bumping this thread.

This change has only made games more of a hassle getting started and no one is appreciating this specific change nor is it accomplishing the desired effect.

People just simply play classic now out of lazy/tardiness.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
I got bad news for you, bumping doesnt work with github issues, they don't change order.

**Comment by Fapboard** [comment]
Unfuck the mod with this decision.

- Regards, Whiteboard.

**Comment by Fapboard** [comment]
Bumping this thread.

Still as annoying as ever to find classic maps being hosted with only a handful of people idling.

Soon as I tell them that mode has no custom abilities and that I rehost.

People always come to my custom lobby afterwards.

Nobody wants to play classic map minus a simple awareness factor.

- Regards, Whiteboard.
