### ISSUE TITLE
"Entangling Claws has no CD" doesn't work

### ISSUE THREAD

**Issue by Acture** [darklordabc/Legends-of-Dota-Redux#1338]
One of Entangling Claws related talent is "Entangling Claws has no CD". The spell will still have CD after picking this talent.

**Comment by DankBudd** [comment]
i imagine it doesnt work because the skill is supposed to be on spirit bear.
so if you had the entangling claws talent AND a spirit bear, the spirit bear would get the benefit.

to make it work for heroes the ability would need to be re-made.

**Comment by darklordabc** [comment]
I've disabled them since they dont work, so you will random some other talent now if you have entangle.
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/1de3e325c976e023948a5a96b75e49075647461b
