### ISSUE TITLE
Dead players can earn exp from sources around where they died.

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1341]
or so i believe. im not sure if its actually limited to the area around where you died.

but i am certain that after dying in a team fight i leveled up several times from my team wiping the enemy team.

**Comment by Fapboard** [comment]
Game mod: Shared_Exp.

Game item: Bloodstone.

Besides those 2 you do not gain exp while dead.

Except for one potential lose thread, which is that is if valve has updated the game to reward entire team on kills (with a potentiall lingering time frame and/or if you have assisted the fight somehow according to game rules).

**Comment by DankBudd** [comment]
yeah i just didnt realize all_allowed has shared exp enabled, my bad
