### ISSUE TITLE
Attack modifiers

### ISSUE THREAD

**Issue by Acture** [darklordabc/Legends-of-Dota-Redux#1342]
1. Some attack modifiers like antimage's will be applied if you are denying.
2. Meepo's attack modifiers will always have the sound, even before you actually learn it.
3. Illusions will have the visual effect for any 'diffusal' ability or talent before learning it.
4. Illusions don't inherit consumed items or book of attributes.
5. Is it possible to make items like skadi still have visual effects when consumable items is on?

**Comment by DankBudd** [comment]
1-3. these are problems with dotas base abilities that we cant fix without recoding them from scratch.
4. that should be a simple fix, ill try to get that working.
5. yes its possible.

**Comment by darklordabc** [comment]
5. What do you mean? It does apply the visual debuff effect on enemies, even when you have consumed it. Could you test this again to confirm if the problem exists?
https://imgur.com/KDrCUJw

**Comment by Acture** [comment]
5. Not the debuff for enemy, but the visual effects of items. Like if you have desolater your attack will become red. In current patch, if consumable items is on, deso won't make my attack become red.

**Comment by Acture** [comment]
This only happens to range heroes.

**Comment by darklordabc** [comment]
Ah I understand now
