### ISSUE TITLE
New ability: 

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1343]
An ability I have thought out which i'd like to see implimented.

It's an inspired concept from Battle Tanks from wc3, more specificly Pheonix Fire.

---
Arms your hero with a side laser cannon that passively fires lasers to nearby enemy units.
Does not fire at structures.
Has instant projectile speed vs non-hero units.
Has 0.5 damage delay vs hero units.
Costs 80 points to pick (If points mode is enabled).

***
Edit:
Ability has been discussed with a developer of the project for an alteration of this ability:
Deals up to 100% of it's damage based on your current % of your mana pool.
***

Projectile: < Tinker laser, sound volume reduced by 50% >
Damage type: Magical.
Skill: Passive (With Active clickable effect).
Range: 600 / 700 / 800 / 900
Damage: 75 / 150 / 225 / 300
Cooldown: 4 / 3 / 2 / 1
Active effect: Costs 3000 Gold - Intalls another Laser on this hero permanently.
Aghanims effect: < Blank / I'll get back to it later on >.
---

Sidenote: It is intended to fully interact with other modifiers allready existing in the game.
Examples, spell amp from int, items and abilities, bloodrage, cast range etc.

Cast range I admit will be diffucult since it doesn't apply to passives and auras as it is atm, which I find understandable if that doesn't apply to this ability.

**Comment by Fapboard** [comment]
Forgot to name the ability, but it doesn't matter, can be called w/e.

**Comment by darklordabc** [comment]
What is the difference between this and Gyros side gunner?

**Comment by Fapboard** [comment]
Gyro's is better.

It crits for 3k dmg with on-hit effects enabled, along with alot of other broken combinations.

Plus it disregards passives being disabled from silver (by functioning through it's buff that it has and not it's original cooldown -> bypassing silver effect).

This is a spellcaster variant of it that deals magical damage instead of physical and interacts with the other side of the coin of lodr.

While at it, its honestly more balanced than Sidegunner.

Plus I just simply found it a fun concept I thought out while at work 1-2 days ago.

- Regards, Whiteboard.

**Comment by Acture** [comment]
It makes me think about this mod, NavalWarfare :
https://steamcommunity.com/sharedfiles/filedetails/?l=schinese&id=524239685

**Comment by DankBudd** [comment]
so its literally just a better unstable current? razors ability.

**Comment by Fapboard** [comment]
No, it's litterally a pheonix fire inspired ability.

**Comment by Wouterz90** [comment]
I'm going to leave the range at a constant 900 because I don't see why it should scale so much in all directions. I'm not too big of a fan of this damage increase and the frequency increase at the same time too, but I'll leave that for now.

> Has 0.5 damage delay vs hero units.

It's a laser, should it really travel on a low velocity? What's the point of making it slower when the enemy is nearby?

**Comment by Fapboard** [comment]
I'm going to leave the range at a constant 900 because I don't see why it should scale so much in all directions. I'm not too big of a fan of this damage increase and the frequency increase at the same time too, but I'll leave that for now.

- The range growth is standard classical ability growth stampmark, much like other abilities in the past, the range grows as the ability levels up. Only seems natural and traditional to level it up for full power.

- Damage/frequency, if these are to be changed, I need to rescale the whole thing.

Has 0.5 damage delay vs hero units.

It's a laser, should it really travel on a low velocity? What's the point of making it slower when the enemy is nearby?

- It's a game design thing, gives players a fair chance to disjoint/respond to the projectile instead of just being instantly fucked, much like Laguna Blade (Besides the fact that its a big bomb vs a lot of pew pew, princip remains the same if it's a killing blow).

- Is instant for non-hero players for satisfaction instead of frustration.

**Comment by Fapboard** [comment]
Also: It's not ment to be slower when an enemy is nearby.

It's ment to have a damage delay towards hero units.

**Comment by Fapboard** [comment]
Also want to mention I look forward to the results.

- Regards, Whiteboard.

**Comment by Wouterz90** [comment]
I have had the code ready, just didn't have time to test it. Should be up today!

**Comment by Fapboard** [comment]
Awesome, looking forward to it.

Did you make sure to have the activatable effect working as well?

- Regards, Whiteboard.

**Comment by Wouterz90** [comment]
The part where you can buy another laser? Yes.

Click to chose a target becomes messy with autocasting, and is a huge boost to the already strong ability.

**Comment by Fapboard** [comment]
It wasnt ment to target anyone or anything with the active effect, just like warstomp.

You just click it for it's effect to happen -> Installs another laser on hero.

Otherwise, sweet.

- Regards, Whiteboard.

**Comment by Wouterz90** [comment]
It autocasts every 1 second, activating it seems weird with such a low cooldown.

**Comment by Fapboard** [comment]
That's supposed to be a passive component, while being able to have an active component to install another laser.

I dont really know yet how it's all puzzled together so far without seeing it.

I do hope that it works atleast in practice.

Looking forward to it.

- Regards, Whiteboard.

**Comment by Fapboard** [comment]
With a retarded turn of events, project has been scrapped.

Thank you for participating on this feat.

All components are to be removed regarding this topic.

- Regards, Whiteboard.

**Comment by Fapboard** [comment]
Also for thread to be closed.
