### ISSUE TITLE
Got griefed, can't be prevented ingame.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1347]
Just played a game where my whole team left until the griefer started targeting me with "helpful" abilities that teleports you to base, Sprout for movement halting and tether me into enemy fountain.

The game it'self doesn't offer a valid method of disabling help or it doesn't work.

Preferably be fixed before it becomes a thing.

- Regards, Whiteboard.

**Comment by DankBudd** [comment]
![cmeu](https://user-images.githubusercontent.com/18477016/35763628-530b3b78-087e-11e8-8a74-18fa6f51a3e6.PNG)

**Comment by Fapboard** [comment]
I tried that, despite it being toggled on or off, a team mate of mine kept casting "return to base spell" from chen, Sprout and tethered me to enemy fountain with Return.

Doesn't seem to work.

- Regards, Whiteboard.
