### ISSUE TITLE
issue after 7.08 update,and some item that should make consumeable

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1348]
1.after 7.08 update ,the game cannot start properly keep stuck at loading screen after choosing hero and skill,pls do fix it(the MAIN original version)
2,is the LOCAL versi of the game no more avaiable?
3.item that should be make consumable
-sange and yasha(SnY)
-Agahnim
-transquil boot
4.is dota imba item can be make avaiable in this game ,we got other custom games skills ,but so far few or less or no other custom items ,
5.Thank you for hard work and continue with the good job

**Comment by sandro8199** [comment]
the game crash in the second 00.00 when the horn sounds

**Comment by DankBudd** [comment]
i haven't encountered any crashing at the start of the game.

@jephat @sandro8199 can you give more details about your games.
what map were you playing on, what settings did you have enabled?

**Comment by jephat** [comment]
HMM I didnt enable setting ,all is default and i play on custom bot ,map also is default

**Comment by Acture** [comment]
My game crashes sometimes as well. all allowed map.

**Comment by DankBudd** [comment]
with default settings on the custom_bot map the console threw these errors. https://hastebin.com/zihadafixe.txt
just a bunch of 'Script not found' for abilities/perks/items
no actual vscript errors

2nd try i crashed just as the loading screen finished, post skill picking.
3rd try i crashed 1 or 2 minutes after the horn sounded.

**Comment by jephat** [comment]
ty for the test @DankBudd mine one is 2nd -crashed after loading screen finished,post skill picking
