### ISSUE TITLE
consumable items, hero talents.

### ISSUE THREAD

**Issue by Acture** [darklordabc/Legends-of-Dota-Redux#1349]
![image](https://user-images.githubusercontent.com/11632382/35765662-8c4c74ca-087d-11e8-9491-d10c0eef78e3.png)
So I think there is something wrong with consumable items, hero talents. 
1. they appear as debuffs. Like SF's talent was a green one, now it is red.
2. consumable items appear as buffs before I consumed it. When I unequip that item, the game just crashes, sometimes instantly, sometimes in a few seconds. I can confirm at least kaya, and vlad has the problem.
3. I have no idea about how to reproduce this. It just happens every game now.

**Comment by jephat** [comment]
hi Acture , you can get the game running without stuck at loading screen after choose hero and skills after the 7.08 update?

**Comment by Acture** [comment]
Yes I do.
