### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1350]
I am unable to start the game. It keeps crashing either at the load screen or when the countdown to send creeps reaches 00:00.

**Comment by XAgent1990** [comment]
It is crashing for me at game start, so after the drafting.

**Comment by darklordabc** [comment]
Covered in more detailed here: https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1355
