### ISSUE TITLE
Flesh Heap: Minion Damage + Spell Amp

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1351]
Flesh Heap minion damage did nothing to the bear, plauge wards and Mass Serpent Wards.

Also despite the tooltip displaying increasing numbers on plauge + mass, no increase in damage was made from the actual summoned unit.

I suggest the ability is taken down in the meantime while it gets tested/reworked to prevent simple missunderstandings leading to dead players ingame.

- Regards, Whiteboard.

**Comment by DankBudd** [comment]
the bonus damage popup only displays if the damage dealt is greater than 100.
but the bonus damage is still applied for any non hero unit that you own.

just fixed it not working with creep-hero units here 6808c58

**Comment by Fapboard** [comment]
So it works just like spell amp heap, it adds a number ontop of what you dealt (afterwards) that gets displayed.

If that's the case, it should be mentioned in the tooltips of these 2 abilities to reduce potentiall missunderstandings.
 - Heaps amp and minion damage.

Also on a side note, you could probably buff FH:MD, it's hard getting kills with summons.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
Another person told me that it was OP with plague wards. How do you know it's not working? You realise it doesn't show the bonus damage on the HUD?
