### ISSUE TITLE
Dota Imba Ability Issues

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1354]
Bane

- [ ] Units in nightmare don't get the "Baleful vision" aftereffect, I only tested on friendly teammates.
Creates a script error https://hastebin.com/oxakunamad.tex

- [ ] Fiends Grip sub ability "Terror Demons" does not summon the units and doesnt work, creates this error https://hastebin.com/yoxacuduhe.tex

Alchemist

- [ ] If you have Mammonite leveled and activated, it dissapears as soon as you buy an item 

- [ ] Got this script error when using Alch https://hastebin.com/ujehutisez.tex seems to happenw when you cast acid spray on an enemy hero

Shadow Fiend

- [ ] Modifier is missing text. This is the modifier that triggers when you all 3 razes connect and the cooldowns of the razes are refreshed. 
![image](https://user-images.githubusercontent.com/16277198/40150839-6868a2b6-59bf-11e8-8fe1-cfa6e3cdc12d.png)

- [ ] Necromastery is missing text on the modifier
![image](https://user-images.githubusercontent.com/16277198/40150903-d77b4c1c-59bf-11e8-8521-177871540d36.png)

- [ ] Soul Frenzy on the Ultimate does not work

Necros

- [ ] Reapers Syth does not apply the sickness

- [ ] Not sure E or W are working

Bounty Hunter

- [ ] Headhunter ability does not work.

Clinks

- [ ] Spooking mechanic on wind walk does not work.

Crystal Maiden

- [ ] Arcane Dynamo needs to be reworked, but first we need to add the custom ability version of Dynamo

Custom Hero

- [ ] Hurl Through Hell creates an error when the heroes return

- [ ] Royal Wrath does not do damage if players dont have Hellbot. Would be good if it could work without that ability.

**Comment by DankBudd** [comment]
pa crit gains 'Die Hard' stacks when any unit anywhere attacks

![20180206184818_1](https://user-images.githubusercontent.com/18477016/35891277-718fccf8-0b71-11e8-9e52-5b4d96a8505e.jpg)

**Comment by DankBudd** [comment]
abilities that are normally innates are unskillable. such as faceless voids TimeLord

**Comment by jephat** [comment]
hi first of all want to thank dev for the hotfix, game can now launch properly if i canhe my interface to "learn" page , but i wan to ask dev ,i just noticed  the import of dota imba abilities ,but when i choose single player ,hero ,neutral and custom skills in the settings i cant choose dota imba abilities skill ,if i choose dota imba abilities skills i cant choose the otheres ,is this normal or bug. ty and keep up the good work

**Comment by sheldonooi** [comment]
Troll Warlord's Battle Trance does not seem to be doing anything.

Dragon Knight's Dragon Charge makes the DK unable to move or attack or use items.

Juggernaut's Blade Dance has a sound issue where it keeps playing the Blade Spin sound once you level it up.

**Comment by darklordabc** [comment]
Thx I'll add these to the list at top. Can you also report if a hero set of abilities hasno issues to so I can tick it off

**Comment by jephat** [comment]
a couple of bug is spotted this few days after minor update (i duno  the reason is because of valve update or lodr update) first the page after u load finish and let u choose the  most popular build is missing,second the 1000 bonus gold award for rare skill pick is also missing third loda_cat abilities is missing  
-and also a couple of item that should make consumable
 1.Sange and yasha
2,vladimir offerings
3,aghanim scepter
4.transquil boot
thnx dev and continue the hardwork

**Comment by darklordabc** [comment]
Updated top comment, will continue to update as I test
