### ISSUE TITLE
Wrong scepter upgrades are shown in scepter description

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1359]
its just displaying the upgrades for the hero you chose, not for the skills you picked.

e.g if you pick sniper with no assassinate, and have say.. brain sap. the aghanim's description will only show assassinate

it used to display the upgrades for all the abilities you had. changed in the spring cleaning update.

**Comment by darklordabc** [comment]
I'm not sure what can be done about this. Anybody have suggestions?
