### ISSUE TITLE
making Local server

### ISSUE THREAD

**Issue by ghostlystrike** [darklordabc/Legends-of-Dota-Redux#1362]
Hi 
so this is my first try to make the local server of legend of dota, since i have really bad Ping...

i have done everything as it says , but i got this message every time:
[                        ]: ] dota_launch_custom_game <Redux> <custom>
[   Console              ]: Loading custom game "<Redux>" with map "<custom>"
[   HostStateManager     ]: CHostStateMgr::QueueNewRequest( Loading (<custom>), 2 )
[   EngineServiceManager ]: SwitchToLoop levelload requested:  id [2] addons [<Redux>]
[   Client               ]: CL:  IGameSystem::LoopDeactivateAllSystems
[   General              ]: WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 18.143
[   Client               ]: CL:  Disconnecting from server: #GameUI_Disconnect_LoopDeactivate
[   stringtables         ]: CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[   Server               ]: SV:  IGameSystem::LoopDeactivateAllSystems
[   Host                 ]: HO:  IGameSystem::LoopDeactivateAllSystems
[   Server               ]: SV:  Server shutting down: 55
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
[   Server               ]: SV:  Disconnect client 'TheKingOfNewbies' from server(1): NETWORK_DISCONNECT_SHUTDOWN
[   stringtables         ]: CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[   General              ]: WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 18.149
[ W EngineServiceManager ]: Can't CEngineServiceMgr::UpdateAddons restricting to to only test due to tools mode
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[   Client               ]: LoadingDisplay changed from NONE to LOADING (map="")
[   General              ]: CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 18.185
[   General              ]: CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 18.185
[   Client               ]: CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons (<Redux>)
[   EngineServiceManager ]: SwitchToLoop game requested:  id [2] addons [<Redux>]
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[   Server               ]: SV:  maxplayers set to 64
[   Networking           ]: Network socket 'server' opened on port 27015
[   General              ]: Initializing script VM...
[   General              ]: ...done
[   Server               ]: SV:  Executing listen server config file
[   General              ]: S:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
[   Server               ]: SV:  CGameRulesGameSystem::GameInit installed game rules
[ W SchemaSystemUtils    ]: WARNING: Schema upconversion occuring for large data (14kb): models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vphys
[   Server               ]: SV:  Spawn Server: <custom>
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[   WorldRenderer        ]: Failed to mount world vpk fike maps\<custom>.vpk, file could not be found.
[   Client               ]: CL:  Server disconnected: 64: #GameUI_ClientNoMap
[   Server               ]: SV:  Server shutting down: 64
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_loading -> ss_dead)
[   stringtables         ]: CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[   HostStateManager     ]: CHostStateMgr::QueueNewRequest( Idle (levelload), 3 )
[   HostStateManager     ]: Discarding pending request 'Loading (<custom>), 2'
[   EngineServiceManager ]: SwitchToLoop levelload requested:  id [3] addons []
[   Server               ]: SV:  CGameRulesGameSystem::GameShutdown uninstalled game rules
[   Server               ]: SV:  CGameRules::CGameRules destructed
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
[   Client               ]: LoadingDisplay changed from LOADING to NONE (map="")
[ W EngineServiceManager ]: Can't CEngineServiceMgr::UpdateAddons to multiple addons in tools mode, tools restricting to test
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[   Client               ]: LoadingDisplay changed from NONE to LOADING (map="")
[   HostStateManager     ]: Idle (levelload)
[   Client               ]: CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[   EngineServiceManager ]: SwitchToLoop game requested:  id [3] addons []
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[   Server               ]: SV:  maxplayers set to 1
[   General              ]: Initializing script VM...
[   General              ]: ...done
[   Server               ]: SV:  Spawn Server: <empty>
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
[   Client               ]: CL:  CWaitForGameServerStartupPrerequisite done waiting for server
[   Client               ]: CL:  CCreateGameClientJob creating client connection to 'loopback'
[   Client               ]: CL:  Connected to 'loopback'
[   Server               ]: SV:  Sending server info to client 'TheKingOfNewbies' at loopback
[   Server               ]: SV:  WriteInitialSpawnGroups sending 1 groups
[   Client               ]: Game: "Dota 2"
[   Client               ]: Map: "<empty>"
[   Client               ]: Players: 1 (0 bots) / 1 humans
[   Client               ]: Build: 7740 (revision 4363677)
[   Client               ]: Server Number: 3
[   SignonState          ]: CL:  CNetworkGameClient::ProcessServerInfo
[   General              ]: Initializing script VM...
[   General              ]: ...done
[   General              ]: ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000191 seconds
[   Client               ]: CL:  CGameClientConnectPrerequisite connection succeeded
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
[   Client               ]: LoadingDisplay changed from LOADING to NONE (map="<empty>")
[   Server               ]: SV:  IGameSystem::LoopActivateAllSystems
[   Host                 ]: HO:  IGameSystem::LoopActivateAllSystems
[   Server               ]: SV:  Game started
[   Client               ]: CL:  IGameSystem::LoopActivateAllSystems
[   General              ]: ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000172 seconds
[   SignonState          ]: CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
[                        ]: VConsole Rejecting Message: 'PHRA'
[   Server               ]: SV:  Sending full update to client TheKingOfNewbies (reason:  initial update)
[   Client               ]: CL:  Receiving uncompressed update from server
[   Client               ]: CL:  Signon traffic "client":  incoming 36.616 KB [5 pkts], outgoing 1.810 KB [17 pkts]

and the game says : unable to load map specifid by server

**Comment by darklordabc** [comment]
Are you subscribed to the mod? And what console command did you use

**Comment by DankBudd** [comment]
looks like the command he used was literally this`dota_launch_custom_game <Redux> <custom>`

@ghostlystrike make sure you subscribed to [redux](http://steamcommunity.com/sharedfiles/filedetails/?id=786348190&searchtext=redux) and use this command
`dota_launch_custom_game 786348190 custom_bot`

**Comment by ghostlystrike** [comment]
@darklordabc  Yes i am!  and this is the code : dota_launch_custom_game Redux Custom

@DankBudd i try that command too, same result


[                        ]: ] dota_launch_custom_game 786348190 custom_bot
[   Console              ]: Loading custom game "786348190" with map "custom_bot"
[   HostStateManager     ]: CHostStateMgr::QueueNewRequest( Loading (custom_bot), 2 )
[   EngineServiceManager ]: SwitchToLoop levelload requested:  id [2] addons [786348190]
[   Client               ]: CL:  IGameSystem::LoopDeactivateAllSystems
[   General              ]: WriteSteamRemoteStorageFileAsync( "scripts/control_groups.txt" ) -> at 18.676
[   Client               ]: CL:  Disconnecting from server: #GameUI_Disconnect_LoopDeactivate
[   stringtables         ]: CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[   Server               ]: SV:  IGameSystem::LoopDeactivateAllSystems
[   Host                 ]: HO:  IGameSystem::LoopDeactivateAllSystems
[   Server               ]: SV:  Server shutting down: 55
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
[   Server               ]: SV:  Disconnect client 'TheKingOfNewbies' from server(1): NETWORK_DISCONNECT_SHUTDOWN
[   stringtables         ]: CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[   General              ]: WriteSteamRemoteStorageFileAsync( "voice_ban.dt" ) -> at 18.682
[ W EngineServiceManager ]: Can't CEngineServiceMgr::UpdateAddons restricting to to only rezas2 due to tools mode
[ W Panorama             ]: ***** Parsing error on panorama\styles\popups\popup_settings.css(2027): Failed to set property value (property=color)(value=textColoredDarkColor)
[ W Panorama             ]: ***** Parsing error on panorama\styles\popups\popup_settings.css(2041): Failed to set property value (property=color)(value=textColoredMediumColor)
[ W Panorama             ]: ***** Parsing error on panorama\styles\popups\popup_settings.css(2107): Failed to set property value (property=color)(value=textColoredVeryBrightColor)
[   General              ]: **** Unable to localize '#loading' on panel 'buildLoadingIndicatorText'
[   General              ]: **** Unable to localize '#hintBloodSeeker' on panel ''
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[   Client               ]: LoadingDisplay changed from NONE to LOADING (map="")
[   General              ]: **** Unable to localize '#hintSinglePlayer' on panel ''
[   General              ]: CAsyncWriteInProgress::OnComplete( "scripts/control_groups.txt" ) -> Success at 61.447
[   General              ]: CAsyncWriteInProgress::OnComplete( "voice_ban.dt" ) -> Success at 61.447
[   Client               ]: CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons (786348190)
[   EngineServiceManager ]: SwitchToLoop game requested:  id [2] addons [786348190]
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[   Server               ]: SV:  maxplayers set to 64
[   Networking           ]: Network socket 'server' opened on port 27015
[   General              ]: Initializing script VM...
[   General              ]: ...done
[   Server               ]: SV:  Executing listen server config file
[   General              ]: S:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
[   Server               ]: SV:  CGameRulesGameSystem::GameInit installed game rules
[ W ResourceSystem       ]: Error loading resource file "panorama/images/custom_game/loading_screens/mdoojh5_jpg.vtex_c" (Error: ERROR_FILEOPEN)
[ W SchemaSystemUtils    ]: WARNING: Schema upconversion occuring for large data (14kb): models/creeps/neutral_creeps/n_creep_black_dragon/n_creep_black_dragon.vphys
[   Server               ]: SV:  Spawn Server: custom_bot
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[   WorldRenderer        ]: Failed to mount world vpk fike maps\custom_bot.vpk, file could not be found.
[   Server               ]: SV:  Connection to Steam servers successful.
[   Server               ]: SV:  ServerSteamID=[A:1:2475544587:9637] (90113385622786059).
[   SteamNetSockets      ]: Gameserver logged on to Steam, assigned SteamID [A:1:2475544587:9637]
[   Client               ]: CL:  Server disconnected: 64: #GameUI_ClientNoMap
[   Server               ]: SV:  Server shutting down: 64
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_loading -> ss_dead)
[   stringtables         ]: CNetworkStringTableContainer::RemoveAllTables:  removing 20 tables
[   HostStateManager     ]: CHostStateMgr::QueueNewRequest( Idle (levelload), 3 )
[   HostStateManager     ]: Discarding pending request 'Loading (custom_bot), 2'
[   EngineServiceManager ]: SwitchToLoop levelload requested:  id [3] addons []
[   Server               ]: SV:  CGameRulesGameSystem::GameShutdown uninstalled game rules
[   Server               ]: SV:  CGameRules::CGameRules destructed
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
[   Client               ]: LoadingDisplay changed from LOADING to NONE (map="")
[ W EngineServiceManager ]: Can't CEngineServiceMgr::UpdateAddons to multiple addons in tools mode, tools restricting to rezas2
[   General              ]: **** Unable to localize '#loading' on panel 'buildLoadingIndicatorText'
[   General              ]: **** Unable to localize '#hintUrsa' on panel ''
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_STATE_LOADING_SCREEN
[   Client               ]: LoadingDisplay changed from NONE to LOADING (map="")
[   HostStateManager     ]: Idle (levelload)
[   Client               ]: CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
[   EngineServiceManager ]: SwitchToLoop game requested:  id [3] addons []
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
[   Server               ]: SV:  maxplayers set to 1
[   General              ]: Initializing script VM...
[   General              ]: ...done
[ W ResourceSystem       ]: Error loading resource file "panorama/images/custom_game/loading_screens/1uuo1ne_jpg.vtex_c" (Error: ERROR_FILEOPEN)
[   Server               ]: SV:  Spawn Server: <empty>
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
[   Server               ]: CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
[   Client               ]: CL:  CWaitForGameServerStartupPrerequisite done waiting for server
[   Client               ]: CL:  CCreateGameClientJob creating client connection to 'loopback'
[   Client               ]: CL:  Connected to 'loopback'
[   Server               ]: SV:  Sending server info to client 'TheKingOfNewbies' at loopback
[   Server               ]: SV:  WriteInitialSpawnGroups sending 1 groups
[   Client               ]: Game: "Dota 2"
[   Client               ]: Map: "<empty>"
[   Client               ]: Players: 1 (0 bots) / 1 humans
[   Client               ]: Build: 7740 (revision 4363677)
[   Client               ]: Server Number: 3
[   SignonState          ]: CL:  CNetworkGameClient::ProcessServerInfo
[   General              ]: Initializing script VM...
[   General              ]: ...done
[   General              ]: ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000197 seconds
[   Client               ]: CL:  CGameClientConnectPrerequisite connection succeeded
[   General              ]: ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_STATE_DASHBOARD
[   Client               ]: LoadingDisplay changed from LOADING to NONE (map="<empty>")
[   Server               ]: SV:  IGameSystem::LoopActivateAllSystems
[   Host                 ]: HO:  IGameSystem::LoopActivateAllSystems
[   Server               ]: SV:  Game started
[   Client               ]: CL:  IGameSystem::LoopActivateAllSystems
[   General              ]: ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000166 seconds
[   SignonState          ]: CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
[                        ]: VConsole Rejecting Message: 'PHRA'
[   Server               ]: SV:  Sending full update to client TheKingOfNewbies (reason:  initial update)
[   Client               ]: CL:  Receiving uncompressed update from server
[   Client               ]: CL:  Signon traffic "client":  incoming 36.612 KB [5 pkts], outgoing 1.855 KB [18 pkts]

**Comment by DankBudd** [comment]
are you running dota in tools mode? that command i gave you was not for tools mode.

**Comment by ghostlystrike** [comment]
@DankBudd i tried with and without tools mode, same issue 

but the way i get this message everytime pop up to middle of screen
 W Panorama ]: ***** Parsing error on panorama\styles\popups\popup_settings.css(2027): Failed to set property value (property=color)(value=textColoredDarkColor)
[ W Panorama ]: ***** Parsing error on panorama\styles\popups\popup_settings.css(2041): Failed to set property value (property=color)(value=textColoredMediumColor)
[ W Panorama ]: ***** Parsing error on panorama\styles\popups\popup_settings.css(2107): Failed to set property value (property=color)(value=textColoredVeryBrightColor)

**Comment by DankBudd** [comment]
i dont know why it wouldnt be working.
this error implies that you either dont have all the files downloaded, or you are trying to load it in tools mode from the wrong addon.
> [ WorldRenderer ]: Failed to mount world vpk fike maps\custom_bot.vpk, file could not be found.

**Comment by ghostlystrike** [comment]
so i'm gonna give up...

**Comment by darklordabc** [comment]
Explore to this folder \Steam\steamapps\workshop\content\570 and see if you have the folder "786348190"

**Comment by ghostlystrike** [comment]
@darklordabc  i do have that folder and there are 2 files in it, one .vpk file with same name as folder and a text file named Publish_data
may i ask you to help me through TeamViewer? if that ok with you

**Comment by darklordabc** [comment]
Yes

**Comment by darklordabc** [comment]
Go to the discord channel

**Comment by darklordabc** [comment]
https://discord.gg/f3RqkU

**Comment by darklordabc** [comment]
Turns out the guy was running it in tools mode whereas he should of run it in just normal dota 2.
