### ISSUE TITLE
Map boundry abuse.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1366]
It's possible to outside map boundries.

Highly abuse with efficent ranges of attack and casting.

This ought to be corrected.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
I'm not sure what to do about this, I would need more info or some examples.

**Comment by DankBudd** [comment]
you can get outside the map with any forced movement ability/item or blinks.
it doesnt work around the fountain, but anywhere else it does.

the solution would probably be to just put clip entities around the edge of the map
