### ISSUE TITLE
Death Ward is a mess.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1367]
Death Ward fails to interact with properly with rest of LoDr.

Neither Flesh heap: Minion Damage or Flesh Heap: Spell Amp increases the damage of this ability as far as I can tell after trying both.

Death Ward dies to a custom ability: "Holy Wrath" after attacking, procking it's effect and being struck by a bolt for 2x the aura host's Int. Ridicilous.

Death Ward is paused/stunned by Chronosphere (may be an intended interaction and/or be the case in regular dota as well).

This ought to be looked into and corrected.

- Regards, Whiteboard.

**Comment by DankBudd** [comment]
all intended by volvo except it dying to holy wrath.

**Comment by Fapboard** [comment]
Well, Flesh heaps outside the pudge's one doesn't exist outside lodr, therefore they do not work on Death Ward.

It just puts the whole thing on a forked road of the question: "Which is it?".
 - It's neither a spell nor a summon.

And one of them ought to work on Death Ward.

Also worth mentioning that Holy Wrath shouldn't work on the ward either.

 - Regards, Whiteboard.

**Comment by DankBudd** [comment]
the custom flesh heaps use valves built in properties for everything from bonus agility/int to spell amp and cooldown reduction.
they are no different than if valve implemented a spell amp ability for witch doctor, it wouldnt work for the ward.

the death **ward** is a ward. there should be no question about what works with it.
should kaya increase the spell damage of your _observer wards_?

and i already agreed that holy wrath killing it is a bug.

**Comment by Fapboard** [comment]
Although the tooltips display an increase in damage as you gain spell amp, even from Dota means.

And ward is just a unit type, you got other attacking wards that benefits from Flesh Heap: Minion Damage.

But since Death Ward doesn't, the logical choice would be spell amp heap instead.

However since neither applies to this ability comes the next logical conclusion, that dev's have forgotten to apply either of those heaps onto Death Ward manually.

Considering how (previously mentioned) other wards: Plauge and Mass Serpent Wards benefits from Heap: Minion Damage, Death Ward ought to as well.

Also getting sassy in responses is not appreciated.

- Regards, Whiteboard.

**Comment by DankBudd** [comment]
it does work with flesh heap minion damage. just tested it.

spell amp doesnt work because

- the damage source is the ward itself, not the caster.
- the ward physically attacks, its not spell damage (-armor effects on the target increase its damage)

**Comment by DankBudd** [comment]
204c4c9

**Comment by Fapboard** [comment]
I also double-checked myself, Heap Minion Damage does work on Death Ward.

I simply never recognized any numbers while using that combination before and assumed it didn't work as I saw no diffrence in damage.

On a side note, Heap: MD bugs out after re-selecting your hero with ingame builder.

- Regards, Whiteboard.
