### ISSUE TITLE
Vengeful Perk / Illusions in general are a mess.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1370]
Spawns a clone of original Vengeful Spirit regardless of what you picked that game with unlearned abilities.

Alongside alot of other illusions, they don't behave properly, sometimes with the same pattern as the previously mentioned.

Also mentionworthy that they do not inherit the stats of the host, only a prefix from the current level of host.

And alot of items are not applying in general and while consumed - to illusions (which is a big shame).

This ought to be looked into and corrected accordingly.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
This is kind of unclear. What you are saying is "Vengeful Spirit always spawns her afterdeath clone if hero perks is enabled", I dont know why she does spawn that, we'll have to look into it.
