### ISSUE TITLE
Passive triggers on sub-abilities.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1371]
Static Field and Essence Aura has been confirmed to trigger these sub-abilities with each seperate combinations:

Static Field + Reality (Sub ability from Haunt).
Essence Aura + Shadow Posion Release (Sub ability from Shadow Posion).

While granting 100% benefits while the abilities triggering them having no cooldown or manacost.

This ought to be further looked into for similuar cases and corrected accordingly.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
Haunt and Shadow Poison is now troll combo with Static Field
Shadow Poison Relesae now longer triggers Essence Aura, if you know of any more combinations, let us know in the discord. 
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/7f25623e613aeed25c8a46ffa9f74dfe243a6f4e
