### ISSUE TITLE
Tether is a mess.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1373]
Has a 60 second cooldown instead of it's intended 12s.

It also goes on it's 60s cooldown whenever an item or ability is used by the user.
 - Regardless of it's remaining cooldown, it will snap back to 60s remaining.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
Where you using arcane symbsious?

**Comment by Fapboard** [comment]
I'd prefer to discuss this with another developer.

Don't bother replying to my posts Darklord.

- Regards, Whiteboard.

**Comment by OtsoTurpeinen** [comment]
Effect is intentional with arcane symbiosis (for balance reasons). Issue closed.
