### ISSUE TITLE
Ability Bug

### ISSUE THREAD

**Issue by LeoVeracruse** [darklordabc/Legends-of-Dota-Redux#1376]
I just attempted to play a Treent Protector build however, when grabbing both "eye of the forest" and "Overgrowth" (sorry if i spelled those wrong) the eye of the forest did NOT cast overgrowth when overgrowth was cast.

**Comment by darklordabc** [comment]
I tested and the Eyes of the forest ability requires the player to have scepter for it to cast roots. I don't think this is a bug, but I have added extra info to the warning on the ability so its clearer to users.
![image](https://user-images.githubusercontent.com/16277198/36393907-cbc22ccc-1605-11e8-915e-b789344ec82e.png)
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/f949c087e2a6477dd5a7ad4fbc35142095ec5bba
