### ISSUE TITLE
Swashbucke Redux

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1377]
The current "Swashbuckle" interaction with attack modifiers (arcane orb, essence shift, fury swipes, desolate) can get a bit OP, not OP enough to warrant making them troll combos or single player abilities, but OP enough to warrant creation of "Swashbuckle Redux."

The difference between "Swashbuckle" and  "Swashbuckle Redux" would be that the attacks on "Swashbuckle Redux" only have a 50% chance of applying attack modifiers, rather  than the current state of garanteed application on each hit.

**Comment by darklordabc** [comment]
This would require recreating the ability. @Yahnich would you be interested in making a redux version of the ability?

**Comment by ForbiddenFruitPOD** [comment]
What about making swashbuckle redux only do 3 attacks instead of 4? Adjust the damage so its still the same overall from the ability itself. The only issue is the near instant application of attack modifiers 4 times. If it was 3 times instead, that would serve the same purpose. Or, you can even just leave it at 3 attacks and no other changes. People don't pick swashbuckle for its damage. People pick it for its mobility and its application of attack modifiers.
