### ISSUE TITLE
Re-add Missing Text for some abiliites

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1379]
It appears a lot of text has been deleted for some custom abilities. Check all the customs and see which are missing texts and then search the git to find older versions of the addon English file and readd them where necessary. 
![image](https://user-images.githubusercontent.com/16277198/36396584-0548e078-1613-11e8-8124-f16307b876fd.png)

**Comment by DankBudd** [comment]
i think it was just cherubs abilities: fa6744de1ed01a002dce070df67c06304fc0cab9
