### ISSUE TITLE
Bots don't spawn on some conditions (unconfirmed)

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1381]
"Bots don't spawn in besides 1 of them. When enemy team has 10 bots and you have more than 1 human on a team."

**Comment by jephat** [comment]
hmm this bug i can confirmed happen long times ago, i think if not mistaken 2 months ago i try to play with 2 friend againat 10 bots , they simply wont spawn,we try couple of times and is the same
