### ISSUE TITLE
i encounter a lot of unexplained bug after 23 feb update

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1385]
that is 3 unexplained bug i encounter so far
most of the bug is unexplainable such as 
-bot wont die (immortal or undieable)despite taking massive damage(the hp drop and instant coming back)
-random survival encounter a lot unnamed bug such as survival attack range dun give attack range etc
-bot who take reincarnation ,the reincarnation keep trigger non-stop

this bug i experienced in custom_bot game i unsure whether it happen to players

**Comment by DankBudd** [comment]
> bot who take reincarnation ,the reincarnation keep trigger non-stop

did you have wtf mode enabled?

**Comment by jephat** [comment]
no i did not use wf all is normal( i build the skill impetus,survival cast range,survival attack  range,flesh heap cast range and mana regen ) ,however when i restart game in classic mode ,the bug is gone, i not sure whether the bug happen only in custom_bot mode or happen randomly, this morning when i build a skill set aound survival of cooldown op in custom_bot mode i notice the suirvival didn't work again,start in classic worked again

**Comment by darklordabc** [comment]
I have experienced the bots with reincarnation with no cooldown, but when I tried to just replicate the problem, I couldn't, do you have any more info on how you can trigger it?

**Comment by jephat** [comment]
hmm i think the condition is when bot or i have random survival of fittest skill ,it will trigger,because today i play with no random survival skill ,it did not happen

**Comment by OtsoTurpeinen** [comment]
Could this be the talent for reincarnation? I've had that randomly show up. Possibly some interaction with modifier duration change and that?
