### ISSUE TITLE
Help Wanted LVL death

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1388]
Hallo I am trying to recreate old doom LVL death spell but i have a problem i dont know how to set up to check maximal level obtainable in game can i add some kind of checker so that it checks max lvl that i configure before the picking phase? Right now I have set it up for lvl 100 but i want it to be better. Please help  me.
Here is the LUA script:
[lvl_death.zip](https://github.com/darklordabc/Legends-of-Dota-Redux/files/1755865/lvl_death.zip)

**Comment by DankBudd** [comment]
OptionManager:GetOption('maxHeroLevel')

**Comment by edotenseilove** [comment]
Thanks I will try it

**Comment by edotenseilove** [comment]
Thanks a lot it is working fine
