### ISSUE TITLE
Survival of the Fittest Redux

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1389]
Several builds based around survival of the fittest skills are too strong. Not OP enough to make them troll combos, but OP enough that survival of the fittest needs an upper limit so they don't become god tier OP.

My recommendation is as follows:
-Current survival of the fittest skills be tagged as OP abilities
-Creation of redux version of each survival of the fittest skills
-Only difference between the regular (OP) version and redux version is that the redux version has an upper limit.

The upper limit should enable the survival (redux) skill to provide a bonus that is still much greater than comparable skills (double is reasonable).

For example, survival of the fittest - strength/agility/intelligence (redux) would have upper limits of 160, as this is double marksmanship -strength/agility/intelligence or brawler - strength/agility/intelligence.

**Comment by darklordabc** [comment]
@DrTeaSpoon we already have limits for some of the survivals, reckon we apply it to all of them?
