### ISSUE TITLE
Bots are getting an extra blank ability

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1391]
![image](https://user-images.githubusercontent.com/16277198/36654663-54056eee-1b12-11e8-860e-dceade67eabd.png)

**Comment by DankBudd** [comment]
thats an ability that every hero has, it just fills the empty ability indexes.

as its name suggests, its supposed to be hidden.
so its likely it had SetHidden(false) called on it somewhere.
