### ISSUE TITLE
nerf attribute perks. (status resistance and magic resistance)

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1392]
### currently you get the following 'perks' for every point of your primary attribute
https://dota2.gamepedia.com/Attributes
- INT - 0.15% magic resistance
- STR - 0.15% status resistance
- AGI - 0.06% movement speed

open angel arena halves the values of the str and int perks, because with high stats they are just broken. overpowered.

its not hard to reach 100% status or magic resistance with a stat build in redux.

i could give some examples for how much you get for X amount of a stat
or make a better argument for why this should be done.
but its late and ill probably edit this later.

**Comment by Wouterz90** [comment]
I think the best solution to things like these is by making the reductions not stack with each other, like some flesh heaps do.

For 100 int that would mean:  
- Old: 15% (0.15*100)
- New: 13.9% (1-(0.9985 ^100))

For 200 int that would mean:  
- Old: 30% (0.15*200)
- New: 25.9% (1-(0.9985 ^200))

For 300 int that would mean:  
- Old: 45% (0.15*300)
- New: 36.2% (1-(0.9985 ^300))

In my opinion that is much better, especially for status resistance. This requires a total rework of the system though.
