### ISSUE TITLE
the souls only show number of souls collected

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1393]
hi today update i noticed a bug the souls only show numner of souls collected, but does not show it in stats and attribute panel (for example : souls evasion still show 0% evasion despite collecting 300 of souls),but although it show 0%, the evasion still did work ,i think it just stat panel need some correction for it to registered proper stats

**Comment by darklordabc** [comment]
@DrTeaSpoon have you encounted this before?

**Comment by OtsoTurpeinen** [comment]
I think this issue has been fixed. All of the souls abilities should now Calculate Stat Bonuses. (which would update lot of local values) Can't test it right now.

**Comment by darklordabc** [comment]
Assuming this is fixed
