### ISSUE TITLE
New ability issue

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1399]
Hallo I have created the ability but i dont know how to add it to the pull requests I have watched the tutorials but i could not do it do i have to download some program to create pull requests?

**Comment by DankBudd** [comment]
fork the repository, commit your changes there and then open a pull request to merge your fork into the main branch.

https://help.github.com/articles/creating-a-pull-request/

**Comment by edotenseilove** [comment]
Thank you I will try it
