### ISSUE TITLE
Suggestion: some of the item that should be make consumable

### ISSUE THREAD

**Issue by jephat** [darklordabc/Legends-of-Dota-Redux#1401]
1.Sange Yasha
2.Transquil boot
3.Aghanim scepter

**Comment by darklordabc** [comment]
I disagree with Aghanim, because there is already an ability that gives aghs, if aghs were consumable it would make that ability redudant.

**Comment by Techmind** [comment]
Maybe change all items to be consumable with price < then something (~2.5k ) ? 

Cause consumable heart\skadi\mkb\deso is way better than single octarine for casters.
