### ISSUE TITLE
Tempest double summons the double with default abilites

### ISSUE THREAD

**Issue by Satsaa** [darklordabc/Legends-of-Dota-Redux#1403]
The "new"(transparent bg and you can spawn early) picking screen has this bug but it doesnt seem to be in solo lobbies/with old pick screen. Also the doubles levels are fucked up.

**Comment by darklordabc** [comment]
I tested this, but my tempest double had the right abilities? any more info on how to reproduce the bug?

**Comment by Satsaa** [comment]
I can only replicate it in a multiplayer lobby because it has the new picking screen where you can join the game early without waiting for others to pick their skills. 
![a2bec3db27af9aa62db226afedd8e409](https://user-images.githubusercontent.com/32210043/37878626-ac20329a-3074-11e8-9c9a-4db38c111c0b.jpg)
