### ISSUE TITLE
Mana Loss Reduction Talent (CM) does not appear to work (Needs confirmation)

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1407]
I just tested the "+14% manacost/manaloss reduction aura" talent from CM, but spells still cost the same amount of mana. I tested with CM and a different hero. Prehaps the talent is connected to arcane aura? Can  anyone confirm?

**Comment by DankBudd** [comment]
yes its connected to the skill, ive used it before with cm passive and it worked.

**Comment by darklordabc** [comment]
Yes, you were right, its connected now.
