### ISSUE TITLE
Counter Helix

### ISSUE THREAD

**Issue by geoawk** [darklordabc/Legends-of-Dota-Redux#1412]
Counter Helix works with illusions in the base game but does not in the mod.
Axe has a "counter helix procs with attack" at level 20 talent. Works fully with all illusions in game. Does not work with mod. 

Fixing that would be cool. Was it intentionally removed considering the base game has it?

**Comment by darklordabc** [comment]
It was not intentionally removed, I dont know why its not working.

**Comment by DankBudd** [comment]
does it work if you play as axe? is might be tied to his hero model, like faceless void being able to walk in chrono.

**Comment by geoawk** [comment]
I have tested this with on other characters as well and it does not work.

**Comment by geoawk** [comment]
to be clear, it doesn't work on axe or any other hero

**Comment by darklordabc** [comment]
Not sure why it doesnt work with illusions, but I've added a warning to the ability for now.
