### ISSUE TITLE
Do something about this combo

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1415]
https://www.youtube.com/watch?v=eZBuUCdDVI0&feature=youtu.be

**Comment by OtsoTurpeinen** [comment]
There is somethings to analyze here:
1) Global Ultimate + Multicast
2) Flat 15 second cooldown reduction (on 20 second cooldown global ultimate)
3) Spell Amp % from Int.
4) Total damage amp of 28%(400 int) + 10% (Kaya) + 40% (Blood Rage) = 78%

**Comment by Techmind** [comment]
Just make blademail ignore fountain's 100% resists. Will wreck that combo hard with 2k gold item.

**Comment by Techmind** [comment]
Once again souls spells/flesh heap are unbalanced because they allow you to snowball. Also item like blademail-2(saw it somewhere maybe "dota imba") which returns PURe dmg will fuck any "attack from fountain  build".

**Comment by OtsoTurpeinen** [comment]
the souls already have soft limit of 250 at max level. so it only provides in this case max of 187.5 int.

**Comment by darklordabc** [comment]
I'm feeling that the worst part of this combo is the wraith of nature + multicast. Even if you got rid of all the other abilities, wouldn't that combo still be pretty devastating?

**Comment by OtsoTurpeinen** [comment]
That blademail might be good idea. Would work against other fountain wankery as well. Or put fountain bonus on pause when hero deals damage. (like tranquil boots but lower cooldown)

**Comment by darklordabc** [comment]
Is blademail fix enough? One, not all players would know thats the counter, two, they would probably only buy blademail after the enemy hero has made a rampage or two, and three, the enemy casting the spell could counter the blademail by for example, having lots of HP or using cyclone staff.

**Comment by OtsoTurpeinen** [comment]
No Multicast on Ultimates?

**Comment by Techmind** [comment]
Yeah, eul/bkb sort of counters blademail in that case, good point.

**Comment by Techmind** [comment]
1) Can we have fountain debuff, so y cant dmg heroes unless they are on your HG ? 
To counter fountain spamming.
So at least hero is vulnerable.

2) Actually only natures wrath + that passive (see heroes on creep kill) is sort-of-broken, cause getting 250+ souls is fast with nature`s wrath, but 250 souls is same as casting bloodlust in terms of magick dmg % increase, so not that broken. 
And flesh heap spell amp or survival of fittest spell amp can accomplish same stuff. 

Even without multicast you can reach 1-shot threshold after getting 10-20 stacks of flesh heap and any global spell will become one shot (sunstrike/zeus ulty). Dunno maybe this is legit combo, the video is minute 23, that guy died 1 time only, by that time many heroes who don't have counters can snowball.
