### ISSUE TITLE
Alch cant aghs himself.

### ISSUE THREAD

**Issue by Techmind** [darklordabc/Legends-of-Dota-Redux#1419]
Was it deleted ? Cause the item still have click-to-use functionality, just does not do anything. Maybe should be part of his perk (+16 gold from creep is meh vs "mks/pangos/svens" passive for example) ?

**Comment by Fertsa** [comment]
Alchs aghs ability is an ability you need to intentionally take at the start of the game, all of the aghs abilities are.

**Comment by DankBudd** [comment]
> all of the aghs abilities are

all of the **_innate_** abilities*

**Comment by darklordabc** [comment]
Yes, it was manually disabled so that he couldn't cast it, in general, we try to disable hero model specific bonuses.
