### ISSUE TITLE
Flesh heap cooldown weird numbers.

### ISSUE THREAD

**Issue by Techmind** [darklordabc/Legends-of-Dota-Redux#1424]
Got 115 flesh heaps in bot match.
8 sec timewalk became1.92 seconds CD. So ~ 75% cooldown reduction.
https://imgur.com/a/B5jal

Getting even 20 flesh heaps in any < 30 minutes match is hard. Getting 100+ and getting for its just "octarine + windrunner perk + rearm" redux combo is sort of useless.

**Comment by OtsoTurpeinen** [comment]
How is this an issue?

**Comment by Techmind** [comment]
I mean description says 1% per flesh heap, and it is actually less.

**Comment by DankBudd** [comment]
flesh heap cooldown stacks diminishingly with itself.
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/78e3c58a8ce1997b8192af18b0e266c7e57b9fa4/src/game/scripts/vscripts/abilities/pudge_flesh_heap_cooldown_reduction.lua#L185

100 stacks at max level would give you 63% CDR

**Comment by darklordabc** [comment]
So this isnt an issue? Or should we improve the text of the ability to be more informative?

**Comment by Techmind** [comment]
I would like the improved text (but i am pretty sure i am like in 1% of players who tries to do something with flesh heap cooldown anyway).

For now flesh heap cooldown is outclassed by any other cooldown ability, nobody would pick it if 25 stacks != 25 % cdr (and actually less), plz make it clear that it actually not that good.

**Comment by darklordabc** [comment]
I'll add the text "Stacks diminishingly with itself." You the fleshheaps it applies to, @OtsoTurpeinen could you tell me which flesh heaps this applies to?

**Comment by OtsoTurpeinen** [comment]
cooldown
evasion
magic resist

**Comment by darklordabc** [comment]
Does this apply to all 3 types of abilities or just heaps?
