### ISSUE TITLE
Question: why Shadow Dance is included in the invisibility ban?

### ISSUE THREAD

**Issue by leviathan13** [darklordabc/Legends-of-Dota-Redux#1425]
Shadow Dance hide the caster but is not a form of invisibility, therefore I think it shouldn't be banned by the "no invisibility" option.

**Comment by OtsoTurpeinen** [comment]
I agree. Shadow Dance should not be included.

**Comment by leviathan13** [comment]
Well the [Dota wiki](https://dota2.gamepedia.com/Slark#Shadow_Dance) states it is a form of invisibility after all, so I guess that's the reason. Although it's not a standard form of invisibility anymore (a while ago you could reveal Slark with true sight, now you cannot).

**Comment by DankBudd** [comment]
yeah. strictly speaking it **DOES** give invisibility when activated. but its for a very short period and you are immune to all forms of the base games truesight.
(a custom ability that gives 'ULTRA' level true sight would reveal you e.g. redux's custom thirst if it malfunctions)

i too think it should not be counted as an invisibility skill

**Comment by darklordabc** [comment]
I agree too https://github.com/darklordabc/Legends-of-Dota-Redux/commit/760ab1dcd6e42f09c5868c1a9eee64a3083d0200

**Comment by leviathan13** [comment]
Was the changed committed? Because Shadow Dance is still banned by the "no invisibility" option.

**Comment by OtsoTurpeinen** [comment]
Update is not live on steam yet.
