### ISSUE TITLE
i have Crash game just in this mod.

### ISSUE THREAD

**Issue by darkness32** [darklordabc/Legends-of-Dota-Redux#1427]
hi bro. this mod is so good . but we have a big Problem. we can play just in one Server. i use your code in console.  i can use this and play  But nothing changes.And actually worse. so plz add more server like  Russia-Western Europe-Eastern Europe. So please give more server. i have a higt computer.I have a good internet and a strong system. So it's not a problem for me.

**Comment by darklordabc** [comment]
We cannot add any servers, that is all on valves end. What type of issues are you encountering? When does it crash?

**Comment by darkness32** [comment]
i have powerfull pc. but every time i use double creep or more tower and
... i have crash. i can play any mod with no crash but in all this mod i
have good ping. in you mod server i dont have good ping . so game well
be disconnect
to. i play single mod and i use custome bo and i use you code to but in
this time i have crash and low speed game to . i love you mod sooooooo
much. so Please fix it. and soryy for my en.

**Comment by darklordabc** [comment]
If you dont use double creeps, is it much better?

**Comment by darkness32** [comment]
yes

**Comment by darkness32** [comment]
i think every time i use more tower or more creep and .... i have bad frame.
and i use you code for oflline map. but when i use this code i have more
bad frame and low speed game. i am a pro gamer. i play 15 yers. i Installation
any software for better game play. like last v driver- Directx and much
more.... . so plz do somting for code.

**Comment by darkness32** [comment]
my dear bro thanks sooooooooo much. now i have a good game play. everything
is good. thanks so much.:-)

**Comment by darklordabc** [comment]
What fixed it?
