### ISSUE TITLE
Suggestion: new cheat for single player mode

### ISSUE THREAD

**Issue by leviathan13** [darklordabc/Legends-of-Dota-Redux#1433]
Add a cheat that grants true sight for the player in the cheat command menù. Useful for dealing with bots with invisibility.

**Comment by darklordabc** [comment]
Good point, I've added a true sight check that gives you the true sight modifier https://github.com/darklordabc/Legends-of-Dota-Redux/commit/7878e6edaa804cea5a6c7813e9dc9d573db9706a
![image](https://user-images.githubusercontent.com/16277198/40040263-e6066a46-585c-11e8-97da-52a367fe2298.png)
Let us know if you think of other useful cheats
