### ISSUE TITLE
Bug: parsing errors

### ISSUE THREAD

**Issue by leviathan13** [darklordabc/Legends-of-Dota-Redux#1436]
Every time a lobby starts, I get three parsing errors popup that I have to dismiss in order to start the game:

-  ***** Parsing error on panorama\styles\popups\popup_settings.css(2027): Failed to set property value (property=color)(value=textColoredDarkColor)
- ***** Parsing error on panorama\styles\popups\popup_settings.css(2041): Failed to set property value (property=color)(value=textColoredMediumColor)
- ***** Parsing error on panorama\styles\popups\popup_settings.css(2107): Failed to set property value (property=color)(value=textColoredVeryBrightColor)

This seems similar to #368 .

**Comment by darklordabc** [comment]
You mean when you load the game in toolsmode right?

**Comment by leviathan13** [comment]
I don't know what toolsmode is, sorry.

**Comment by darklordabc** [comment]
How do you play the game? Through the normal way through dota 2 arcade tab? Or some other way?

**Comment by leviathan13** [comment]
I search a lobby through the lobby list in the arcade tab. By the way, the popups increased, now I get like 5 of them...

**Comment by darklordabc** [comment]
Do you have any special settings or launch options? I never get these popups when I start through the arcade.
