### ISSUE TITLE
Bug:  Glaives of Wisdom with Death Prophet

### ISSUE THREAD

**Issue by leviathan13** [darklordabc/Legends-of-Dota-Redux#1437]
The lvl25 talent "+1s glaives silence" add a 1s silence on hit with Glaives of Wisdom, but Death Prophet's perk doesn't work with that (glaives don't mute enemies).

**Comment by DankBudd** [comment]
probably missing the 'silence' flag
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/909bb0d15f393d31f7d29250b05a2c2bba59892b/src/game/scripts/vscripts/abilities/hero_perks/npc_dota_hero_death_prophet_perk.lua#L68

**Comment by darklordabc** [comment]
@Wouterz90 any idea how to fix this? You made the DP perk.

**Comment by Wouterz90** [comment]
Most likely it doesn't count as an ability

**Comment by Wouterz90** [comment]
Should be fixed, let me know if I messed up something!

**Comment by ForbiddenFruitPOD** [comment]
The perk still doesn't work with glaives of wisdom talent

**Comment by Wouterz90** [comment]
I think I know what causes it, might be a bit annoying to fix it though. But I'll do it soon.

**Comment by Wouterz90** [comment]
I have something that should work in theory, will test it tomorrow.

**Comment by Wouterz90** [comment]
I'm sorry I forgot about this. The issue is that when there is no ability attached to the modifier like in this case, it won't trigger our system. Changing that would require a lot of work and opens us op to new bugs. I don't think that's the path we will  be taking. I'm sorry.
