### ISSUE TITLE
Venge respawning with lvl 1 and default venge build at faster respawn (and being repeatedly farmed for 4k+ gold per kill)

### ISSUE THREAD

**Issue by Techmind** [darklordabc/Legends-of-Dota-Redux#1442]
Subj, saw this happen 1-2 times at least.

**Comment by darklordabc** [comment]
Is this reproducible?

**Comment by 1ran-wang** [comment]
3 times in my games.

**Comment by Wouterz90** [comment]
Had trouble reproducing this, will test again tonight but maybe it has been fixed by itself??

**Comment by Wouterz90** [comment]
Can't find it, lets reopen this when we find it agian.
