### ISSUE TITLE
Custom attribut bonuses ability

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1443]
Hallo I started creating custom ability which improves bonuses that i get from stats but i dont know what modifier property i should use to increase  Health regen amplification. I have found health regen and health regen based on the affected object's maximum health but i dont know how to create something that increase Health regen amplification

please help

**Comment by darklordabc** [comment]
There is already an ability like that in redux yeah? The stat bonus ability.

**Comment by edotenseilove** [comment]
it is like tenebris_mortal_coil_modifier from next generation that increase attack speed for every point of agility and i want to expand it by creating ability that increase all things conected with increasing atributes so regen armor speed magic resistance spell amplification and so on but i dont know the exact modifier properties to do so like Health regen amplification  of course that  only things that are conected with agility will be affected by current agility and that will be for all atributes

**Comment by DankBudd** [comment]
http://docs.moddota.com/lua_server_enums/#modifierfunction

probably this.
```
GetModifierHPRegenAmplify_Percentage
MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE
```

that sounds like it could easily be overpowered though, would make any stat focused build very strong.

**Comment by edotenseilove** [comment]
thanks a lot of course i am going to test it and change the values to not be so overpowered and i am going to split this ability into 3 too to increase only str or agility or int bonuses than i will create an OP ability where everything will be conected and if i can make it i am going to add option to increase atk damage depending on the main attribute

**Comment by edotenseilove** [comment]
it works thanks a lot and i think that i choose the right values so it is not so overpowered now
