### ISSUE TITLE
Some Single Player Skills can still be selected

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1454]
Even if single player skills are disabled, some of them can still be selected. They are all the super OP souls abilities, as well as Arcane Art OP.

**Comment by darklordabc** [comment]
Thanks for pointing this out, its been fixed and uploaded. https://github.com/darklordabc/Legends-of-Dota-Redux/commit/0282a928e15378a4d1974b1919c877441463e6c6
