### ISSUE TITLE
Patreon Link ingame

### ISSUE THREAD

**Issue by Whitebored** [darklordabc/Legends-of-Dota-Redux#1459]
I'd prefer if you put it somewhere else in the game where my immediate reaction < isn't > to remove it instantly.

It blocks out some of the interface at a very crucial area where youre doing your shopping.

And I can imagine clicking that thing is gonna tab down the game and open your default browser with a web adress pasted into it.

It needs to be placed else where on the screen, perhaps to the top left corner where the hero portrait is on the ocation you open the shop menu.

Otherwise this is gonna grief alot of players unescessarily, which probably isn't the type of negative reaction youre looking for when using this ingame advertisment.

Is cool though to see the project grow and has now an access for public use as of funding this project.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
If you become a patreon it goes away :P

**Comment by Whitebored** [comment]
Pay to win concept.

Lemme smash the screen with stuff that blocks the actual game youre playing and came here for in the first.

And if you pay, they are removed.

Please, give me a serious response instead of this horseshit.

- Regards, Whiteboard.

**Comment by ForbiddenFruitPOD** [comment]
Put the patreon link on top of the minimap. Have it as another icon like where you have the icon for game settings/credits/hero builder.

**Comment by darklordabc** [comment]
I dont want it to be too subtle. Its meant to be fairly obvious

**Comment by ForbiddenFruitPOD** [comment]
Put in on the load screen then.

**Comment by Whitebored** [comment]
Since this topic has obviously been ignored and we still have a link ingame that disrupts the flow of the game whenever missclicked imma hit this topic with some sarcasm since nothing else seems to give:

Make it bigger, hence more people might actually missclick all of their credit card information into donating towards lod.

And for the non-sarcastic part of this post:
People who are intrested in donating to the lodr project will do so, link or no link.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
I understand that its slightly annoying, but so are ads on every freemium app, the slight annoyance is meant to encourage people to support the mod. In an ideal world, the button wouldn't exist, but we don't live in that world and the project requires funding to operate, which means adding incentives for players to support the mod.

**Comment by Whitebored** [comment]
Just put it to the left, above the other ingame menu buttons ontop of the minimap.

Thats probably gonna catch peoples equal attention where people look very often or left of hero portrait.
 - Somewhere people don't click as often and needs to remove it soon as game starts to prevent missclicks.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
I'm (pleasantly) surprised to see an actual constructive suggestion, yeah we could move it, but is that going to really fix the issue? Are you still going to close it at the start of every game?

**Comment by Whitebored** [comment]
Personally and for the majority, if it's not in the way of your own operations it will simply be left there lingering - hence it get's more exposure time -> power of suggestion get's to do it's own thing more than previously.

- Regards, Whiteboard.
