### ISSUE TITLE
Tinker and Ogre Magi perks too low.

### ISSUE THREAD

**Issue by Whitebored** [darklordabc/Legends-of-Dota-Redux#1460]
Tinker and Ogre Magi has each a custom made perk that causes some spells to be refreshed instantly when used on a fairly low ocation.

 - Tinker is at 7% for any abilities tagged with "Science".
 - Ogre Magi is at 2% with any ability.

This is something that is too low and ends up not being part of the game, you merely pick these models as an optimal choice for a particular build you have in mind -> But they never actually prock.

The prock chance needs to be higher (or potentially reworked) to be more of a constant factor of the game.

I suggest these perks simply gets a buff from (Tinker) 7% to 15% and (Ogre) from 2% to 5%.

If these numbers proves too be too much for the game and simply breaks it in half, it demands a rework instead.

---
As it is, these perks only happens once in a blue moon during a game and is as if these models doesn't have a perk at all that affects the game even to the slightest extent as it is in it's current state and ought to be changed to something that < does > affect the game in some shape or form.

- Regards, Whiteboard.

**Comment by Whitebored** [comment]
No responses yet on this thread, bumping thread.

- Regards, Whiteboard.

**Comment by 1ran-wang** [comment]
Orge's model has incredible stat gain. It's still an option even without any perk. Just like mirana.


There are lots of heroes need buff(Tinker puck SK ). But Darklord seems wanna rework the perk system.

**Comment by Whitebored** [comment]
This thread isn't about heroes and their stat growth, it's about the perks.

And they are to change and affect how you play the game in some shape or form.

These perks barely prock at all hence have no prescense during your average game.

#Darklord-perk rumour: I'll have the developer himself step in on this one before jumping to any conclusions.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
There was plans to overhall the perk system, spearheaded by @SwordBacon, under the Hero Mastery project here https://github.com/darklordabc/Legends-of-Dota-Redux/projects/3
But it lost momentum and lack of funding. But I do agree with Techies in the sense that least picked heroes should be prioritized in improving their talents. Generally the more picked a hero is, the worst their perk should be.

**Comment by Whitebored** [comment]
It appears that the overhaul is on hold indefinetly (correct me if im wrong) and thus can be disregarded.

And simply putting less effort into more popular/picked models is a sign of laziness not balancing.

If anything, the perks in this game takes the game to a new level that changes how you play, while if we did the opposite and just turned perks off for a single game, all the highly statted models would be the most OP to pick.

And thats the exact problem here, Ogre Magi is simply picked for his stats and not his perk (since it does next to nothing). Almost the same thing can be said for Tinker.

Their perk should not be worse due to their pickrate/popularity - they should all offer something unique.

It's a simple matter of turning that <2% into 5%> and <7% into 15%> to test out what the effects are on an average game.

And incase that would be way too OP I already have idea's as of how to rework them into something more fair and balanced.

And ofc there can also be a case where it isn't OP, just some crazy stuff in general that evens out by it'self.

- Regards, Whiteboard.

**Comment by Whitebored** [comment]
This topic has still not been adressed as of how it will be treated (now or further down the line) hence bumping it.

It remains the same as before, a non-existant perk that doesn't affect the game in any shape or form and might as well not be there.

Suggestion of changing both of these perks:
Old Ogre Magi Perk: 2% chance to reset cooldown on a casted ability.
New Ogre Magi Perk: Every 10:th ability casted by Ogre Magi will have it's cooldown reset.

Old Tinker Perk: 7% chance to reset cooldown on a "Science" ability on cast.
New tinker Perk: Your next "Science" ability casted will have it's cooldown reset - 30 seconds cooldown.

 - Regards, Whiteboard.

**Comment by 1ran-wang** [comment]
Orge: any 5 spells with cooldown less than 5s + 1 global skill= 10 sec
global skill.

Nice try.


Whitebored <notifications@github.com>：

**Comment by Whitebored** [comment]
That global skill would be unboosted by other common popular picks, (like bloodrage and spell amp passives) Techies and inevitably weak and ignorable during a common game of lod.

 - Where people usually get 3k-7k hp.

I suppose that build could kill wisps who hasn't picked a fleshed out build yet in the fountain.

Otherwise you might want to consider adding: "Next non-ultimate" ability to the perk change instead.

- Regards, Whiteboard.

**Comment by Whitebored** [comment]
This topic still hasn't been adressed properly.

- Regards, Whiteboard.

**Comment by Wouterz90** [comment]
I closed all issues that were older than 3 months or something, you are also fully aware that perks will be getting an update soon.

**Comment by Whitebored** [comment]
Fair enough.

- Regards, Whiteboard.
