### ISSUE TITLE
Ogre Magi Perk, malfunctioning with consumable items??

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1464]
![image](https://user-images.githubusercontent.com/16277198/40883139-b2801154-6739-11e8-907c-dd023a8428cf.png)
Is it possible that the Ogre Magi perk is activating for non-spells and breaking something? 
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/909bb0d15f393d31f7d29250b05a2c2bba59892b/src/game/scripts/vscripts/abilities/hero_perks/npc_dota_hero_ogre_magi_perk.lua

**Comment by 1ran-wang** [comment]
I'm not sure if its related to Orge's perk. I thought it's related to LOD multicast with aghanim.

**Comment by Wouterz90** [comment]
Multicast shouldn't be triggering on consumable items anymore, also perk is gone too
