### ISSUE TITLE
Mastery of Illusion + Rosh = 3 free Aegises

### ISSUE THREAD

**Issue by LostWalker** [darklordabc/Legends-of-Dota-Redux#1466]
Pretty simple bug. Cast Mastery of Illusion or rosh, wait for the timer to run out and then pick up the free aegises

Edit: Quick question. I'm a noob to GitHub. Can someone tell me how to add tags to a post?

**Comment by 1ran-wang** [comment]
This old bug has been reported many times. And easily abusing by pick with Roshify.

**Comment by Wouterz90** [comment]
Would preventing this ability to be cast on roshan/ or going into cooldown without effects solve this?
