### ISSUE TITLE
New Mutator Ideas

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1468]
I am interested in Mutator Suggestions and i would like to ask if there will be some of them implanted in the future like builder one i think it would be interesting to be able to build walls towers gold mines and so on and maybe to be able to upgrade it like in the old version of dota builder reborn

**Comment by darklordabc** [comment]
Yes, there is so many possible ideas, for example I'd like to add pocket towers to the game. If you have any ideas or anyone else has ideas, jot them down in this issue. Even better, if somebody can fund a mutator that would be great.

**Comment by darklordabc** [comment]
Also, prehaps go through this list and see if there is any gems: https://www.reddit.com/r/DotA2/search?q=mutation&include_over_18=on&restrict_sr=on&t=all&sort=new

**Comment by edotenseilove** [comment]
I was thinking about something that were removed and that was stronger neutral creeps like boars and doomlings creeps spawning with healing aura and so on and maybe Fast Neutrals - neutrals in the jungle spawn every 30 seconds (but i dont know if it should be combined with multiple neutrals)
