### ISSUE TITLE
Suggestion : Invincible Buildings

### ISSUE THREAD

**Issue by Ralayax** [darklordabc/Legends-of-Dota-Redux#1485]
Hello everyone,

I think it would be nice to have an in-game cheat/option to toggle building invincibility while in a single-player game.
That way, it would be possible to stall the game indefinitely at will.

What do you think ?

**Comment by darklordabc** [comment]
Make all buildings invincible or just your own teams

**Comment by Ralayax** [comment]
Well sometimes my own bot team pushes while I try to max out some flesh heaps. So two options might be best !
