### ISSUE TITLE
Custom building targetability

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1487]
Hallo I am starting to create my own towers and i want to add them sanctuary ability of shrines  i have succesfully add sanctuary ability but i cant use it because my towers are not clickable is there some kind of modifier that makes units/buildings targetable?

**Comment by Wouterz90** [comment]
Do they have a hitbox?

E:
You can easily add buildings like [this](https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/vscripts/abilities/pocket_tower_test.lua) or [this if you like typescript](https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/vscripts/abilities/pocket_tower_test.ts)

**Comment by edotenseilove** [comment]
I know that and I have succesfully created a tower and now i am trying to add sanctuary ability to that tower.  I have succesfully add it so it is not just unskilled gray ability the only problem is that tower is not targetable like shrines and i am trying to find a way of adding some kind of modifier that makes it targetable so that sanctuary ability will start doing its thing.

**Comment by Wouterz90** [comment]
What model are you using? It's very likely it has no hitbox, which is something that can easily be fixed

**Comment by edotenseilove** [comment]
Well i am using standart tower model npc_dota_goodguys_tower1_top it is standart working tower that is working exacly like normal tower with one ability in addition sanctuary ability but because tower is not clickable like shrine the sanctuary ability can not be triggered

**Comment by Wouterz90** [comment]
Hmm it might be the shrine ability, if that is the one you are adding to it, that's causing this. Try some aura and see if it persists

**Comment by edotenseilove** [comment]
about the hit box because it is originaly a tower it has a hitbox. When i click on a shrine the cursor will change and that means that it is clickable and i will go to it and triggers the ability .But when i click on tower it is a regular move command.

**Comment by edotenseilove** [comment]
I tried to add different aura and it is there but it is not giving me any effect so maybe thats the case
I was using the same way of adding ability as was used with armagedon ability and then i used 

local ability = building:AddAbility("alpha_wolf_command_aura")

        ability:SetLevel(1)
but again ability was there but the effect of that aura was not.

**Comment by Wouterz90** [comment]
I found the issue. Units with baseclass npc_dota_tower have this behavior. 

`npc_dota_badguys_healers` has the good baseclass, also it starts with the ability.

**Comment by edotenseilove** [comment]
Well I actually found it on gametracking - Dota2 github page and i was thinking about theese diferencies between tower and shrine and i have found the exact name of sanctury ability there.

**Comment by edotenseilove** [comment]
Maybe that i will leave that idea of making a tower with sanctury ability and instand of it I will try to make a builder of all dota buildings which will work on the same princip as cherub flower garden but instand of flowers it will create buildings. Anyway thanks for your help I really appreciate it.
