### ISSUE TITLE
New abilities from CHIP

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1491]
Hallo I would like to ask if you are planning to add some abilities from CHIP  Community Hero & Item Project project i think that there are a lots of interesting abilities like superposition that allow you to teleport and leave illusion  behind that continue to channel ability that you were channeling  and so on

**Comment by Wouterz90** [comment]
You could start doing it, I won't do it right now but if the abilities work I have no problem with it.

We need permission first, lets hold off for now.
