### ISSUE TITLE
Saving/Loading Settings in Offline Mode not working

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1492]
Is this by design?

**Comment by Wouterz90** [comment]
Yes, afaik this is to prevent recreating the mod. We might revert this later or find a better solution.

**Comment by darklordabc** [comment]
To clarify it is by design. Right now save settings only work from the official redux workshop entry, this is to prevent clones of redux using the server features (hi Ash), it's an unfortunate by product.

**Comment by edotenseilove** [comment]
So If i understand correctly It was possible to save some patreon features in Ash version and then just load it in official version?
