### ISSUE TITLE
Custom Ability Talents

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1493]
Hallo I succefully managed to add Talents for  sand king imba abilities thanks to ability Deps file but they are not on the right levels is there i way how to bound them to a specific level?

**Comment by Wouterz90** [comment]
I think you should be adding something like this to your talent
"special_bonus_unique_ogre_magi"
    {
        "TalentRequiredAbility"                                                   "ogre_magi_bloodlust"
    }

**Comment by edotenseilove** [comment]
Well I know that but the thing is that talents works but lvl requirements are ignored meaning that if there is a talent for lvl 25 i am able to skill it on lvl 10 15 or 20. I tried to add talent to kv ablilities and then i pick it instand of sixth ability  the result was that i had only 5 abilities but i have my talent guaranteed but on the first available slot than i try to add a talent as a subability and it worked but again i have it on the the first available slot = lvl 10 even if it was suposed to be for lvl 25.

**Comment by Wouterz90** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/npc/npc_abilities_override.txt#L5718-L5727

It seems to work with custom abilities, I don't think the abilitydeps is even needed.

**Comment by edotenseilove** [comment]
Well you are right but it seems that it is only for basic dota 2 talents and not for custom talents of custom abilities

**Comment by Wouterz90** [comment]
I wanted to work on the perks first, but this should be something that we can do. I might experiment later with it.

**Comment by edotenseilove** [comment]
I know that now there are so many things to do reenabling all of the missing abilities perks talents supporting multiple abilities IMBA abilities fix and so on. You are doing great job on Improving LoD redux And I really dont understand why is Ash trying to sabotage your work.

**Comment by Wouterz90** [comment]
I can see where he is coming from, especially since the patreon thing started.

**Comment by Wouterz90** [comment]
Custom talents should be accepted now.

Add a "TalentRank" "1" value

Where the number can be 1 to 4 according to their position in the tree.
