### ISSUE TITLE
Valve fixed status resistance

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1497]
Valve fixed MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING not working and not showing in Hud I have made some tests and it realy works I tried to change basic tenacity bonus ability to provide STATUS_RESISTANCE instand of tenacity and then i changed back aeon disk consumble and when i test it in a real game it was working

**Comment by Wouterz90** [comment]
Can you make a pr for this?

**Comment by edotenseilove** [comment]
![image](https://user-images.githubusercontent.com/19620604/43687455-ab40b16e-98d5-11e8-8902-cbdc8ab35386.png)
 here  is the picture I have Tenacity OP changed from providing tenacity to Status resistance and I changed back aeon disk consumable back too and as you can see on the picture I have 96.3 % status resistance

**Comment by edotenseilove** [comment]
and for the basic tenacity bonus i used:
 function modifier_basic_tenacity_bonus_op:DeclareFunctions()
	local funcs = {
		MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING,
	}

	return funcs
end

function modifier_basic_tenacity_bonus_op:GetModifierStatusResistanceStacking()
  if self:GetCaster():PassivesDisabled() then return 0 end
  return self:GetAbility():GetSpecialValueFor("tenacity_bonus")
end

**Comment by edotenseilove** [comment]
At first  I checked the latest update for Dota Imba And there was this line : Replaced Tenacity with Status Resistance (should only change how DoT affected heroes, also now you can see your status resistance on HUD) and I was wondering that was not possible before so i had to immediately test it

**Comment by Wouterz90** [comment]
Which is nice of you, and my question was if you could make a pull request for it here, so I can merge it in the next update.

**Comment by edotenseilove** [comment]
Done I am not Sure if I done it correctly since it is the first Pull request that i created

**Comment by Wouterz90** [comment]
Looks good! Thanks!
