### ISSUE TITLE
Some Tweaks to Existing Abilities

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1502]
- [x] Glaives of Wisdom: The "1 sec silence on hit" talent is super OP. The talent should either be removed entirely or be changed to "destroys mana on hit, mana destroyed is equivalent to 50% of damage inflicted." **Thinking about making this 25%**

- [x] Doppelganger: With phantom lancer it can create illusions non stop, creating excessive lag. The ability should have a limit of 12 illusions. If you have already generated 12 illusions from this ability, until those illusions die, further casts of this ability should not create more illusions. If you want more than 12 illusions, use other abilities or manta style

- [x] Teleport / x marks the spot: This combo should be a troll combo. It allows the user to cast x marks the spot in fountain, teleport, kill lane creeps and be back at fountain. There is no counter short of actually getting to enemy fountain. Alternatively, give x marks the spot a level 25 talent so if you pick this combo, you can't have the level 25 talent that removes the cooldown on teleport. **Troll combo**

- [x] Redux versions of skills : All redux versions of skills should always be available and made troll combos with their non redux versions.  My reasoning is that some skills only have a single player and a redux version. So if "disable op skills" is not enabled than that skill, even the redux version is unavailable. An example is essence aura and essence aura redux.

- [x]Fury Swipes and Swashbuckle: I don't think its OP enough to warrant making this a troll combo. **I'll leave it troll for now.**

**Comment by Wouterz90** [comment]
Glaives of Wisdom: I think banning the talent is an option. We can't change the effect without remaking the ability. I think the duration could be made shorter too.

Doppelganger: The spell has a cooldown that is higher than the duration. Once again we have no access to the ability.

Teleport/ x marks: They can be countered by a well timed euls or other stuff. I agree it's annoying but not broken.

Redux Skills: I kinda agree here, I don't know why the current situation is the current situation and I want to find that out before I do anything.

**Comment by ForbiddenFruitPOD** [comment]
Doppelganger: with phantom lancer's perk ( -50% cd on illusion creating abilities) and the -7 s cd talent on doppelganger, its cooldown is 1.5 seconds, which can be reduced further by octarine core. Its duration is 8 seconds and each cast extends the duration of illusions by 2 seconds. So basically, every 1.5 seconds, 2 more illusions are created and the duration of existing illusions is increased by 2 seconds.

**Comment by Whitebored** [comment]
If you changed Phantom Lancers perk (which I find ridicilous as well in the first place, as it is a flat better version than Naga siren's perk) with the perk I suggested: PL creates an additional illusion of the same kind when casting an < illusion > ability, he wouldn't be able to spam an infinite army that breaks and lags the game.

Plus it would be along his theme as a master of numbers in illusions.

Trust me on this, it's the half assed perk on PL that broke doppleganger.

Changing his perk would also bypass the issue of not being able to change doppleganger specificly.

- Regards, Whitboard.

**Comment by Wouterz90** [comment]
@ForbiddenFruitPOD 
Your input on talents would be appreciated too.
https://docs.google.com/spreadsheets/d/1G3-Z2lVxym31WRjL6laWFpz7fjoiM5Y_2pblsH4NK2s/edit#gid=0
