### ISSUE TITLE
Unable to choose/identify talents

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1505]
Currently, there is no way to see your hero's talents until you lock in, therefore, you may expecting 1 set of talents, only to get talents you were not hoping for, making your build less effective. I think the simplest solution is to have a duration setting for "enable hero builder." The duration would start its count down at the same time as the in game clock.

For example, I could be able to have hero builder stay enabled for 5 minutes. This would allow me to change the placement of me abilities (for example, swapping your Q and E with each other) over and over again, and by trial and error, I can get the talents I'm looking for, without changing my ability combination. Alternatively, I can just use a different build all together.

**Comment by Wouterz90** [comment]
Picking talents is now possible.
