### ISSUE TITLE
Bots dont appear to be getting Talents

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1510]
The previous system was that they would get talents and auto level them, but something appears to have been gone wrong. Also, bots should not be getting custom talents or replaced talents in general, they should be getting their default talents. 
![image](https://user-images.githubusercontent.com/16277198/46570532-85478b00-c95d-11e8-9fe5-cbcdf6ffa100.png)

**Comment by Wouterz90** [comment]
Looks like this is no longer an issue.
