### ISSUE TITLE
Outdated perk tooltips

### ISSUE THREAD

**Issue by Wouterz90** [darklordabc/Legends-of-Dota-Redux#1511]
- [x] Crystal maiden

- [x] Phantom Lancer

- [x] Slark
- [x] Jugger
- [x] Necrophos
- [x] Spectre
- [x] Grimstroke

**Comment by arkydon** [comment]
Slark, Juggernaut, Necrophos.

**Comment by arkydon** [comment]
Spectre

**Comment by arkydon** [comment]
Grimstroke
