### ISSUE TITLE
Talent tree

### ISSUE THREAD

**Issue by SirRiceAlot** [darklordabc/Legends-of-Dota-Redux#1517]
The talent tree is not corresponding to the hero or the skill picked in single player with bots mode.  Eg. I picked Medusa with split shot but the level 25 talents did not include +7 targets or modifier effect.

**Comment by Wouterz90** [comment]
Did the tree not include it? Might have taken too long to get it from the server, try picking it again when that happens. I can't recreate this issue myself so it might have been unlucky.
