### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1518]
1 - Hero builder interactions with underlord and dark pillow perks are OP. They retain their attribute bonus after each use of hero builder. For example, with dark willow, I can get 6 support skills, level them all up, and get + 48 all stats (6 *4 *2). I then use hero builder, and swap 1 support skill for another and repeat, however, the + 48 all stats carries over.

2 - If you only change your abilities, but not your hero when using hero builder, your hero gains lots of exp and talents are fucked until switching the hero model

3- Glaives of Wisdom is bugged. It doesn't always work. Usually using hero builder fixes it.

A possible solution to # 1 and # 2 is to make it so that whenever you lock in with hero builder it changes your hero to default wisp for like 0.25 seconds before changing it again to your desired hero and ability combination.

**Comment by Wouterz90** [comment]
I don't think the issues with hero builder are high priority, or any at all. 

The glaives issue is known, and should be recreated at some point I'm affraid.
