### ISSUE TITLE
7.20 Patch OP Abilities

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1521]
Bad Juju: -50% cooldown is OP. Create "Bad Juju Redux" with half the cooldown bonus so -15%, -20% and -25% at levels 1, 2, and 3 respectively

Omnislash: It's basically an instant kill button with 1 or 2 attack modifiers. Create an Omnislash redux where its duration at max level is LESS than the duration of ghost scepter / aeon disk. That way these items' abilities garantee survival against this ability. 

Also maybe make Bad Juju (Redux) troll combo with rearm redux.

**Comment by Wouterz90** [comment]
Thanks for mentioning these. Don't have time to look into it, but I just wanted to add them asap.

**Comment by ForbiddenFruitPOD** [comment]
After a bit of playing, I don't think omnislash is as OP as I originally thought. It can be countered by using said items as well as moving into creeps.  The short range, also gives you plenty of oppurtunity to apply disables to any would be omnislahers before they get close enough. 

Bad JuJu is still stupid OP though.
