### ISSUE TITLE
Lich needs a new talent (Sacrifice is gone)

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1524]
The current talent is based on Sacrifice is now removed from the game. 
![image](https://user-images.githubusercontent.com/16277198/48951585-028f8500-ef37-11e8-9a7b-d2d4e4186aa1.png)

**Comment by edotenseilove** [comment]
is it possible to add sacrifice back so that new perk is not needed I have found a lua version of this ability: https://github.com/Elfansoer/dota-2-lua-abilities/tree/master/scripts/vscripts/lua_abilities/lich_sacrifice_lua

**Comment by Whitebored** [comment]
It's about time he gets a new perk anyways.

- Regards, Whiteboard.
