### ISSUE TITLE
Lucky Shot + Curse of Avernus + Heartpiercer + Jingu Mastery causes Dota to CRASH

### ISSUE THREAD

**Issue by mrizwan1993** [darklordabc/Legends-of-Dota-Redux#1527]
Try picking Jugg with the following build:  Take Aim, Jingu Mastery, Curse of Avernus, Lucky Shot, Heartpiercer (IMBA), Time Lock. A few minutes into it, Jingu + Curse of Avernus prock 4 times together and the game crashes. Plz fix.

**Comment by Wouterz90** [comment]
Probably an infinite loop. Let me know if this persists without IMBA spells, those are not supported.

**Comment by mrizwan1993** [comment]
Works if I don't use the IMBA version of the spell - thanks!
