### ISSUE TITLE
Melting Strike Causes Crashes

### ISSUE THREAD

**Issue by lewisallen** [darklordabc/Legends-of-Dota-Redux#1528]
Melting Strike is unskillable and causes the game to crash when your auto attack hits a hero, doesn't crash if you just attack creeps. I have confirmed it causes a crash when you attack bots but have not tested it against other players. Having or not having Aghanim's Scepter makes no difference. Thought it might as how the other Invoker abilities are weird with aghs. I tested it on a bunch of different heroes and with a bunch of different abilities so I don't think it's any weird combination of it and other abilities/hero causing the issue just the ability itself.

**Comment by Wouterz90** [comment]
Disabled
