### ISSUE TITLE
Error crashing on start with single player bot game (macOS)

### ISSUE THREAD

**Issue by qlfwyyd** [darklordabc/Legends-of-Dota-Redux#1531]
Hi, the game is currently crashing for me when I try to start a bot game using the dota_launch_custom_game 786348190 custom_bot command. It starts to load and then crashes with the error in the screenshot below.

<img width="1280" alt="screenshot 2018-12-20 20 01 13" src="https://user-images.githubusercontent.com/10055095/50274950-62c00b00-0492-11e9-9c3e-d2199a763667.png">

**Comment by Wouterz90** [comment]
Afaik this has been fixed, by either me or valve :D
