### ISSUE TITLE
Missing icons and effects on Ubuntu 18.10

### ISSUE THREAD

**Issue by Ralayax** [darklordabc/Legends-of-Dota-Redux#1536]
As the title describes, the abilities created by redux are missing icons and in game effects.

I'm ready to actively debug this, though I'll most likely need instructions.
![capture d ecran de 2019-01-10 17-49-49](https://user-images.githubusercontent.com/3892807/50983820-9ece1500-1500-11e9-8c26-c6029d7125a7.png)

**Comment by Wouterz90** [comment]
Hmm this is weird. I doubt it's really redux related.

There should be a folder named 786348190, if you can open the vpk file in there with something like gfscape we could look if it's there.

Might also want to ask this here: https://github.com/ValveSoftware/Dota-2/issues
