### ISSUE TITLE
Suggestion Consumable items compresed into one buff

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1538]
If a hero consume to many consumable items the other buffs/debufs dont have a space to show on hotbar
I suggest to make a new buff instand of the current permanently gained benefits of  to just show all consumed items in one buff which just update when hero consume another item.

**Comment by Wouterz90** [comment]
I don't think there is a good way to keep track of all the consumed items this way.
