### ISSUE TITLE
Talents dont work after changing build

### ISSUE THREAD

**Issue by Fenekhu** [darklordabc/Legends-of-Dota-Redux#1547]
I don't know if this is an intended punishment for changing builds but it doesn't seem like it is. When I change my build, the talents either have no effect anymore, or they just show up as name 1, name 2, etc.
Keep having to rehost lobbies because someone makes a build and changes and gets their talents screwed up. This has to be known right?

**Comment by Wouterz90** [comment]
Fixed on next update
