### ISSUE TITLE
BUG REPORT 2/24/19

### ISSUE THREAD

**Issue by The700b** [darklordabc/Legends-of-Dota-Redux#1551]
The stash is locked and cannot be grabbed from, Bots get stuck trying to buy items, If you try to play bots with a friend the bots don't fully spawn, only about 9 bots spawn instead of 18 (2 humans), The cour not working and grabbing from the stash to bring your items to you. Rosh cannot be attacked either.

**Comment by ActionAlligator** [comment]
Apparently, the stash bug is occurring in other custom games too if what I'm told is true. So it looks like it's a valve oof.

**Comment by The700b** [comment]
From what i've heard its due to them removing the artifact table from the
shop, Apparently it created a domino effect from what i've heard. May be
entirely incorrect however.

**Comment by ActionAlligator** [comment]
Oh and neutrals keep spawning on top of each other without limit, usually until you crash

**Comment by The700b** [comment]
Another bug I have noticed is when playing it with a friend the bots just
don't load in right and sometimes there will be no bots if you join with
even one player

**Comment by ActionAlligator** [comment]
Not sure about that, sorry; but the neutrals, rosh, and stash bugs are fixed from Valve's side, yay

**Comment by darklordabc** [comment]
This was a valve bug and is fixed now
