### ISSUE TITLE
Can no longer load and save configurations

### ISSUE THREAD

**Issue by ActionAlligator** [darklordabc/Legends-of-Dota-Redux#1560]
As title says; I have no idea why, I keep trying to save and load but nothing happens. There used to be a way to copy & paste the settings in text form, but that's no longer available unfortunately, otherwise I'd just do that. Appreciate anything you can do, thx.

EDIT: oh, and this is put in the console when I try to load
[PanoramaScript] !! (undefined, line:1, col:1) - SyntaxError: Unexpected token o

**Comment by Ralayax** [comment]
Same here !

Edit : 
Fixed for me, praise the dark lord
