### ISSUE TITLE
Suggestion: Permanent attribute steal on essence shift

### ISSUE THREAD

**Issue by Ralayax** [darklordabc/Legends-of-Dota-Redux#1561]
Hey guys,

A while ago, Valve added a permanent agility steal on essence shift when slark gets a kill.
I thought it would be nice to add a permanent strength/intelligence steal component to slarks essence shifts, maybe as OP abilities ?

Praise the dark lord.

**Comment by Wouterz90** [comment]
This has been added to the abilities already, it's not displayed like the normal one though.

**Comment by Ralayax** [comment]
![image](https://user-images.githubusercontent.com/3892807/60770689-3db58180-a0de-11e9-9cad-aeefca89daf8.png)

I don't know if I was really clear in my explantations above, but the strength and intelligence abilities don't seem to have a permanent component to them.

**Comment by Wouterz90** [comment]
It doesn't show it, but after you get a kill with it you will gain strength or intelligence. It's not a green number it just adds 1 attribute to the base stats.
