### ISSUE TITLE
[Crash] Fortify building cheat crashes the game

### ISSUE THREAD

**Issue by Ralayax** [darklordabc/Legends-of-Dota-Redux#1562]
To reproduce : 
1. Fortify buildings with the "-fortify" cheat
2. Let multiple targets approach a (at least T2) tower
3. Game crashes before the tower's attacks come out

I think it is related to the fact that the fortification now allows T2 and above towers to multishot.
The crash doesn't happen when a single target is under the fortified tower, nor when the regular in-game fortification is used.

**Comment by darklordabc** [comment]
Changed the cheat. Now it gives the fountain regen modifier instead of fortify, it will causes the towers to regen health so fast that you wont be able to kill them (well maybe you can)
