### ISSUE TITLE
BUG about Bloodseeker's Thirst

### ISSUE THREAD

**Issue by Klamist** [darklordabc/Legends-of-Dota-Redux#1580]
Why does BloodSeeker's passive "Thirst" has a fixed 900 move speed?
I wonder if it's a BUG or only problem in my games. It happens everytime when someone choose"Thirst", and the movement speed improves directly to Max(which is 900, not 750) while the passive learnt.

**Comment by darklordabc** [comment]
Its fixed to 900 for balance reason, there is an OP version that does not have the limit.

**Comment by Klamist** [comment]
Em, I didn't express well, my fault. The passive skill Thirst will get 900 speed as soon as learnt, even no one's health below 75%. I've banned bloodseeker and Thirst every game these days. So I wander if it's a BUG for me or for Redux.
