### ISSUE TITLE
Tricks of the trade bug with togglable abilities

### ISSUE THREAD

**Issue by onlybiscuit** [darklordabc/Legends-of-Dota-Redux#349]
ultimate stops if u toggle on/off any togglable ability,altho the channel duration still runs it might confuse people with togglable and think the ult is working

**Comment by ZzZombo** [comment]
Recoding it from scratch is easy enough. It's a channeled ability that deals a forced attack via `CDOTABaseNPC:ForceAttack()` to enemy heroes each second.
