### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by SwordBacon** [darklordabc/Legends-of-Dota-Redux#368]
Game Setup:
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\game_setup.css(2331): Failed to set property value (property=align)(value=right)
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\game_setup.css(2414): Failed to set property value (property=margin)(value=auto)
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\game_setup.css(2434): Failed to set property value (property=align)(value=right)

Cheats:
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(9): Failed to set property value (property=border)(value=none)
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(15): Invalid property name: inline-block
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(18): Invalid property name: 0.4s
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(20): Invalid property name: pointer
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(24): Failed to set property value (property=border)(value=none)
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(29): Invalid property name: inline-block
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(32): Invalid property name: 0.4s
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(34): Invalid property name: pointer
[ W Panorama               ]: ****\* Parsing error on panorama\styles\custom_game\cheats.css(52): Failed to set property value (property=visibility)(value=hidden)

I'm using a smaller window size if that matters. 1600x900.

**Comment by leviathan13** [comment]
I still see the three errors

> Game Setup:
> [ W Panorama ]: ***** Parsing error on panorama\styles\custom_game\game_setup.css(2331): Failed to set property value (property=align)(value=right)
> [ W Panorama ]: ***** Parsing error on panorama\styles\custom_game\game_setup.css(2414): Failed to set property value (property=margin)(value=auto)
> [ W Panorama ]: ***** Parsing error on panorama\styles\custom_game\game_setup.css(2434): Failed to set property value (property=align)(value=right)

at the start of every game. You can just dismiss them, but still, that's not supposed to happen.
