### ISSUE TITLE
Create Category Filter to Show perk related abilities | Hookup with GUI Button

### ISSUE THREAD

**Issue by onlybiscuit** [darklordabc/Legends-of-Dota-Redux#423]
**Edit:** This feature is half done. It has the graphical component on the new GUI, its just temporarily deactivated, we just need a coder to hook it up with a filter that when clicked, shows all the perk related abilities. - Darklord

![image](https://cloud.githubusercontent.com/assets/16277198/20588267/ee754bf8-b267-11e6-9db1-131dad7603b1.png)

> Original Post: Right now we have perks that refund mana for light abilities or does extra damage for fire ones. I think we should make a filter for those, like a fire spells filter, ice spell filter, light, dark, etc, it would help people with perks and an easy way for baumi to make his theme videos

**Comment by darklordabc** [comment]
Has been added, but just as a checkbox.
