### ISSUE TITLE
GUI Bugs

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#47]
**1.** Weird category in the sort abilities by categories drop-down box. Only shows neutral abilities, as far as I can tell, was introduced in this merge: https://github.com/darklordabc/Legends-of-Dota-Redux/commit/0c29b640f7e7889b931c3b8d51b5bf178cf7148a
![image](https://cloud.githubusercontent.com/assets/16277198/16546857/ff8bfdf2-419b-11e6-8cbe-479ba6af91f8.png)

**2.** Button is missing to finish bans/ lock build. I suspect it has been pushed down out of sight when the new elements got added above. 
![image](https://cloud.githubusercontent.com/assets/16277198/16546855/dd278aec-419b-11e6-96b3-57362d14ef39.png)

**3.** Hero icon shows in an awkward position, when hero icons are clicked on either the preset builds screen or on the hero select screen. It should be lower down and in a stable positon (i.e. not move when you change the tab).
![giphy](https://cloud.githubusercontent.com/assets/16277198/16546880/98e7ce18-419c-11e6-9db7-1cda390968a7.gif)

**Comment by TideSofDarK** [comment]
Working currently.

**Comment by TideSofDarK** [comment]
#48 Here it is.
