### ISSUE TITLE
Return hints panel to previous position

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#538]
I really don't like how they are right now, and I know its just going to keep annoying me. I'd like them returned to the previous place, with the same size, but hopefully with a style that is more appropriate to the new GUI. 

This change will require modifying the container of the GUI elements so that its has less height, this will also alleviate the chat issue because it won't be blocked as much. 

I know you are not a fan of this design @K1llMan, but I'm sorry, the top thin bar is just not working for me. I'm still open to recommendations but I can't think of any. 
From this:
![image](https://cloud.githubusercontent.com/assets/16277198/20989004/3d4f7446-bd27-11e6-86b8-dd729c83b970.png)

To this:
![image](https://cloud.githubusercontent.com/assets/16277198/20988898/d0bb8090-bd26-11e6-92d3-b9758556dd88.png)

**Comment by jgarbagnati** [comment]
Should be done with https://github.com/darklordabc/Legends-of-Dota-Redux/pull/682
