### ISSUE TITLE
Memes/Petri Redux Compilation

### ISSUE THREAD

**Issue by SwordBacon** [darklordabc/Legends-of-Dota-Redux#544]
So I'm gonna dedicate the next week or so working on a mutator for all the memers out there. The current plan is to make one mutator for a broad variety of memes (twitch, reddit, old sound mods), and another for Petri Reborn memes. 

The mutator works by triggering specific sounds whenever a player casts an ability or does some action. I will be listing my ideas for what sound plays under what conditions below, starting with some obvious ones that would be fun. Multiple sounds can be triggered within one occurrence. 

* Cast Sandstorm => Darude Sandstorm
* Cast Freezing Field => Let it Go
* Cast Black Hole => Tobiwan screaming Black Hole
* Cast Satyr Blast => [HADOUKEN](https://www.youtube.com/watch?v=3lUuLeBH1pY)
* Cast Death Ward => Random dubstep
* Land a Hook => There's a Hook!
* Cast Duel => Its time to D D D D D DUEL!/Attack on Titan/Mortal Kombat
* Win Duel => Final Fantasy Victory/FATALITY
* Cast Phase Shift => WAOW
* Cast Techies Suicide => Allah akbar/WTF BOOM
* Multicast a spell => Casino jackpot sounds
* Kill a hero with Assassinate/Powershot/Sunstrike => MLG 360 noscope/BOOM HEADSHOT
* Charge of Darkness => LEEROY JENKINS
* Have "Gotta Go Fast" + 1000ms => [Sanic theme](https://www.youtube.com/watch?v=PX7zPlQjAr8)
* [Activate Blademail](https://youtu.be/D1efEAcCppw?t=37)
* [Cast God's Strength](https://youtu.be/D1efEAcCppw?t=1m4s)
* Select +6 Treants as a talent => 9 minutes of AdmiralBulldog

Some sounds also have a chance to trigger on death (like sad violin) or on kills (like air horn).

**Comment by darklordabc** [comment]
Some of your @K1llMan suggestions should defintely be added.

**Comment by darklordabc** [comment]
Added although needs updating
