### ISSUE TITLE
Return function to see advanced settings if "Custom Gamemode" is not selected

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#545]
Right now, you can only see the custom settings if you have picked the custom gamemode, but before you could see them (even if you couldn't change them) on any gamemode. For debugging purposes a lone this can I make things more difficult. Change it so that this is still the default view when you click on advanced settings on a non-customgame gamemode.
![image](https://cloud.githubusercontent.com/assets/16277198/21071136/4a6e99de-beeb-11e6-9fad-3c9f6a6bd120.png)
But when you click the settings, you can see the settings, you just can't change them, like before.

**Comment by K1llMan** [comment]
I don't understand what you need. Should I remove screen with tip about enabling custom options? Or what?

**Comment by darklordabc** [comment]
No I like the tip. But when I click option like bots it doesn't show the settings

**Comment by darklordabc** [comment]
In previous versions, I could click on settings like "Game Speed" and it would show the game speed settings page, but it would be grayed out and I wouldnt be able to change anything. But now, If I click on it, it does'nt change anything, and I can't see the options.
