### ISSUE TITLE
Particles not showing ingame, after steamworkshop upload. 

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#55]
The abilities for the item abilities are not showing in-game, when played through the steam-workshop page. 

![image](https://cloud.githubusercontent.com/assets/16277198/16565136/a0a5de58-424e-11e6-92d8-f311d30dd46a.png)

I think this may be because the compiled particles are not properly there. I notice that the Cherub pull request, has the particles in two different extensions, the uncompiled and compilied, and that works when its uploaded to the workshop. 

@Yahnich

**Comment by darklordabc** [comment]
I've found a workaround. 

I find that if just unzip the game and upload it, there will be missing particles. But If I first run the game in the steamworkshop and play the game and use those abilities and THEN upload to the workshop, the game will have working particles.

**Comment by Yahnich** [comment]
yeah because the game needs to run once to compile the maps and particles, which can then be uploaded
