### ISSUE TITLE
Abilities in groups of two, should go vertical, not horizontal, to save space. 

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#62]
To save space, groups of two, should be presented vertically, so not like this:
![image](https://cloud.githubusercontent.com/assets/16277198/16605404/f373c4d2-4371-11e6-9be0-d0a520d9282f.png)
Like this:
![image](https://cloud.githubusercontent.com/assets/16277198/16605390/da30e72a-4371-11e6-8bcd-a24c8a8a3b0d.png)

**Comment by darklordabc** [comment]
Merged

**Comment by Myrl** [comment]
Look at the "Custom Abilities" I've tried this before and IMO, it looks a bit weird on that regard.

**Comment by darklordabc** [comment]
Yeah that is a bit werid, but overall, I think its an improvement.
