### ISSUE TITLE
Not working perks

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#657]
I found some heroes with not working perks:
SPIRIT BREAKER
SLARDAR
ANCIENT APPARITION
SNIPER doesn't deal damage from Shrapnel

**Comment by LODonly** [comment]
Clockwerk's perk doesn't work after death

**Comment by darklordabc** [comment]
@Yahnich any thoughts?

**Comment by darklordabc** [comment]
It seems to be the ones that use filtertables, prehaps its been broken in the code by us, or maybe by valves update.

**Comment by darklordabc** [comment]
@LODonly these perks have been temporarily disabled from the game, thanks for the report.
