### ISSUE TITLE
IMBA Nether Ward turns you into said ward (as it is a passive)

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#660]
I mean you can never be healed or regen health, only take damage by four, also adds the ability it counters in your bar, which you cannot use, but can level up. Passives seems to work though, like Shadow Dance with the health regen going through the roof when unseen (and yes your health is still unaffected, but the number goes up).
While it's a blast to play, I'm guessing the passive should be on the ward.
A hero-friendly version of the countering aura would be a wonderful idea.

**Comment by darklordabc** [comment]
IMBA Issues will be revisted when we actually properly import them after there big patch.
