### ISSUE TITLE
When bots buy 7th item they stay at fountain and do nothing

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#661]
Bots still have issues with their item builds, very late game, they will buy items but have no space for them so they stay in stash, they return to fountain area to pickup these items, but are unable to figure out how to get them.

**Comment by RissaWasTaken** [comment]
Just some visual evidence to add to this:
![botfountain](https://cloud.githubusercontent.com/assets/25391385/22623011/5f70a916-eb1a-11e6-9c96-7dbecf390e27.png)

**Comment by darklordabc** [comment]
Shouldddd be fixed.
