### ISSUE TITLE
[BUG] IMBA Tidebringer/Stifling Dagger lock collision

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#663]
Effect: when Tidebringer or Stifling Dagger's effects go off, it teleports your hero to the target, locking you in place with them until one of you dies. This includes all secondary effects like Torrent triggered from Tidebringer.

**Comment by darklordabc** [comment]
IMBA Issues will be revisted when we actually properly import them after there big patch.
