### ISSUE TITLE
Omnishash IMBA doesn't work

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#664]
You get stuck in, let's say Omnislash mode, you get a yellowish glow, move extremely slow, the camera is stuck on you, you blink to your first target but won't attack it, and can't be given a Move-Attack order. You can't be targeted anymore, be it by abilities or attacks.
Tested with Aghanim's.

**Comment by RissaWasTaken** [comment]
Interaction with IMBA Omnislash and Coup de Grace: Once you are stuck in Omnislash mode (100 move speed, invulnerable), you one-shot everything on the map - creeps, heroes, towers, ancient.

**Comment by darklordabc** [comment]
Fixed
