### ISSUE TITLE
[FEATURE IDEA] Add "Improved Heroes" mode

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#666]
Add a standard Improved Heroes mode which will lock the original heroes' native abilities and leave open only the other slots for drafted abilities.

Would require locking draft selection order to Heroes first, I think, so the abilities would auto-load/lock.

**Comment by AugurM** [comment]
Problem being, some heroes natively have six abilities (Earth Spirit or Shadow Fiend for example).
