### ISSUE TITLE
Skills doing damage to buildings but should not

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#668]
Caustic finale and Living bomb [custom skill] should not damage buildings. Last one just oneshot tier 3 towers when hero has a lot of hp.
https://giphy.com/gifs/living-bomb-legends-of-dota-redux-l3q2EZ3iSrZJOYeGY

**Comment by darklordabc** [comment]
Dealt with here:https://github.com/darklordabc/Dota-2-Redux/commit/b622621b538a76eccc521f15a3a134a33ccfa20d

Also, it now only does half damge if the debuff expires while the unit is alive (like in normal dota)

**Comment by darklordabc** [comment]
Also living bomb fix here: https://github.com/darklordabc/Dota-2-Redux/commit/da16d86126df3d9767808b2fd648c6e73efbc497
