### ISSUE TITLE
Switch team bug - hero doesn't respawn at all

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#671]
Here is a video with this bug https://vimeo.com/201658788

darklord edit: More info here 
![image](https://cloud.githubusercontent.com/assets/16277198/22605953/231e0f0e-eaa6-11e6-901b-087a11913525.png)

**Comment by darklordabc** [comment]
I've played a few games recently and I think this has been fixed.
