### ISSUE TITLE
Infernal blade + gyro/trikle shot = troll combo

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#673]
Infernal blade is cased on every attack and effects buildings
https://giphy.com/gifs/infernal-blade-legends-of-dota-26xBFNTipQobj59lu

**Comment by darklordabc** [comment]
This has been dealt with in the latest commit. Gyro can no longer use infernal blade unless single player abilities are on. If he tries to, he will get a replacement ability which is basically just Chaos Strike. 
https://github.com/darklordabc/Dota-2-Redux/commit/a29b46088684cabee7483d749f04012736775ff2
