### ISSUE TITLE
Spectators get no hud

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#676]
theres no top bar, minimap, ability bar, etc.
![20170130234207_1](https://cloud.githubusercontent.com/assets/18477016/22452565/f4a5e93e-e745-11e6-9148-718f1b531e44.jpg)

**Comment by darklordabc** [comment]
@TideSofDarK this was;nt always the case, I've got a hunch that this problem started when we tried to fix the reconnecting stuck-on-wisp problem.

**Comment by darklordabc** [comment]
Fixed
