### ISSUE TITLE
somethings wrong with exp per level

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#685]
max level was set to 100. not sure what exp/gold were set to, i wasnt paying attention during settings
Edit: asked the host after game. Exp and gold were at 300% he believes. with 3 gold tick.

![20170202220558_1](https://cloud.githubusercontent.com/assets/18477016/22578053/cbc38ed6-e993-11e6-999f-0c47ea09317a.jpg)

**Comment by darklordabc** [comment]
This should be fixed?

**Comment by darklordabc** [comment]
Fixed
