### ISSUE TITLE
Starfall isn't doing damage (only tested with Aghs enabled)

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#688]
Starfall aghs wouldn't autocast while invis (which may be correct, I don't actually know) but even manually casting wouldn't actually play the star FALL animation or do damage. The single 'extra' starfall shows up, but does no damage.

It does cost mana, the hero cast animation occurs, but the stars don't fall (except the bonus star), and no damage is done.

Have not tested Starfall without Aghs.

**Comment by TideSofDarK** [comment]
fixed cb7e0d8
