### ISSUE TITLE
Jingu Mastery has no icon or text in the draft phase

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#689]
Shows up as an empty box with ?? info text. The only reason I know it's Jingu Mastery is that I tried to add it from a friend's build in Single Draft and it told me I couldn't add Jingu Mastery because it wasn't one of my draftable skills.  Otherwise, there is no indication what the 'blank' skill is.

**Comment by darklordabc** [comment]
silly mistake, fixed now
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/e3f700f4829711d848dfc1644dc6c6db33aec3e2
