### ISSUE TITLE
Blade Mail + Octarine Vampirism = Shallow Grave

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#694]
for whatever reason you cannot take fatal damage if you have octarine vampirism skilled and have blade mail active.

**Comment by darklordabc** [comment]
@Yahnich any ideas?

**Comment by DankBudd** [comment]
all you have to do is add a check for whether or not the modifier owner is alive .-. .. or if that doesnt work then add a check for if their hp before heal is 1 or higher

**Comment by Wouterz90** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/da40991ba1ff92ec29857d77e52018d2593ef986
