### ISSUE TITLE
Maxlevel settings is not obeyed 

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#703]
This part of the code does not seem to be applied to the actual game, might be related to how we spawn heros. If you have the setting on anything other than 25, the game will allow heros to level up to 100, always. 
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/vscripts/pregame.lua#L3440

**Comment by TideSofDarK** [comment]
fixed that in f3e23d0
