### ISSUE TITLE
[BUG] Aegis Tower skill (imported from IMBA) does not grant bonus health

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#707]
Skill does grant the bonus armor and armor aura, but does not grant the bonus health.  Tested on multiple heroes, tested dying and respawning.  Health does not get bonus.

![aegis tower](https://cloud.githubusercontent.com/assets/25391385/22717025/bae6782c-ed66-11e6-847e-c113bf0d2184.png)

**Comment by darklordabc** [comment]
Yeah this has always been the case with this ability, not sure how to fix it.

**Comment by darklordabc** [comment]
Fixed
