### ISSUE TITLE
Bots can use items and abilities while Dueled, including breaking out of Duel entirely

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#716]
When under the effect of Duel, bots can escape (Shadow Dance, etc.), activate other abilities (Chem Rage, etc.), and use items (armlet, etc.).  

It *appears* the bot interaction with Duel taps into the same scripting that dictates their behavior while taunted by towers, but that's just my best guess.

**Comment by darklordabc** [comment]
Its only Shadow Dance and Chemical Rage I assume because they use special scripts to activate, the script is obviously not respecting if a unit is stunnned or command restricted.

**Comment by darklordabc** [comment]
Fixed
