### ISSUE TITLE
Some heroes cannot use the extra given ability, e.g. unstable riff

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#717]
This is related to the old problem of abilities not matching up with the hotkey slots. E.g. if life stealer uses the free ability mutator and chooses unstable rift, he will get the ability, but he cant use it, because it says "ability not learnt".

**Comment by ZzZombo** [comment]
You'll have to increase the amount of "slots" for abilities, there is a modifier property dealing with it, called "ability layout".
