### ISSUE TITLE
Arcane Symbiosis featured in Baumi video

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#731]
#730 OtsoTurpeinen just letting you know that Baumi featured your ability in his latest video. https://www.youtube.com/watch?v=SqaZp1FtsE4

He likes it.

**Comment by darklordabc** [comment]
Btw @OtsoTurpeinen I think that invisiblity should break for the host, if one of the infested units auto attack or casts a spell, seems a bit OP otherwise.

**Comment by darklordabc** [comment]
test

**Comment by darklordabc** [comment]
test

**Comment by OtsoTurpeinen** [comment]
Ye, I think the ability could do with some fixes. I already made some fixes (interaction with infest).
I tried to make the ability feel more natural by applying mana gain effects for symbiot to host as well but that has lot of issues that I don't think will get fixed.
So, I think we should add the attack breaking invisibility and add mana regen boost to host. Noticed people getting frustrated when symbiot would use all their mana.

**Comment by darklordabc** [comment]
Attack and spell casting should break invisible, nobody likes getting blown up by invisible enemies. I don't mind buffing mana a bit but if we do that we should nerd somewhere else, because right now, based on the video, it seems too op.

**Comment by OtsoTurpeinen** [comment]
Ye, I try adding visibility break when casting/attacking.

**Comment by darklordabc** [comment]
We had an idea for nerf. Host Sickness. The lpre being that it becomes difficult for the host if he has too many parasites living in him and becomes sick if there is more than one symbiote. So each extra symbiote gives -5 hp regen and -15 move speed, which doesn't kill the strategy that baumi used but gives it a slight drawback. What you think?

**Comment by OtsoTurpeinen** [comment]
I think reducing armor and magic resistance is better idea. Negative hp regen is tricky unless we want host to possibly die of being host and movespeed reductions feel annoying for host player. (and you really want to consider that most games are played among complete strangers, I wouldn't want someone to come and screw with my play by intentionally slowing me down)

**Comment by OtsoTurpeinen** [comment]
I added some balancing.
![sillyness](https://cloud.githubusercontent.com/assets/25548968/23095762/0a59c22e-f618-11e6-8921-d03fc9029438.png)
need to fix some that tool tip but the numbers seemed to be fair. (with full divided we stand stack magic resistance was around -50% total)
btw, this is pretty fun build:
![masochistbuid](https://cloud.githubusercontent.com/assets/25548968/23095591/f1260a54-f614-11e6-90ff-81e745fb7a48.png)

**Comment by OtsoTurpeinen** [comment]
sent pull request with the changes

**Comment by Darkmega18** [comment]
Shouldn't the armor+magic resist percentage go down so to make it WORTH skilling as you can so your host doesn't die as much while increasing the overall potency? It's like, you're better at providing benefits while better at not providing negatives. 

so my numbers might go like:  
stats 4/8/12
regen, 50/100/150
negative resistance 15/12/9
negative armor 6/4.5/3
or something?

**Comment by OtsoTurpeinen** [comment]
I think the negatives could be flat (-4 armor & -12%magic resistance).
I was sort of compensating how much the players gain power as they level up. But I think flat is still better than decreasing value.

**Comment by Darkmega18** [comment]
I'd probably take that deal (If I have any say, cause it is technically your skill). Since it means you'd need all your stacks of reactive armor to and you'd barely just come out on top with magic resistance to cancel out a quad symbiote if you want to go silly with it. Just with my stats and regen numbers so they're nice rounded off numbers. :3

**Comment by OtsoTurpeinen** [comment]
Latest pull request:
stat bonus: 4/8/12
mana regen: 50/100/150%
magic armor: -12%
physical armor: -4.0
Fixed disjointing projectiles.

**Comment by K1llMan** [comment]
Maybe you can use symbiont stats? Like sum mana regen but decrease move speed by 5% from every symbiont (aura's and symbiont skills can increase speed, same thing for armors). Stat bonus sums from main symbiont attribute. Also I don't think that is a good idea to make avaliable droppable items to symbiont. Maybe they should be dropped after skill using or skill may be unavaliable if symbiont carry those items.
