### ISSUE TITLE
Arcane Symbiosis: Certain abilities activate but do nothing

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#737]
I've noticed that certain abilities that would be absolutely brilliant to be used on a symbiote can't be used or are immediately dispelled or don't activate at all while in a host. Abilities such as Dark Forces, Trickshot active (didn't try passive) and Living bomb as a start for what I've found. I didn't keep testing through all the custom abilities but as a guess I think they all apply buff effects to the character to achieve their effects but they can't get applied if the unit is invulnerable due to either dota reasons or mis-tagging of the effect. Can these be checked out?

**Comment by OtsoTurpeinen** [comment]
There are two options to fix the issue.
The two modifier states "Invulnerable" and "Out of game" requires attaching modifiers to explicitly allow application on either of those two states. I could disable those but that would make it possible for AoE effects that bypasses magic immune will target the symbiot.
Other option is the more tedious effort of fixing all non-working abilities manually to include invulnerable and out of game targets.

**Comment by Darkmega18** [comment]
I'd probably rather symbiote is completely invuln, so it might have to be the second. Is it hard to put invulnerable and out of game tags/modifiers to other things? I wouldn't want single target abilities like support abilities to be castable on the symbiote (otherwise you could shallow grave yourself before your host dies and survive among other things) but just stuff that requires a buff to be applied to work, like those 3 abilities I'd just like for them to work. It's probably mostly related to custom abilities that work in similar ways I'd figure.

**Comment by Anarcheevee** [comment]
I believe the issue is most prominent in "aoe" abilities that spawn damaging pulses, such as leshrac's diabolic edict, and a large amount of custom abilities (good examples are the original post's ones.) They spawn projectiles/effects, yet with symbiote they seem to disappear or get stuck above the host actor's head.


Huh I posted on GitHub a surprise

**Comment by Darkmega18** [comment]
Welcome to the party. and yes, I believe so. I almost feel like going through a bunch of AoE moves and seeing which ones work and not. I'd guess attacks that go off immediately like stomps and explodes would work (Necro pulse, centaur stomp, slardar stomp) but stuff like the ones I mentioned that linger or need to remain to do stuff will fail cause the effect can't physically linger. It could also be a weird thing with being in the air that can cause weird targeting differences like making area of effects slightly smaller or need longer reach and such. cause you are technically centered in the air just about the person you're infesting just without a visible model, replaced with a particle effect and sometimes a glitchy floating weapon.

Actually... a rightclick symbiote doing Requiem of souls could be amazing. :D

**Comment by darklordabc** [comment]
@OtsoTurpeinen, Melon had the suggestion of making it so that if the host is disarmed, stunned, silenced etc, those debuffs should be parried to the symbiotes, so that for instance, you can't have right-click attacks coming out of a host that is disarmed. What you think? How easy is that to code?

**Comment by darklordabc** [comment]
Also this is a rather fair point 
![image](https://cloud.githubusercontent.com/assets/16277198/23118026/af91b5aa-f7a6-11e6-8fcd-f0c08aa0422b.png)

**Comment by OtsoTurpeinen** [comment]
The disarm/stun/silence stuff should be pretty simple to reflect on symbiote.
The movement skills that don't "SetLocation" don't work correctly meaning the skills that lerps player position have issues. I might figure out solution but I can't promise anything.
To argue against fixing the issue. Some of the skills can have use if they don't force player to move.
ex. Snowball(optional movement if host is right clicked), Charge of darkness (global stun and lot of bashes in between :D), waveform(damage in wave).

**Comment by darklordabc** [comment]
Yeah it was just an interesting point, no need to add it, I'm more interested in the first fix, with the debuffs.

**Comment by darklordabc** [comment]
I think this is fixed
