### ISSUE TITLE
Revamp Bot Builds

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#742]
Bots won't make use of the new abilities and won't really match the average power level.

Suggested solution:
1. Add to the bot pool some curated combination, mostly making use of adequate passive and/or flesh heaps.
2. Restrict the randomness of the added abilities to ones really improving the bot (no more Take Aim on a melee hero for example).

**Comment by darklordabc** [comment]
I agree but this is part of a larger project to revamp bot builds, including giving them cosmetics and profiles.
