### ISSUE TITLE
[Suggestion] Bots - Sniper

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#743]
Sniper bot isn't able to use Assassinate with Aghs.

Suggested solution:
Short of fixing the bot, maybe give him a custom Assassinate that won't change with an Aghs, or with a custom Aghs effect not affecting the bot behaviour.

**Comment by Wouterz90** [comment]
The problem is that when the bot is given a custom spell he won't be able to use it. We should make sure he only gets 1 aghs boosted ability and just remove the aghs modifier if he gets it for free.

**Comment by darklordabc** [comment]
So does sniper never use assassinate if he has scepter?
