### ISSUE TITLE
New Flesh Heaps (or other stacking abilities)

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#744]
More Flesh Heap variety:
1. Cast Range
2. Cooldown Reduction (but what to do when you reach 100%?)
3. Manacost Reduction (hardly warrant a slot I think)
4. Evasion
5. Armor
6. (Spell) Life steal
7. Attack speed (maybe with BAT adjustment)
8. AoE Radius (but I've been led to believe it's not possible code-wise)
9. Health & Health Regen (separated from strength)

Dual Flesh Heap (that are evidently Overpowered, but would make fine addition nonetheless):
1. Any two basic Stats
2. Attack Range + Vision Range (no one willingly takes Vision Range anyway)
3. Movement Speed + Evasion
4. Size (linked to Strength + Armor but diminishing movement speed), up to a reasonable size at say 25 stacks (see IMBA Flesh Heap)

**Comment by Wouterz90** [comment]
At the time of making these darklord made a strawpoll, and the ones in game are what was voted for. It wouldn't be a lot of trouble making those, but I'm sure there are more important things.

**Comment by edotenseilove** [comment]
I totally agree that would be great if we have more flash heaps also it would be great if someone develop an ability that allows us to combine any 2 passive abilities into one so we can have more abilities than 6 or 7

**Comment by darklordabc** [comment]
@Wouterz90 do you feel like many any more, I'm half/half, up to you. Can you think of any interesting ones or ones from the list you like?

**Comment by Wouterz90** [comment]
I think magic resistance/ cooldown reduction/evasion etc all could be implemented with new instances per stack. This means having 10 stacks is not 1-0.1, but 0.99^10. This makes sure the number never becomes 0 and keeps the balance in check

**Comment by Wouterz90** [comment]
How about something like this for percentage based flesh heaps. 
```
Kills  1  2  3  4
0	0.0	0.0	0.0	0.0
1	0.40000000000001	0.8	1.2	1.6
2	0.7984	1.5936	2.3856	3.1744
3	1.1952064	2.3808512	3.5569728	4.7236096
4	1.5904255744	3.1618043904	4.7142891264	6.2480318464
5	1.9840638721024	3.9365099552768	5.8577176568832	7.7480633368576
6	2.376127616614	4.7050178756346	6.9874250450006	9.2240943234679
7	2.7666231061475	5.4673777326295	8.1035759444606	10.676508814292
8	3.1555566137229	6.2236387107685	9.2063330331271	12.105684673264
9	3.5429343872681	6.9738496010823	10.29585703673	13.511993718492
10	3.928762649719	7.7180588042737	11.372306752289	14.895801818996
11	4.3130475991201	8.4563143338395	12.435839071261	16.257468989892
12	4.6957954087236	9.1886638191688	13.486609002406	17.597349486053
13	5.0770122270887	9.9151545086154	14.524769694377	18.915791894277
14	5.4567041781804	10.635833272547	15.550472458045	20.213139223968
15	5.8348773614677	11.350746606366	16.563866788548	21.489728996385
16	6.2115378520218	12.059940633515	17.565100387086	22.745893332443
17	6.5866917006137	12.763461108447	18.554319182441	23.981959039123
18	6.9603449338112	13.461353419579	19.531667352251	25.198247694497
19	7.332503554076	14.153662592223	20.497287344024	26.395075731386
20	7.7031735398597	14.840433291485	21.451319895896	27.572754519683
21	8.0723608457003	15.521709825153	22.393904057145	28.731590447368
22	8.4400714023175	16.197536146552	23.32517720846	29.871885000211
23	8.8063111167082	16.86795585738	24.245275081958	30.993934840207
24	9.1710858722414	17.533012210521	25.154331780975	32.098031882764
25	9.5344015287524	18.192748112836	26.052479799603	33.18446337264
26	9.8962639226374	18.847206127934	26.939850042008	34.253511958677
27	10.256678866947	19.49642847891	27.816571841504	35.305455767339
28	10.615652151479	20.140457051079	28.682772979405	36.340568475061
29	10.973189542873	20.77933339467	29.538579703653	37.35911937946
30	11.329296784702	21.413098727513	30.384116747209	38.361373469389

```

I'll quickly make a PR with Cooldown Reduction, Evasion and Magic Resistance using those diminishing values. Armor, lifesteal, spell lifesteal, cast range, attack speed all are options that I want to keep open. I don't think health regen would be fun. Mana reduction seems redundant. AoE radius is indeed not reliable.
