### ISSUE TITLE
Add "Passive" to flags

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#745]
Add some more filters, such as:
1. Passive
2. Illusion-friendly (might just need to be added to the Illusion one)
3. Thematic or perk-related filters (trees, lightning, poison, scientific, ...)
4. Tree Destroyer (Because "Dark Forest + Forest Tower Free Extra Ability" is a thing, a wonderful thing)
5. By condition (Silence, Break, Hex...)
6. By Source (Dusk, IMBA, Overflow, ...)

**Comment by darklordabc** [comment]
Out of those I only really like the Passive idea. @TideSofDarK you know how we are parsing npc_abilities data now? Maybe we can check the ability type and use that to make a new category of "passives".
