### ISSUE TITLE
New Mutator - Darker Forest

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#747]
Suggested names: either Choking Forest or "Timbersaw was Right!"

Start as normal, or as Dark Forest, and progressively add more trees as time passes.
Ideally, growing from the existing forest, thicker and thicker.
Even more, camps overrun by trees might send the neutral creeps on a rampage, or just wandering.

**Comment by darklordabc** [comment]
Two problems with this.

1. We can make thicker forest, but within limits, for example, the current generation of trees creates about 1000 temp trees, at around 8000 temp trees the game usually crashes. So there is space for more trees, but not unlimited space.

2. Right now the trees are designed to leave enough space to navigate through them, if we make the forest thicker, Bots will not know what to do, they would need to be given some way to handle it, like a passive that destroys nearby trees.

**Comment by AugurM** [comment]
What about "hostile trees" then?
Gradually popping on the border of existing trees, with someway to inconvenience or attack you. A tiny subtle Overgrowth, Sprout and/or (local) Nature's Wrath at close range.
But if you leave those trees be, for one you get more and more of them and they could potentially wipe out the creep waves left unchecked for a long time.

You could also have a casual Treants (the summoned kind) wave, one treant for each tree, or just stronger for each tree still standing) hunting the player with the most tree cut at some predetermined times.
