### ISSUE TITLE
[Suggestion] Bots - Tiny

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#750]
Tiny never seems to level his Craggy Exterior.

**Comment by darklordabc** [comment]
Its worst than we imagined. Not only does he not level his craggy exterior, he doesnt fully level up his other abilities. This photo was taken on level 28.
![image](https://cloud.githubusercontent.com/assets/16277198/24395903/0a7643b6-13ed-11e7-8a60-9b5f806ed522.png)

**Comment by darklordabc** [comment]
Fixed
