### ISSUE TITLE
Test of Faith (Teleport) - Cooldown Talent

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#758]
Chen's Test of Faith (teleport) cooldown isn't reduced by his talent.

**Comment by darklordabc** [comment]
This is default dota problem, his talent only reduces the damaging Test of Faith, not the teleport one, since its not specific to Redux, it wont be being fixed.

**Comment by crojucuhus** [comment]
But in default dota the talent does work with teleport Test of Faith.
