### ISSUE TITLE
Test of Faith (Teleport) - Anomaly interaction

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#759]
Teleporting multiple creeps back to the fountain with Anomaly doesn't trigger Chen's Perk of giving them a random ability.

**Comment by darklordabc** [comment]
Tried a fix for this, but it still works strangely, seems to cast twice now on the creeps instead of one, but the other units in the anomaly does get any extra abilities. @Yahnich

**Comment by darklordabc** [comment]
I'll be honest, this is such a rare occurence, we probably wont get it fixed, but I'll leave this issue open.

**Comment by Wouterz90** [comment]
It doesn't register as a spell cast by chen, considering how situational this is I'm closing this.
