### ISSUE TITLE
Fatal Error related to meepo clone ability

### ISSUE THREAD

**Issue by AStormOfTranquility** [darklordabc/Legends-of-Dota-Redux#763]
So this is my first time utilizing this, so I don't know what other information is relevant or necessarily how to provide it, so please bear with me on this. That said,

Creating a hero with a flesh heap ability and meepo's clone ability seems to have produced a fatal error during the finalization stage of loading in on the LoD Redux/Local version. As a temporary (or possibly permanent) fix I suggest blocking the combination entirely, or adding a tooltip warning for this.

**Comment by darklordabc** [comment]
I don't think this is related to that build, the game is just crashing all the time now, regardless of abilities or modes

**Comment by AStormOfTranquility** [comment]
Ah, thanks for the heads up

**Comment by AStormOfTranquility** [comment]
Good luck, and thanks for all the hard work!

**Comment by darklordabc** [comment]
Thanks, a hotfix should be online now, hopefully that fixes the crashes, thanks for playing!
