### ISSUE TITLE
Random spawning of wisp bots

### ISSUE THREAD

**Issue by zeonbh** [darklordabc/Legends-of-Dota-Redux#770]
After taking down tier 1 or tier 2 towers the game randomly spawns wisp bots with no models at the fountain on bot sides.

**Comment by darklordabc** [comment]
Should be fixed? Please confirm if it is

**Comment by zeonbh** [comment]
The game crashes after the new update. Couldnt confirm whether its fixed or not.

**Comment by darklordabc** [comment]
Crashes when?

**Comment by zeonbh** [comment]
after the game spwans the heroes, it either crashes or the connection times out.

**Comment by darklordabc** [comment]
Should be fixed  albeit with a less than perfect solution.
