### ISSUE TITLE
Divided we Stand and Arcane Symbiosis - Huge FPS Drop

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#772]
If you get divided we stand (especially with aghs) and get all your clones to use Symbiosis on a hero, the game takes a huge fps hit, it may be related to the game creating the overhead particle many times (it shouldn't, it should just be one particle for any amount of parasites), or it could be related to something else, either way its an issue. 
@OtsoTurpeinen rekon you can help out? 
This is a video of it slowing the game down: https://drive.google.com/file/d/0B7dpugx95_vadk1RS2xzYTJPaWM/view?usp=sharing

I'll make it a troll combo for now, until we can get a fix.

**Comment by OtsoTurpeinen** [comment]
newest pull request should help with the issue. Requires online testing.

**Comment by darklordabc** [comment]
Still has FPS issue

**Comment by darklordabc** [comment]
This should be fixed
