### ISSUE TITLE
[Suggestion] Timbersaw Perk

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#791]
For every destroyed tree - heals him for 0.25% of max Hp and restores 0.20% of max MP. 
•1lvl-600hp-302mp - 1.5hp/0.75mp/tree
------------------------------------------------- 
Here we can see that pure timber is getting a bit more hp than default
•15lvl-1120hp-698mp - 2.8hp/1.4mp/tree     
       Default Perk ~10tree/teamfight - 20hp/20mp 
       Redux ~10tree/teamfight - 28hp/14mp (not even a charge of bloodstone)
•15lvl-(150hp/20 int talent, Bloodstone, Arcanes, Vanguard)-1995hp-1613mp - 5hp/3.2mp/tree
       Default Perk ~10tree/teamfight - 20hp/20mp 
       Redux ~10tree/teamfight - 50hp/32mp (that's more like it, but still shit, usually you cut more than 10 trees)
------------------------------------------------
•20lvl-(150hp/20int talent, Bloodstone, Arcanes, Crimson, Agh)-2590hp-2076mp - 6.4hp/4.1mp/tree
       Default Perk ~10tree/teamfight - 20hp/20mp 
       Redux ~10tree/teamfight - 64hp/41mp (that is noticeably, weaker at start, but a survival machine at the end, but still remember that the enemy team is not weak either, incoming damage is more and more as well)
-----------------------------------------------
•25lvl-(150hp/20int/20str talent, Bloodstone, BoT, crimson, Agh, Octarine, Shiva)-3595hp/3055mp - 8.9hp/6.1mp Semi-Tank DD
       Default Perk ~10tree/teamfight - 20hp/20mp 
       Redux ~10tree/teamfight - 89hp/61mp (not even close to a heal spell)

I wanted to say that existing perk is not that good at the end and becoming useless after first 10lvl passed.
This version tends to keep it usability to the end and it FORCES YOU to play with a tree cutting abilities if you want to actualize this hero's potential. That's where the perk will define your future build, playstyle and item build. There are no turn around spells in dota that cuts trees, [no imba ](https://hydra-media.cursecdn.com/dota2.gamepedia.com/8/88/Embr_move_02.mp3):D

**Comment by darklordabc** [comment]
This has been implmented, but instead of .25% I give 1% per tree. https://github.com/darklordabc/Legends-of-Dota-Redux/commit/8b607c0086d8731df31e2bcb7857dec242eba3c0
