### ISSUE TITLE
Output of print_abilities command

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#792]
heres what I got out of the command when I ran it, @darklordabc 

[VScript] -------------HERO STATS------------
[VScript] HP: 1008/1180
[VScript] EP: 362/362
[VScript] -----------------------------------
[VScript] MR: 0.25
[VScript] ARMOR: 9.4285717010498
[VScript] -----------------------------------
[VScript] STR: 49
[VScript] AGI: 38
[VScript] INT: 26.299995422363
[VScript] -----------------------------------
[VScript] AD: 87
[VScript] AS: 2.0299999713898
[VScript] ApS: 1.1941175460815
[VScript] -----------------------------------
[VScript] MODIFIER COUNT: 15
[VScript] -----------------------------------
[VScript] modifier_item_stout_shield	0
[VScript] modifier_npc_dota_hero_lycan_perk	0
[VScript] night_wolf_p_mod	0
[VScript] modifier_item_yasha	0
[VScript] modifier_spirit_breaker_empowering_haste_aura	0
[VScript] modifier_spirit_breaker_empowering_haste	0
[VScript] modifier_spirit_breaker_greater_bash	0
[VScript] modifier_item_iron_talon	0
[VScript] modifier_thirst_datadriven	0
[VScript] modifier_thirst_visual	0
[VScript] modifier_movespeed_cap	0
[VScript] night_wolf_mod	0
[VScript] modifier_item_power_treads	0
[VScript] modifier_item_empty_bottle	0
[VScript] modifier_tower_aura_bonus	0
[VScript] 	0
[VScript] npc_dota_hero_lycan_perk
[VScript] special_bonus_attack_damage_15
[VScript] special_bonus_hp_150
[VScript] special_bonus_respawn_reduction_25
[VScript] special_bonus_strength_12
[VScript] special_bonus_evasion_15
[VScript] special_bonus_cooldown_reduction_15
[VScript] special_bonus_unique_lycan_1
[VScript] special_bonus_unique_lycan_2
[VScript] visage_grave_chill
[VScript] spirit_breaker_empowering_haste
[VScript] bloodseeker_thirst_lod
[VScript] spirit_breaker_greater_bash
[VScript] lycan_shapeshift
[VScript] night_wolf
[VScript] GetAbilityByIndex requested for invalid index 24
[VScript] GetAbilityByIndex requested for invalid index 25
[VScript] GetAbilityByIndex requested for invalid index 26
[VScript] GetAbilityByIndex requested for invalid index 27
[VScript] GetAbilityByIndex requested for invalid index 28
[VScript] GetAbilityByIndex requested for invalid index 29
[VScript] GetAbilityByIndex requested for invalid index 30
[VScript] GetAbilityByIndex requested for invalid index 31
[VScript] GetAbilityByIndex requested for invalid index 32
[VScript] -----------------------------------

**Comment by darklordabc** [comment]
Cheers
