### ISSUE TITLE
[Suggestion] Beastmaster perk

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#793]
Nothing new to add, but some neutrals like, prowler aura and wolves 30% damage and etc have only 1 lvl to upgrade. Thus bm receives only 3 str cuz it counts as 1 lvl. Maybe he should get 12? As if it was standart passive skill

**Comment by darklordabc** [comment]
Good suggestion, I've uploaded it so, beastmaster now gets 12 bonus strength if there is max level 1.
