### ISSUE TITLE
Online ability tracking is broken

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#798]
No longer tracking abilities. User comments are still being uploaded tho.
http://ec2-52-59-238-84.eu-central-1.compute.amazonaws.com/wordpress/#abilities

**Comment by K1llMan** [comment]
Why do you think so? I saw 'phantom_assassin_coup_de_grace' pick count changed from 27 to 28.

**Comment by darklordabc** [comment]
Tides has fixed it, I think the command to upload was in the wrong location.
