### ISSUE TITLE
Improve scoreboard, so that abilities are shown

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#80]
Current scoreboard:
![image](https://cloud.githubusercontent.com/assets/16277198/16674593/f8165f54-44fc-11e6-9cad-f52fb48047dc.png)

I think it would be cool if you could see your allies abilities in the scoreboard. Also, enemies abilities should become visible on the scoreboard after the game has been going for 2 minutes (or after they have been visible once, its probably easier just to do 2 minutes tho).

The abilities should show their usual tooltip when you mouse over (i.e. they shouldnt just be images).

**Comment by TideSofDarK** [comment]
I think i'll take this task.
