### ISSUE TITLE
Burning Spell Sword spells not reflecting right

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#807]
This is probably a problem for a few spells, but they don't respect the anti-mage spell reflect ability, and continue to target enemies.

**Comment by Wouterz90** [comment]
Which spells have this issue?
Adding this should cancel the effects
`if target:TriggerSpellAbsorb( self ) then return end`

Reflecting them is something the ability should do, don't know about that.
@darklordabc
