### ISSUE TITLE
Ability Points are not been giving out on levels 18 to 25

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#811]
![image](https://cloud.githubusercontent.com/assets/16277198/23592432/fb0f263a-0254-11e7-80db-6865a12dea97.png)

**Comment by LoDfan** [comment]
After 7.06 patch was released I faced this bug several times

**Comment by ZcythierO** [comment]
I experience it too!!

**Comment by darklordabc** [comment]
This problem is'nt predictable is? Sometimes it works, sometimes it doesnt? Everytime I investigated this problem before, it worked for me, we need to find the conditions when it doesnt work to be able to fix it, unless its changed and it never works now?
