### ISSUE TITLE
Search function uses scripting names not ingame names

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#82]
The search function when looking for abilities appears to use the name of the abilities in the scripting files. This is usually not a problem, but some abilities have different names in game, e.g. in game greevils greed is goblins greed in txt files.
Search needs to be improved so it searches the programming names AND the ingame names, i believe the function  $localize is part of the solution.

**Comment by TideSofDarK** [comment]
I will fix it.

**Comment by TideSofDarK** [comment]
#83

**Comment by darklordabc** [comment]
working
