### ISSUE TITLE
Some Terrible troll combo related to Arcane Symbiosis

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#821]
Completely invisible and undetectable enemy hero. Maybe arcane and burrow combo?
![image](https://cloud.githubusercontent.com/assets/16277198/23659484/63a3ac3e-039a-11e7-8d2b-6e5c0f3a01e4.png)
https://i.gyazo.com/e3db4282f76761498a89c08ae11f855b.gif

**Comment by darklordabc** [comment]
@DrTeaSpoon any ideas?

**Comment by grumpsmahboi** [comment]
This happened to me today, it's caused by your arcane symbiosis host using the re-builder while you are inside them. It doesn't kill you, but instead detaches you from them and leaves you as an invincible+invisible entity capable of doing all the things you could do normally in arcane symbiosis.

**Comment by darklordabc** [comment]
@DrTeaSpoon could you make it so using the ingame hero builder ejects the symbiote?

**Comment by LoDfan** [comment]
I suggest to move this ability to super OP. There are a lot of troll combos with this build. Usually tank/carry + Arcane Symbiosis support = team wipe

**Comment by darklordabc** [comment]
Haven't seen since, assuming gone
