### ISSUE TITLE
Innate abilities are not forced on heros if less than 6 slots

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#824]
We should change the slot it tries to go into, be the first one. 
![image](https://cloud.githubusercontent.com/assets/16277198/23704129/822411e0-0457-11e7-971d-db940c9f1311.png)

**Comment by darklordabc** [comment]
@Wouterz90 we had an oversight :(

**Comment by Wouterz90** [comment]
Fixed
