### ISSUE TITLE
Hero Builder sometimes does not work for players (unreproduced)

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#828]
Report by a couple of players including Chris, that sometimes it doesn't open for them. Needs further investigation.
![image](https://cloud.githubusercontent.com/assets/16277198/23778925/5fd15e3c-0591-11e7-9dce-a80e4e01bf18.png)
![image](https://cloud.githubusercontent.com/assets/16277198/23778947/76764f62-0591-11e7-85ae-196b8bec9e4f.png)

**Comment by RissaWasTaken** [comment]
Seconding the occasional inability to use build switcher.  Seems totally random, can't reproduce on purpose.
