### ISSUE TITLE
Tempest double bug

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#832]
![20170310175448_1](https://cloud.githubusercontent.com/assets/19620604/23804982/5ed358ca-05bc-11e7-8adb-145cf959a7dd.jpg)
![20170310175451_1](https://cloud.githubusercontent.com/assets/19620604/23805192/2d372ae8-05bd-11e7-8a0d-3c04a35ac325.jpg)

I would like to report a bug. When i pick chen with tempest double and creap spawn ability with his perk enabled. When i summon tempest double my clone get standard chen skills instand of abilities that i choose.
I am playing this combo a few times and it always worked until now.

**Comment by darklordabc** [comment]
Should be fixed
