### ISSUE TITLE
[Suggestion] Ideas for an Orb Attack

### ISSUE THREAD

**Issue by TheRisen41** [darklordabc/Legends-of-Dota-Redux#833]
## Ideas for an Orb Attack  
  
I created these particles and icon for a lighting style orb attack some time ago. Currently it just stuns on a cooldown which is pretty boring. Please let me know guys if you have cool ideas for this orb attack.  
  
*Ability Icon*
![paralyzing_attack_icon_2](https://cloud.githubusercontent.com/assets/8276667/23805346/cba59836-05bd-11e7-9620-b1cac9b4c054.png)

*Orb Particle Effects*
![custom_paralyzing_attack_orb](https://cloud.githubusercontent.com/assets/8276667/23805295/9a981f20-05bd-11e7-8bff-848592a175db.gif)

*Particles when Orb is ready*
![custom_paralyzing_attack_ready](https://cloud.githubusercontent.com/assets/8276667/23805280/87fbe8ec-05bd-11e7-8e31-ccd4c46ec6fc.gif)

**Comment by darklordabc** [comment]
Maybe has like a 10% chance to purge and increase the cooldowns of enemies spell by 1 second, or maybe without the purge part?

**Comment by darklordabc** [comment]
lowers enemy turnrate dramatically?
Disables healing?

**Comment by OtsoTurpeinen** [comment]
Disable healing sounds like very useful orb against vampiric tanks.

**Comment by darklordabc** [comment]
I agree I think disable healing would be most useful for LoD.

**Comment by TheRisen41** [comment]
Alright disable healing it is. Thank you.
