### ISSUE TITLE
Elemental Mastery OP is overridden by Octarine Core (and scale weirdly)

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#837]
EM OP ultimately gives 50% Cooldown Reduction, but buying an Octarine Core, instead of either adding to it (75%?) or being irrelevant (overruled by the higher bonus of 50%) override the ability and put CDR at 25%. Might be good to investigate its interaction with CDR talents.

Also, EM OP scale weirdly with 10/20/30/50. Shouldn't it be 12.5/25/37.5/50? or add more steps, maybe even higher than 50%?

**Comment by darklordabc** [comment]
@TideSofDarK can you make it so that Elemental Mastery checks if the user has Octarine core (and maybe other cooldown reduction like talents??) and then calculates that in, so that everything is hunky dory? I'm terrible at this maths stuff.

**Comment by darklordabc** [comment]
This was only applied to the OP variant.

**Comment by darklordabc** [comment]
Done
