### ISSUE TITLE
[Suggestion] - OP vanilla abilities

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#838]
Some heroes kits worked over multiples abilities and passives that the current Redux environment doesn't exactly promote, where sinking so many slots into a theme or concept is a flawed approach.
One possible solution is either create OP version of the abilities regrouping some of them or have them give the linked one similarly to Ethereal Jaunt and Illusory Orb.
Some propositions:

1. Night Hunter: regroup Hunter in the Night and the Unobstructed Night Vision and/or Darkness. (This one is tricky as it should be linked to the Night Hunter model for the cosmetic aspect)

2. Morphling - Link Morph STR and Morph AGI

**Comment by darklordabc** [comment]
I get this, but I'd rather deal iwith specific abilities. I dont think hunter in the night needs to give darkness, as its already good enough, darkness is a bit useless, but I dont want to give a free ability with it.
