### ISSUE TITLE
New Ability - Morph INT

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#839]
Letting everyone accomplish that Glass Cannon dream of his.

**Comment by darklordabc** [comment]
Good idea.

**Comment by Wouterz90** [comment]
I'm not sure how the mana interaction would be with int, but I guess that would be fine. I'm also wondering if morph str to agi and str to int at the same time would cause bugs, not sure.

**Comment by Wouterz90** [comment]
#889
