### ISSUE TITLE
Rubick problem

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#852]
-addability, -giveability is not working on him, I suppose because of his inner "Stolen spell" auto added skill, which prevents the adding, look into it pls

**Comment by darklordabc** [comment]
He has too many abilities, he has no free slots for new abilities. 

Related Issue: https://github.com/darklordabc/Legends-of-Dota-Redux/issues/818

**Comment by darklordabc** [comment]
![image](https://cloud.githubusercontent.com/assets/16277198/24931896/6f13e380-1f52-11e7-906e-35ec77231596.png)
Still has the issue
