### ISSUE TITLE
better wukong command (working with ranged so all soldiers fight as long as the enemy is in range )

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#854]
Can someone develop new OP wukong command ability that work with ranged and range increasing abilities like in this video from baumi:  https://www.youtube.com/watch?v=VsrHKVgEqPY

**Comment by darklordabc** [comment]
Sorry I don't think we will be doing this, for at least two reason.
Wukong command is a complicated spell to reproduce from scratch and we have had very bad experience with the original Wukong command causing really bad lag, this has been fixed, but once bitten twice shy, and I don't want to invite any type of lag like that with a recreation. Also, it seems like it would be OP with ranged heros.
