### ISSUE TITLE
New Mutator From "Dota 2 But ..." 

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#860]
The mod is a collection of mutators that would make a really fine addition to the options of Redux.

**Comment by darklordabc** [comment]
I've actually checked it out, and there are maybe a few mutators ideas that could work, but a lot just wouldnt really add much. Like the option where creeps explode, it basically ruins the game, waves all die when one unit dies, and it destroys melee heros. The mod has a few mutators like that, which are fun for 5 minutes, until you realize they break the game. 

But I might be generalizing, is there any mutators specifically you were thinking of?

**Comment by AugurM** [comment]
Well, that is what mutators are for, a quick change of pace.

The most interesting ones, which might turn out to be more extensive, are the river ones, especially **Irradiated** which opens up new strategies and on-the-flight changes.
The random spell on auto-attacks/counter also hold some interest.
The Souls one is interesting too.
The Chen/Enchantress ones might not mesh well with the Roid Jungle Redux tend to have.

**Comment by darklordabc** [comment]
True, that is what mutators are for, but I like mutators to have around a 20% use rate at least, I think a lot of dota 2 mutators would be used only once and not often again, I imagine there rate around 5%. But I believe there is at least 1 good one we should copy over, we just need to figure out which one.

**Comment by GREYSQUID** [comment]
Is this mutator ever coming or has the project been cancelled? I was a bit interested in the random spell on auto-attacks/counter for a game mode with all the spell options redux offers.
