### ISSUE TITLE
[Suggestion] - Adding the River Vials as options or consumables in the shop

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#861]
The 2016 International River Vials are a nice aesthetic option intended to work as is on map.
Would it be possible to add them to the shop?

Better yet, they could be tied to ingame gameplay effects tied to an option at setup.
For example, simple temporary modifiers when dipping into the river:

**Blood**: Attack Speed/Movement Speed Increase but Armor Decrease
**Potion**: Health and/or Mana Regen
**Oil**: Increased Fire Damage both Input/output
**Slime**: Slow AS/MS but Resist Magic (and reduced Health/Mana regen for being slowly digested?)
**Chrome**: Armor bonus & Cooldown Reduction
**Electric**: MS and one-time Mjolnir proc with the damage and jumps based on the time you spent in the river (think static buildup)

**Comment by darklordabc** [comment]
Yeah thats a cool idea! Although, I'm worried it may not be technically possible without changing the map in hammer. Will need more investigation.

**Comment by AugurM** [comment]
Shouldn't it be in the default map (at least the effects) considering anyone can/could use it in any normal Dota match?
It might be interesting to look at Weather effects too, especially if they can be linked to interesting mechanics on the map. I have a burning Dark Forest/Forest Tower mod with the Ashes Weather in mind, maybe with reduced visibility instead of Dark Forest. Oh the possibilities...

**Comment by darklordabc** [comment]
I think those cosmetics are client-side only, i.e. if you buy the pack, to my knowledge they can't be applied by us. I appreciate the idea, but I'm going to close this one for now to clear up the issue list.
