### ISSUE TITLE
Ring of Basilius and Power Treads trigger super OP skill redusing cd by 1...4 sec

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#864]
A lot of troll combos may be created with this super OP skill (I forgot its name, and currently can't check)
This skill reduces cd of all spells by 1...4 simply by toggle Ring of Basilius and Power Treads trigger.
Very easy to ruin some game.

**Comment by darklordabc** [comment]
Nerfed it so that even the OP version needs minimum 3 second cooldown.

**Comment by LoDfan** [comment]
Thanks you
