### ISSUE TITLE
Super OP Vacuum just ruins game

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#865]
It's the most OP skill in the game. You are able just to cast at fountain and pull half of map neutral and enemy units. After that use some splash skills or Echo Slam or some other mass killing skill. No need to leave fountain.

**Comment by darklordabc** [comment]
Yes it's nerfed a bit in next version but if you play with super op you cant expect balanced abilities.  They are called super over powered for a reason.

**Comment by LoDfan** [comment]
May be it's better to rename All allowed map to Super OP? So it won't be the 1st in the list. Most of players create default map, and currently it's All allowed.
I liked very much the time need to start the game (it was , but I think it's better to make default map classical lod to completely destroy outdated LoD official. Players will play Redux classic. 
Votes for redux classic: fast start, stronger towers, enable bans, enable OP (not super OP). Turn off enable builder voting and cheats voting so new players won't be shocked. Also custom and super OP skills aren't available. Ban time, pick time voting time may be same (it's just perfect). And after 1-2 months most part of official LoD players will play LoD Redux Classic. But it should be before other Redux versions in the list.

**Comment by darklordabc** [comment]
What about Hero perks? It would feel a shame not to have them in the classic version even tho they arent official dota stuff. I feel that would have to be a difference with the LoD version.

**Comment by LoDfan** [comment]
Perks aren't balanced well. Some heroes have good strong perks (legion com., techies, antimage, lion, dazzle, and other even not popular heroes have useless perks. Also LoD player new to Redux will have to read all perks.

**Comment by LoDfan** [comment]
Or there should be one more voting disabling or enabling perks.

**Comment by darklordabc** [comment]
Maybe I'll add a vote to enable hero perks

**Comment by darklordabc** [comment]
All_allowed is now fast start, strong towers, op abiliites, enable hero perks, and player bans

**Comment by darklordabc** [comment]
Maps been changed the Vacumnn OP has been nerfed again.
