### ISSUE TITLE
2 Arc Warden's ult versions could be casted endlesly

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#866]
Steps:

1. take 2 AW ults
2. Cast one of them
3. select illusion and cast another ult
4. repeat as much as you want to create lags

**Comment by darklordabc** [comment]
I'll make it possible to only have one.

**Comment by darklordabc** [comment]
Fixed https://github.com/darklordabc/Legends-of-Dota-Redux/commit/152f61db018e648c1967a7a4d3b79e5d81a4872e
