### ISSUE TITLE
When starting at level 3, bots have 5 skill points.

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#869]
Sometimes it's only four points, but almost never do they only have the three points from starting at level 3.
![lodrbotskills](https://cloud.githubusercontent.com/assets/25391385/24467969/9a121224-1484-11e7-8ee2-721e51ed98ac.png)

**Comment by darklordabc** [comment]
Assuming this is related to a fixed bug, if not, comment here and I'll repon.
