### ISSUE TITLE
Phantasm (maybe all illusion builds) cause extreme lag

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#872]
Chaos Knight's Phantasm causes ungodly lag.  Presumably all illusion builds do, but only verified in games with CK.  (We had one game with a Doppleganger build, but CK Phantasm was also in that one, so cannot verify...)

**Comment by darklordabc** [comment]
Assuming this is related to a fixed bug, if not, comment here and I'll repon.
