### ISSUE TITLE
Bristleback skill does not release Quill Spray consistently.

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#873]
Bristleback (the skill) does not seem to always release Quill Spray, even when Quill Spray is taken and leveled. Have had inconsistent results when testing this; sometimes it works, sometimes it doesn't, and I cannot tell what makes the difference.

**Comment by darklordabc** [comment]
Do you have steps to reproduce this problem?

**Comment by RissaWasTaken** [comment]
Sadly no. I'll see if I can try it a few more times to see if I can get a bead on it.

**Comment by Wouterz90** [comment]
There is no LoD/Redux bristleback skill. If this is wrong this is out of our control, only solution would be to make it ourselves but I doubt it would be needed

**Comment by darklordabc** [comment]
Yeah I agree with @Wouterz90 there may be an issue here but since its a) hard to define and hard to reproduce and b) A native dota 2 ability, I don't think its worth recreating the ability itself, hence I'll leave it as it is for now.
