### ISSUE TITLE
IMBA Stifling Dagger interaction with IMBA Infernal Blade is inconsistent.

### ISSUE THREAD

**Issue by RissaWasTaken** [darklordabc/Legends-of-Dota-Redux#874]
IMBA Stifling Dagger and IMBA Infernal Blade interact inconsistently. Sometimes the effects will go off as expected/intended(?), sometimes they won't.  

This was hard to reproduce, so my theory is that it has something to do with the range of Stifling Dagger being outside the expected range of Infernal Blade.

**Comment by darklordabc** [comment]
IMBA problems are not being tracked until we officially support them, the importing process was only half done and as such there is lots of issues, when IMBA does its big patch, we'll more seriously import them.
