### ISSUE TITLE
Collosal Lag with Roshanify into Phantasm, which remains afterwards and stacks

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#875]
Copy and pasted from the discord:

> Alright guys, try and figure this one out. Roshanify+Phantasm on Monkey King. Causes massive lag. :<
> I don't know if it's my internet being on the fritz even if I'm playing local, or if it's actually ingame. cause my bandwidth for internet is actually used up, so my internet is like slower than dial up for a few days. :V
> possibly a memory leak? it has been getting worse the more times I use the roshan into phantasm combo
> using phantasm also reverts my model to my hero but still treats me with the buffs of roshan mode
> but the images retain roshan looks
> My entire build for the curious is:
> Charge of Darkness, Boundless Strike, Reality Rift, Arcane Arts, Roshanify, Phantasm. (basically, charge, transform while charging, hit a person, use phantasm, stun them with boundless, then surround with reality to finish them)

So yeah, I use roshan and then phantasm, first few times it was fine, but then it started catching up on my computer I guess and the subsequent times I did the combo I lagged out until it got unplayable after about 5 uses. There WAS also a chaos knight doing his own phantasm, so dunno if it's phantasm or some other wierd interaction. but there was also this issue I saw about phantasm it could (and probably is) linked to: https://github.com/darklordabc/Legends-of-Dota-Redux/issues/872

and yeah, minor thing, roshan model doesn't seem to persist through using abilities that hide or remove you for a moment to make illusions and stuff, you reappear and it causes the particle effect that appears when roshanify starts up and you revert but keep the effects of roshanify until it expires. The illusions however remain as roshan model until their buff expires.

**Comment by darklordabc** [comment]
I couldnt trigger this, I'm assuming this was related to a broken function that got fixed earlier yesterday, if it continues, post here and I'll reopen this issue.
