### ISSUE TITLE
Respawn Fixes are not being run every spawn (Silencer and Gyro fixes are broken)

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#881]
so silencer gets int steal for free after first death

**Comment by darklordabc** [comment]
This code is only being runned once they spawn the first time, its meant to be run everytime they respawn. 
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/develop/src/game/scripts/vscripts/pregame.lua#L6993
