### ISSUE TITLE
Shadow Demon perk is still bugged

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#882]
*Steps to reproduce:*
1. start LoD redux all allowed/standart
2. pick ShD
3. start game
4. buy all smokes
5. sell all smokes
6. repeat last 2 steps X times
7. buy 1 ward, but don't sell it

*Actual result:*
stats for sold smokes are added

*Expected result:*
it's better to change perk then to fix it
For example reduce cd by 50% for all ShD skills (they aren't very powerful)

**Comment by darklordabc** [comment]
Its been removed from game for now, will later be reworked or patched up.
