### ISSUE TITLE
Anomaly + Wrath of Nature = troll combo

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#883]
*Preconditions:*
it's redux game with custom skills and fast start

*Steps to reproduce:*

1. pick any hero
2. select anomaly + Wrath of Nature + arcane echo/multicast
3. start game
4. make 3+ stack of ancients
5. cast Anomaly on all ancients stack
6. cast Wrath of Nature  on some of creeps in the anomaly area 

*Actual result:*
9-24 times of casting Wrath of Nature
Also if your teammate takes skill for vision all enemy heroes it's a team wipe. Even heroes with 5k hp will die. 
If all map is covered by treant's vision = gg

*Expected result:*
make Anomaly + Wrath of Nature = troll combo

*Note:* 
another skill powerful with Anomaly is laser/pl lance with ags

**Comment by darklordabc** [comment]
I've made Wrath of nature a troll combo for now, may return to the laser and pl issue.
