### ISSUE TITLE
New Ability - Veno Wards that inherit passives

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#885]
Venom wards apply some attack modifiers, from what hero do have. Maybe it will be their OP version, but wards kinda underpowered I think. And make aura applied to them (any hero aura, damage, mana regen, neutral, etc) as simple unit

**Comment by LoDfan** [comment]
I strongly disagree wards are underpowered. Just try my veno exp build.
Venomanser hero, Veno Wards + multicast+ banshee passive+ tome of hero. Just need 25 lvl very fast

**Comment by AugurM** [comment]
Well, if they need two other skills and a specific hero to be useful then...
What they need to more interactions with other skills, at least the poison ones if we are to be thematic should be applied by wards attacks, and ideally have the poison scale with the hero stats, especially his Spell Amp.
I'm not advocating for Bashing or Critting wards here, just not have they only work with a so very specific build.

**Comment by LoDfan** [comment]
It's lod. Some skills only work with very specific builds. And this Veno build is very strong against casters and heroes without detection. After 25 lvl you are able to finish game in 1-5 min (x3 wards with multicast and cd=1 sec just destroy everything)

**Comment by Darkmega18** [comment]
Don't advocate it too much, or it might just become a troll build. ;) (or atleast re-arm and witchcraft should be troll, at the very least. Cause no-one wants to be multi-earthshocked or veno-inundated in a split second with aftershock going at the same time cause of no cooldowns.)
