### ISSUE TITLE
[Suggestion] mage huskar passive

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#886]
The lower mana hero have the more mana_regen/cooldown_reduction he recieve.

**Comment by darklordabc** [comment]
Do you mean the huskar perk but for mana instead of HP, because Disruptor already has that exact perk.

**Comment by Exchy** [comment]
You know, disruptors perk Is really underpowered, because, it's literally nothing in mana regen. like half of cm aura but only when you have close to zero mana (huskars either, people already told 'bout that). The only real boost to mana for mage is devourer passive and imba cm aura. Nothing to add in this list, while hp regen have descent list. And why not after all? ^^

**Comment by darklordabc** [comment]
Are you talking about perks or abilities?

**Comment by LoDfan** [comment]
Huskar's passive didn't give hp reg him. It was his active skill. And it healed in % of Str.

**Comment by darklordabc** [comment]
I still dont know what this issue is about. "[Suggestion] mage huskar passive" what does that mean?

**Comment by LoDfan** [comment]
I think he proposed an idea of new passive ability for casters. But I don't like that idea. Currently there are a lot of skills increasing casters damage and reducing cd and giving mana reg. I have no problems in building strong casters skills. One of my support casters build has winrate ~ 95%. There are a lot of heroes with talents very useful for casters.

**Comment by Exchy** [comment]
Lower mana - lower cd that was the idea. Like lower hp - bigger attack. Just converted to magic stuff

**Comment by LoDfan** [comment]
It'll be useful only with some skills (Ogre's Unrefined Fireblast), other skills may use more mana than available.

**Comment by darklordabc** [comment]
We probably should add another perk related to mana regen, there is basically none, we might do it later, I dont think we need this issue tho.
