### ISSUE TITLE
Consumed Deso doesn't consume or give it's buff

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#891]
what it says on the tin. Desolator doesn't consume properly, but it still saps your gold.

**Comment by Darkmega18** [comment]
Err... and neither does octarine. although it worked last night. O.o

**Comment by darklordabc** [comment]
How many abilities did u have when you tried to consume the items?

**Comment by Darkmega18** [comment]
I was 6 slotted on a rubick. Had Aghs, octarine, deso, daedalus, super TP boots and something else. but I was full and looking to use the deso so to free up a slot for more stuff, but it didn't disappear or work and it ate my gold. :< Was doing... basically siege tank rubick with the new abilities and some stuff. :V

**Comment by darklordabc** [comment]
Rubick is a bad hero to test with, because he has extra abilities because of his broken slots. You probably did not have enough space for another ability, and the consumed items require at least 1 free space. 

@Wouterz90 could we add a check so if the player does not have any free ability slots, it doesnt consume the item?

**Comment by Darkmega18** [comment]
Roger. I had a feeling that might've been part of it.

**Comment by Wouterz90** [comment]
I thought I had a check like that, but I'll check it out

**Comment by Darkmega18** [comment]
it didn't consume the item btw. it just consumed the gold and left the item on me cause it didn't take effect. :V  and can these consumeable items be given to allies? so can there be basically a gold farming guy that gives everyone OP items? and by extension could we make some stat increase items that aren't abilities that take up slots in the same way that dusk has the night time only shop that sells expensive stat bits also for over-farmed people to either become god or help their friends along?

**Comment by Wouterz90** [comment]
Ah that explains what's happening. I'll use a proper cast filter now.

**Comment by Wouterz90** [comment]
#892 This should fix it!

**Comment by darklordabc** [comment]
Fixed
