### ISSUE TITLE
Makes a MultiCast OP variety

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#900]
Just no cooldown, sometimes I take it with only ~2-3 actives, but according to existing OP I either have to w8 until the passive refreshed or throw second skill without. Just move it to OP and not everyone will take it. That's it
Well, maybe you wish to add some changes to be more OP and fit that section
P.S. Ah yes, forgot, change the tooltip of Skywrath Ult pls - that it doubles skill cast, and won't work with non-Skywrath skills

**Comment by darklordabc** [comment]
I'll try to add an OP version of multi cast that has double procs.
