### ISSUE TITLE
Argent Smite = Broke

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#906]
Argent smite doesn't work. you click it and attack an ally or the tower but it deals damage instead and still goes on cooldown. :< was trying to do a "Biotic Rifle" support build, but that made it fail.

**Comment by Wouterz90** [comment]
It did work, but somehow it got broken indeed. On it

**Comment by Darkmega18** [comment]
Roger-roger

**Comment by Wouterz90** [comment]
They were aligned with the perks, which was a bad idea to start with. I made a new filter file, long story short, its fixed
