### ISSUE TITLE
[MODIFIER SUGGESTION] Asynchronous Creep and tower Modifiers

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#907]
I'm wondering if you guys can do versions of the double creeps, tower amount, power tower, and power creeps for just a single team. So say double creeps and strengthening creeps with powered towers for only dire for example so that you could say "vs the creeps" with them having less heroes and make a sort of psuedo horde mode or defense mode sort of game. For using OP builds and "for fun" purposes.

So basically having Power creeps dire/radiant/both/none and do the same for number of towers, double creeps and powered towers. 

And possibly something that makes neutrals spawn out of lane creeps sometimes instead when they multiply as another setting (x2, x2 with chance of allied neutrals, x2 with chance of neutrals with buffs). That would be awesome. :D

and unrelated: Can we make consumeable items able to be given to allies as a secondary selection? Consumeables off, self, self and allies just like giving aghs and stuff to allies?

**Comment by darklordabc** [comment]
There are actually a few different suggestions in here, in future would be better to break into separate issues. I'm anxious to add asynchronous options as they can make it easier for hosts to create unfair games, by choice or by accident, and I've been planning for a long time to create some kind of coop mode, so I'd rather just create the coop mode then a series of asynch options, so I'll probably hold of for now. 

Neutral spawn out of lane creeps is interesting idea, but it needs more definition and how it would actually work. I'm not sure about giving consumable items to allies.

**Comment by Darkmega18** [comment]
Roger. Yeah true, I forgot about the eternal conundrum of things being made for originally good causes but shitheads always coming along and abusing such thing... Co-op mode sounds cool actually. :D 

I'm trying to think of a balancing factor for the neutrals from lane creeps thing. but thinking on it again it just sounds like a random thing that could unbalance pushes if it's just handled as a random trigger. But i was thinking it could be some kind of special back-up ability that you could trigger for your team from a barracks? Like, give the barracks an ability that lets a hero spend gold at it by rightclicking on the barracks at close range like a shrine and it buffs the next wave of creeps to spawn heavy melee or ranged creeps depending on the type of creep that is buffed but in that lane. With super creeps making even ancients instead as basically a push or super distraction that you can use to zerg rush enemies. But the drawback would be because they're neutrals they'd give more money to the enemy team if they interject and they're not just murdered by a turret. :V 

For the consumeables it's just from the stand point of making a really good currency making build that would be used to buff the rest of the team in a roundabout way as a strat so that a "team farmer"'s job doesn't just end at the point of everyone having a perma-aghs and a moonstone now with the ability being there to take it even higher if the game allows it.
