### ISSUE TITLE
Illusions of OTHER heros dont have correct abilties

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#917]
Disruption and Agh Phantasm illusions casted on ally/enemy possess My own skills, which is wrong. And thus I loose the benefit from having those skills, it's becoming useless when your overfarmed ally 5 PA illusions have your 6 active spells

**Comment by Wouterz90** [comment]
I will look into this tomorrow, I hope recreating the spells will do the trick

**Comment by darklordabc** [comment]
Should be fixed
