### ISSUE TITLE
[Suggestion] Skywrath Agh

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#922]
Take out his Agh and make it as a separate ability. "Double cast a spell and auto aim it to enemy unit. Heroes takes priority"

(Warlock bonds reverse - healing bonds, casts on ally, just another suggestion)

**Comment by Wouterz90** [comment]
This is extremely strong, I would like to make it but I don't recommend it.

**Comment by LODonly** [comment]
It's enough to work with Skywrath abilities. Also perk and talents make Skywrath very good caster. He is already strong enough.

**Comment by darklordabc** [comment]
I think this would be a good ability to make but I'd rather it be a separate ability, one that automatically fires the same spell at an alternative enemy, it would be like another multicast or spell echo ability. We could balance it by having a cooldown, or extra manacost for the second spell cast, or by perhaps only a chance to proc, I would go with cooldown imo.
