### ISSUE TITLE
meepo perk error

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#925]
[VScript] Script Runtime Error: ...cripts\abilities\hero_perks\npc_dota_hero_meepo_perk.lua:49: attempt to index global 'HeroList' (a nil value)
    stack traceback:
	    ...cripts\abilities\hero_perks\npc_dota_hero_meepo_perk.lua:49: in function <...cripts\abilities\hero_perks\npc_dota_hero_meepo_perk.lua:47>

herolist is probably server only or something

**Comment by darklordabc** [comment]
Duplicate of #919
