### ISSUE TITLE
Timeout on review phase, no hero on reconnect

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#926]
i haven't been able to play redux for a week or so. every time i try to play, even in solo games, ill get timed out after everyone readys up and we move on the review phase. 
when i reconnect i don't have a hero, cant control my teams courier or anything.

no idea what causes this, but i've seen it happen to others fairly often.

**Comment by darklordabc** [comment]
Is this on both local and regular version?

**Comment by DankBudd** [comment]
just downloaded local to test, i did not time out on local version.

also i randomed "invoked spell"
![20170418195154_1](https://cloud.githubusercontent.com/assets/18477016/25157701/eac5f3ce-2470-11e7-9281-5b6726c7d29b.jpg)

**Comment by nikypage** [comment]
Have the same problem 
Also I was hosting thw game

**Comment by darklordabc** [comment]
This is a hard problem to diagnose because I can't reproduce the problem. Can either of you try disabling vulkan support on steam and see if that helps?

**Comment by DankBudd** [comment]
i dont have vulkan support enabled

**Comment by nikypage** [comment]
It could be that on lower spec computers it struggles to load because my computer is quite slow once its in game its fine but when its trying to load in it stutters

**Comment by DankBudd** [comment]
this seems to be fixed? i've played several games on regular version and i don't time out anymore.

@nikypage do you still time out?
