### ISSUE TITLE
Custom Flesh Heap's don't gain stacks from denied heroes

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#927]
you have this in your flesh heaps
`if self:GetCaster():GetTeamNumber() ~= hVictim:GetTeamNumber() and self:GetCaster():GetTeamNumber() == hKiller:GetTeamNumber() then`

if you remove the killer team check they should properly gain stacks from denied enemy heroes, like regular flesh heap does

**Comment by Wouterz90** [comment]
That's a rare one, good catch.

**Comment by darklordabc** [comment]
Has this been fixed @Wouterz90, can we close this issue?

**Comment by Wouterz90** [comment]
I don't remember fixing this, so I guess not. Now I did
