### ISSUE TITLE
Troll combo from baumi's last vid. looks salty.

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#932]
https://www.youtube.com/watch?v=MOsxSEu12YM

Basically symbiosis + assimulate (combined with a push build) = complete invulnerability for 2 or more people until the unassimulates. immobile, but when combined with a push strat it becomes deadly overpowered with the right combination like the push strat they did.

better nuke it before everyone learns about it and plays it constantly and no-one has any fun ever. :V

**Comment by darklordabc** [comment]
Thanks man but I'm already ahead of you on this. Made it a troll combo about 10 hours ago.

**Comment by Darkmega18** [comment]
Roger that. no problemo then. :)
