### ISSUE TITLE
Talents not working after adding an ability 

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#938]
When I added an ability using -addability command I am unable to choose a talent and when I added an ability after lvl 25 with fully upgraded talents then they just stopped working

**Comment by darklordabc** [comment]
This is intended, adding abilities removes all talents. Heros can only have around 16 abilities, talents take up a large share of that, if we didn't remove talents, you would only be able to add a couple of abilities.
