### ISSUE TITLE
Potential problem with flesh heap cast range

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#940]
should be cast_range_bonus?
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/f7e9a235a6cdc45593480f1c5e5c16144bd371e3#diff-a03180b8dfc09d2826ebca49cbb6e25dR126

**Comment by Wouterz90** [comment]
MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING, but yea. Thanks!
