### ISSUE TITLE
[Custom Skills] Some invis skills are available when no invis is voted 

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#941]
1. Invis aura
2. Hit and go to invis for 3 sec (I'm not able to check its name right now)
May be there are some more, but these 2 are picked very often when no invis is voted.
Also I have a question about TA perk: should it be disabled for this mode, or it's just not strong?

**Comment by darklordabc** [comment]
fixed here https://github.com/darklordabc/Legends-of-Dota-Redux/commit/fa78027472f85e33b74555901e85b3db6efdc0e7

I thought about TA perk, I have never seen it be used once, so I don't think its worth disabling it.

**Comment by LoDfan** [comment]
thx
