### ISSUE TITLE
Witchcraft + Unrefined Fireblast = troll combo

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#943]
I just need 4 skills to kill any hero: Witchcraft + Unrefined Fireblast + 2 multicasts/multicast + arcane echo

**Comment by darklordabc** [comment]
I'll make the two multicast troll combos.

**Comment by LoDfan** [comment]
It won't help. I'll pick Witchcraft + Unrefined Fireblast + usual multicast (not redux) + arcane echo = same permabash shit

**Comment by darklordabc** [comment]
Arcane Echo and Multicast is already a troll combo.

**Comment by LoDfan** [comment]
![20170428160913_1](https://cloud.githubusercontent.com/assets/24685202/25532100/c4af8c6a-2c34-11e7-9acd-48a51615f3b6.jpg)
This game was today. Look at ogre's pick. That's why I wrote about Witchcraft + Unrefined Fireblast + usual multicast (not redux) + arcane echo
