### ISSUE TITLE
Remove secret ability "Spell immune"

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#945]
Some unfair players are picking it all the time in dota map with custom settings.
![20170425230141_1](https://cloud.githubusercontent.com/assets/20225508/25409127/5f19095c-2a19-11e7-877a-203f79df293f.jpg)

**Comment by darklordabc** [comment]
How are they picking it? It's not on the menu to pick

**Comment by LoDfan** [comment]
I don't know. May be some developer made a commit with changes to its name. And during pick phase he selects it via search. But anyway such bug or secret was used by several players (or he changes his nickname often)

**Comment by tmate93** [comment]
I don't know if it's true, but i guy i played with said he got it as a random ability when he didn't picked a skill for one of his slots.

**Comment by darklordabc** [comment]
Fixed
