### ISSUE TITLE
mana shield + essense aura + arcane orb is troll combo

### ISSUE THREAD

**Issue by vird** [darklordabc/Legends-of-Dota-Redux#947]
+Arctic Burn makes it ultrafast hero-melderer

**Comment by LoDfan** [comment]
I don't think it's very strong. There are a lot of counter builds: manaburn, control, veno ward, rat fast push.

**Comment by darklordabc** [comment]
Yeah I agree with lodfan, I dont think its strong enough to be a troll combo, especially since it requires 3 abilities and troll combos are usually just 2 abilities.
