### ISSUE TITLE
Holy Persuation doesn't work on Ancient Creeps. 

### ISSUE THREAD

**Issue by Lee91x** [darklordabc/Legends-of-Dota-Redux#948]
Holy Persuation with Aghanim Scepter doesn't work on Ancient Creeps as it should do.

**Comment by DankBudd** [comment]
might need to have chen as your hero for that

**Comment by LoDfan** [comment]
You need to pick Chen's ult. It worked fine for me.

**Comment by darklordabc** [comment]
There is already a warning for the interaction with ancient creeps 
![image](https://cloud.githubusercontent.com/assets/16277198/25511901/69aa54de-2c0d-11e7-9300-779166671f47.png)
