### ISSUE TITLE
Jingu redux missing some particles and sound

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#951]
snippits from my own code

kv
-----------------
		"precache"
		{
			"particle" "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_overhead.vpcf"
			"particle" "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_hit.vpcf"
			"particle" "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_stack.vpcf"
			"particle" "particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_start.vpcf"
			"soundfile" "soundevents/game_sounds_heroes/game_sounds_monkey_king.vsndevts"
		}

		"modifier_jingu_mastery_buff"
		{
			"EffectName"		"particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_overhead.vpcf"
			"EffectAttachType"	"follow_overhead"
		}
			

lua
-----------------
		-- overhead jingu particles
		if not target.jingu then
			target.jingu = ParticleManager:CreateParticle("particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_stack.vpcf", PATTACH_OVERHEAD_FOLLOW, target)
			ParticleManager:SetParticleControl(target.jingu, 0, target:GetAbsOrigin())
		end
		ParticleManager:SetParticleControl(target.jingu, 1, Vector(0,jingu:GetStackCount(),0))

		--shiny explosion particles on caster
		local explo = ParticleManager:CreateParticle("particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_start.vpcf", PATTACH_ABSORIGIN_FOLLOW, caster)
		ParticleManager:SetParticleControl(explo, 0, caster:GetAbsOrigin())

		-- jingu start sound
		EmitSoundOn("Hero_MonkeyKing.IronCudgel", caster)

		-- jingu hit pfx on target
		local hitPfx = ParticleManager:CreateParticle("particles/units/heroes/hero_monkey_king/monkey_king_quad_tap_hit.vpcf", PATTACH_ABSORIGIN_FOLLOW, target)
		ParticleManager:SetParticleControl(hitPfx, 1, target:GetAbsOrigin())

**Comment by Exchy** [comment]
Grave guard Op lacks particle texture and flamebreak OP has no projectile

**Comment by darklordabc** [comment]
@DankBudd could you add this to the mastery ability. I never noticed it missing particles.

**Comment by DankBudd** [comment]
#956

**Comment by darklordabc** [comment]
Fixed by the one and only dankbudd himself
