### ISSUE TITLE
[Request] Consumable and bots

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#952]
In single player game, I want to have a possibility equip bots with consumable items. I hope this will be possible, please :3

**Comment by darklordabc** [comment]
Are you thinking about giving consumed items to allied bots or enemy?

**Comment by Exchy** [comment]
Yep, not enemy, just ally, sometimes want to be a farming boy who equip his team. And yeah, allow to make infinite pauses without limit and duration of them as well
