### ISSUE TITLE
Infinity Templest Double

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#953]
1. Pick  Templest Double and  Templest Double Redux + some skill you want to spam (for example tombstone)
2. Start game
3. Reach level 6
4. Use spam skill +  Templest Double
5. Select TD and use spam skill and Templest Double Redux 
6. Select TD Redux and repeat step 4
7. Go on spamming

Expected: 
 Templest Double +  Templest Double Redux = troll combo

**Comment by LODonly** [comment]
Also it gives ability to use midas and other items without cd and cause a lot of lags because of memory leaks.

**Comment by darklordabc** [comment]
Tempest doubles should be troll combos https://github.com/darklordabc/Legends-of-Dota-Redux/commit/723dded8cd440e2ea2bed941ada3181fa920be35
