### ISSUE TITLE
Reopen  #943 Please. This permastun bullshit should be added to troll combo

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#954]
![20170428160913_1](https://cloud.githubusercontent.com/assets/24685202/25532181/0e008acc-2c35-11e7-8e4c-520118274681.jpg)
(ogre's skills)

**Comment by darklordabc** [comment]
I've made Multicast troll combo with spell echo, I think thats fair because the other multicast is a troll combo.

**Comment by LoDfan** [comment]
Thanks
