### ISSUE TITLE
suggestion New ability Takeover

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#957]
Is it possible to create an ability that allows you to take-over neutrals and get their abilities for example you will use it to wolf and you will get his model and his skills so you will have your abilities and abilities of wolf until you take over another creep and get his skills

**Comment by DankBudd** [comment]
so basically dooms devour but you also get the creeps model >.>
its possible but could cause problems in redux, ability slots are a precious commodity
