### ISSUE TITLE
Fury Swipes/Fury Swipes Redux Troll combo

### ISSUE THREAD

**Issue by Lee91x** [darklordabc/Legends-of-Dota-Redux#958]
Fury Swipes/Fury Swipes Redux deals way too much damage.

**Comment by LODonly** [comment]
Totally agree. I used Fury Swipes Redux + Fury Swipes + rapidfire and a lot of heroes die in a second

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/344bcbb86bcd74e48b212b3a90fb9127f72e6844 I agree
