### ISSUE TITLE
Wind Soul works with shadow amulet

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#960]
It's possible to reduce cd of all skills by clicking on shadow amulet. It's even op with 1 sec version if you use quick cast items on yourself. For me it took 10-15 sec to recast spectre's ult via fast clicking and 3-5 sec via python macros

**Comment by LODonly** [comment]
And make impossible to buy shadow amulet when no invis mode is enabled please

**Comment by darklordabc** [comment]
This has been fixed. However, I havent made shadow amulet banned yet in no invis mode, I didnt bother because who ever buys the shadow amulet just by itself?

**Comment by darklordabc** [comment]
Actually I forgot there is that other invis item, I'll ban the amulet in the mode

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/25e36d87f4e2a6d6db75dee92c4b4f9c147baa4d
