### ISSUE TITLE
Disconnects during game start

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#969]
As I see a lot of players are disconnected during game start (at the moment of hero spawning).
As I understand a lot of high load processes are running at that moment. May be adding some queue for these processes will fix this issue?
(I'm not a developer so it's only my assumption)

**Comment by XAgent1990** [comment]
There once was an automated gamepause until all heroes spawned one by one.
Maybe that would be an attempt to fixing this problem by implementing that again?
I also always had this disconnecting problem myself and this pausing always helped my game.

**Comment by LoDfan** [comment]
It's better to start these high load processes before showing map and heroes (before actual game start). Is it possible?

**Comment by darklordabc** [comment]
This is the major bug, we have been trying to fix this for a long time now, we'll keep trying.
