### ISSUE TITLE
Shadow Fiend has extra abilities when option should disable it

### ISSUE THREAD

**Issue by XAgent1990** [darklordabc/Legends-of-Dota-Redux#970]
All other bots only have their usual abilites, but Shadow Fiend still has 2 extra one.
Nothing more to add.

**Comment by darklordabc** [comment]
This is intended. Otherwise, he would get no special random abilities and it would be unfair to him.

**Comment by XAgent1990** [comment]
Sorry, maybe I have not been clear enough.
I turned on 6 ability slots.
I turned on the option, that bots only have their usual 4 (for shadow fiend 6) abilities
But still Shadow Fiend had 2 extra ones (Shadow dance and cloak and dagger in one case) making him have a total of 8 abilities. I really do not think this is the way it is intended.
I do remember the time he did not get any extra, becaus he needed all 6 slots for his own abilities, but now that he can pick 2 extra ones he does it even when I disable it.

Hope this makes my statement a littlebit clearer
