### ISSUE TITLE
Fountain Psi Blades crashes the game when it gets triggered

### ISSUE THREAD

**Issue by XAgent1990** [darklordabc/Legends-of-Dota-Redux#971]
Want to say that if an enemy is behind the by the fountain attacked enemy, it crashes the game.
Nothing more to add to that.

**Comment by XAgent1990** [comment]
Can still confirm the bug

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/2e2ea2fb7b3bd048b8fec1f6b9ebf23649056bcf Removed psi blades from foutain

**Comment by XAgent1990** [comment]
My suggestion: give it the splash damage from the Ancient dragon 😄
