### ISSUE TITLE
[Suggestion] Add a Movespeed modifier to only raise the upper limit

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#979]

**Comment by XAgent1990** [comment]
Yes please!

**Comment by Darkmega18** [comment]
so a separate ability that's only function is to break your movespeed limit? ;o

**Comment by AugurM** [comment]
No, Movespeed modifier is an option at setup.
Only missing the possibility to only increase the ceiling without a blanket change to the base speed.

This is only in the hope that it would allow movespeed build to really focus on it.
