### ISSUE TITLE
[Critical] Chacra magic and CM cooldown reduce cd of itself (spaming zeus/spectre/NP ult)

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#982]
Steps:
pick Chacra Magic cooldown , Essence Aura and some ult with long cd (also you may pick multicast or arcane echo)
use Chacra Magic cooldown on yourself several times
use ult
repeat last 2 steps as long as you wish

Actual:
Chacra magic and CM cooldown reduce cd of itself so you cast it with cd 1 sec
after stacking CM effect you are able to cast ult without cd
this totally ruins game

Note:
Also add  Chacra magic cooldown with rearm redux as a troll combo

**Comment by darklordabc** [comment]
Sorry I dont understand, How do you cast chakra magic on yourself multiple times. The cooldown is longer than the duration.

**Comment by darklordabc** [comment]
Nonetheless I've made chakra magic cooldown and rearm redux a troll combo

**Comment by LoDfan** [comment]
> Sorry I dont understand, How do you cast chakra magic on yourself multiple times. The cooldown is longer than the duration.

Cd reduction talents + octarine + multicast
