### ISSUE TITLE
Passives from custom abilities aren't disabled by break

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#983]
As players are voting custom abilities on in 90%-95% of games I think it's better to make game more balanced. So passive custom abilities should behave same way as usual passive abilities.

**Comment by darklordabc** [comment]
Lots of them do, its just adding a single line of code into the lua for them. Do you know any specifically that dont disable?

**Comment by LoDfan** [comment]
I can't write correct names right now, but I describe by my words:
Imba protection (dazzle auto save), chance to freeze attackers and towers, return damage by 16% etc. I tried to counter tank build by skills with break and failed cause custom passives were not disabled
