### ISSUE TITLE
Toxic darts have no cd

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#984]
Toxic darts have no cd. It's possible to permabash heroes. Also it procs zeus passive.

**Comment by darklordabc** [comment]
@SwordBacon any idea whats going on?

**Comment by SwordBacon** [comment]
Charges might not be depleting properly, maybe passives like Arcane Echo are messing it up

**Comment by LoDfan** [comment]
100% arcane echo or multicast makes charges not working and it's possible to spam it nonstop

**Comment by SwordBacon** [comment]
Should be fixed with the cooldown issue now
