### ISSUE TITLE
Saints Rage doesn't heal allies/self nor does it seem to cause a slow.

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#989]
what it says on the tin. Friend picked it today in a finger of death + ancient seal nuke combo build. Tried mid game to heal me and himself after a fight, no beuno. tried again 20 secs later cause low cooldown, still no good when right up close. check it out.

**Comment by darklordabc** [comment]
It defintely heals now. Just tested it in a game.
