### ISSUE TITLE
Make Mastery of Magic not trigger spell echo or multicast

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#993]
No need to make them a troll combo there is internal lists that define what abilities wont trigger these two abilities.

**Comment by edotenseilove** [comment]
Make it please only for normall version of mastery not for op one

**Comment by darklordabc** [comment]
Okay

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/f148c7b6f7caf4e1ad790ad2d9951b51652260ea
