### ISSUE TITLE
New Immortal Terrain doesn't apply to the map.

### ISSUE THREAD

**Issue by WilyWilly** [darklordabc/Legends-of-Dota-Redux#996]
I have just the new underwater Terrain equipped, but when I load in, the map still uses my previous terrain. I tried re-installing but it still doesn't work.

**Comment by darklordabc** [comment]
What map are you playing?

**Comment by WilyWilly** [comment]
Single player, which should default to "dota"

Edit: Just tried using a different Terrain (the sandy one) and it still doesn't change. It's stuck on the Monkey King terrain.

**Comment by darklordabc** [comment]
@WilyWilly could u check if this is fixed? It should be

**Comment by WilyWilly** [comment]
It still doesn't work. I load into default terrain. I re-installed LoD:R before doing this. 
Thanks for trying btw. I know it's only visual, but it'd be nice to play with the new water themed stuff.
