### ISSUE TITLE
Make Fountain also break passives of nearby enemies

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#997]
To prevent fountain spawning.

**Comment by LoDfan** [comment]
Here is a list of enemies who are able to kill leavers anyway:

- long range attackers with flying vision
- strong procasters
- AA with ice spells
- heroes with cd reduction talent + cd reduction abilities and AA's ult

But this change will make impossible dispersion heroes with 100% damage resist (there are some builds based on fanatism)
