### ISSUE TITLE
Improve Custom Devour so it works with dooms talents

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#999]
These two talents wont work as they will be looking for the original doom ability, Can we change our custom devours code so that it checks to see if the player has either of these talents and then changes accordingly? 
![image](https://cloud.githubusercontent.com/assets/16277198/26047166/642d4d14-3995-11e7-9668-402c52be7394.png)
![image](https://cloud.githubusercontent.com/assets/16277198/26047111/3d65a7da-3995-11e7-8713-94f90bb1ed86.png)

**Comment by Wouterz90** [comment]
#1002 Should fix both these issues for devour.

**Comment by darklordabc** [comment]
Awesome
